### ISSUE TITLE
Documentation bug rendering markdown, starting with Lint/Debugger

### ISSUE THREAD

**Issue by danbernier** [rubocop/rubocop#10038]
The HTML docs after Lint/Debugger are rendering strangely. The code samples whose lines start with `# bad` or `# good` are turning into `h1.sect0` tags, and rendering as links in the right-nav.

--------

## Expected behavior

The examples from Lint/Debugger should appear as examples, not as section headers. The right-nav shouldn't be full of text links that are supposed to be code comments in the examples, like "good," and "bad (ok during development)".

## Actual behavior

The code examples appear as linked section headers.

![image](https://user-images.githubusercontent.com/13077/130682440-5a69a7ec-ada7-4016-b5ab-f055c15178de.png)

![image](https://user-images.githubusercontent.com/13077/130682470-5b3bec97-3745-4751-b189-43d467d8105f.png)

![image](https://user-images.githubusercontent.com/13077/130682561-8fbe74f5-2c92-4ce2-8a7c-35c9b8896f9a.png)

It continues down, beyond the code comments from [the Lint/Debugger source](https://github.com/rubocop/rubocop/blob/7b0358fe4a6d3b4bd9238667c12c09f3954689ca/lib/rubocop/cop/lint/debugger.rb), which makes me think it's some kind of markdown rendering mode that gets flipped, and eventually flipped back by a farther-down cop's comments.

![image](https://user-images.githubusercontent.com/13077/130682683-944e0a44-e040-4ddf-817f-78db2b5f2a48.png)

## Steps to reproduce the problem

Look at the first linked heading under the [Lint/Debugger docs](https://docs.rubocop.org/rubocop/1.10/cops_lint.html#lintdebugger), titled [bad (ok during development)](https://docs.rubocop.org/rubocop/1.10/cops_lint.html#bad-ok-during-development).

## RuboCop version

This affects version 1.10, based on looking at the URLs.

**Comment by dvandersluis** [comment]
This was fixed in #9522 (you can see it working if you look at the 1.19 docs)

**Comment by danbernier** [comment]
Damn, missed that. Sorry for the dupe and trouble.
