### ISSUE TITLE
Cop idea: Gemspec/TestFiles

### ISSUE THREAD

**Issue by ybiquitous** [rubocop/rubocop#10065]
## Is your feature request related to a problem? Please describe.

I don't think it's necessary to use the `test_files` attribute in a gemspec in most cases, since it has been removed from the [gemspec's official document](https://guides.rubygems.org/specification-reference/) and seems to be no longer recommended.

Also, if removing `test_files`, then we could receive smaller packed gems.

See also the discussions:
- rubygems/guides#90
- rubygems/rubygems#735

## Describe the solution you'd like

I suggest adding a cop like `Gemspec/TestFiles` that warns the use of `test_files` in a gemspec.
(I'm not sure about this naming... 😅 )

## Describe alternatives you've considered

I have no alternatives.

## Additional context

Many gems including Rails have removed `test_files` to reduce a gem size.
(see also rails/rails#22272)

**Comment by koic** [comment]
Apart from this suggestion, the following RuboCop Packaging documentation may also be improved.
https://github.com/utkarsh2102/rubocop-packaging/blob/v0.5.1/lib/rubocop/cop/packaging/gemspec_git.rb#L6-L51

Cc @utkarsh2102

**Comment by utkarsh2102** [comment]
Hi @koic,

> Apart from this suggestion, the following RuboCop Packaging documentation (examples) may also be improved.
> https://github.com/utkarsh2102/rubocop-packaging/blob/v0.5.1/lib/rubocop/cop/packaging/gemspec_git.rb#L10-L51

That seems like a good idea. IIUC, you propose removing any and every mention of `spec.test_files`, right?
Either way, would you be interested in making a PR? (I wouldn't mind even if you go ahead and commit that directly - you already have the rights :D).

**Comment by koic** [comment]
> you propose removing any and every mention of `spec.test_files`, right?

Right! And I can take the doc improvement of RuboCop Packaging!
