### ISSUE TITLE
Autocorrect vs auto-correct

### ISSUE THREAD

**Issue by dvandersluis** [rubocop/rubocop#10095]
```sh
~/code/rubocop$ grep -iro "autocorrect" . | wc -l
    1971
~/code/rubocop$ grep -iro "auto-correct" . | wc -l
    1551
```

Both `autocorrect` and `auto-correct` are used frequently in RuboCop. Should we be consistent? If so, which one?

Any change should only affect comments and other string content, not method names.

**Comment by bbatsov** [comment]
I've been thinking about this myself at some point. I like "auto-correct" better, as it's easier to read, but I assume many people prefer "autocorrect" as it's easier to write. :D According to the dictionaries "autocorrect" is the right spelling, so I guess we should stick to it. (https://www.dictionary.com/browse/autocorrect)

**Comment by bbatsov** [comment]
Btw, I've noticed that we're using `--auto-correct` in the cmdline options, which means the change is going to be a bit more involved, as we'll also have to deprecate those. Anyways, not a big deal.

**Comment by dvandersluis** [comment]
FWIW I was only considering making it consistency in comments/docs. We should probably keep `--auto-correct` regardless (or allow the inner `-` to be optional as @rubyFeedback suggested).
