### ISSUE TITLE
`Style/QuotedSymbols` endless loop caused by escaped quote character

### ISSUE THREAD

**Issue by joshua-v-jones** [rubocop/rubocop#10148]
On upgrading rubocop from version 1.1.0 to 1.22.0 there was a problem running the auto-correct command. The issue causes a file to be continuously filled with '/'s.
--------

## Expected behavior

Normally, rubocop would replace the double ticks with single ticks in this statement:

`:"Le produit avec le SKU \"%1\" n’existe pas" `

Would be replaced with
`:'Le produit avec le SKU \"%1\" n’existe pas'`

## Actual behavior
 Rubocop gets caught in an endless loop continuously generating '/'s like below:
 
 `:"Le produit avec le SKU \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"%1\" n’existe pas" `

The file with this line is never corrected and CLI does not progress.

## Steps to reproduce the problem

Create a ruby file with the line above.

Run rubocop -a

The command line will hang and when forced to exit the file should contain many '/'s.

## RuboCop version

1.22.0
no output possible as the code hangs on an endless loop.

**Comment by dvandersluis** [comment]
`:"Le produit avec le SKU "%1" n’existe pas"` is a syntax error because the inner quotes are not escaped, do you have a better example?
