### ISSUE TITLE
Lint/DuplicateBranch can have legitimate reasons

### ISSUE THREAD

**Issue by ccutrer** [rubocop/rubocop#10153]
If you have a semi-complicated set of conditions, repeating a branch body -- non-contiguously -- can make sense for a compound if/elsif. For example:

```
if condition1
  do_thing1
elsif condition2
  do_thing2
elsif condition3
  do_thing1
else
  do_thing4
end
```

`condition3`'s branch duplicate's `condition1`'s, but you can't simply combine the branches because of the intervening `condition2`, which implicitly means that `condition3` is `!condition2 && condition3`. Repeating condition2 can both make the code longer, and might have performance implications.

--------

## Expected behavior

No offenses for the given code.

## Actual behavior

```
test.rb:7:1: W: Lint/DuplicateBranch: Duplicate branch body detected.
elsif condition3 ...
^^^^^^^^^^^^^^^^
```

## RuboCop version

```
1.22.0 (using Parser 3.0.2.0, rubocop-ast 1.12.0, running on ruby 2.7.2 x86_64-darwin20)
  - rubocop-performance 1.11.5
  - rubocop-rails 2.12.2
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.5.0
```

**Comment by bbatsov** [comment]
We can't possibly know all such implications from static analysis, so in case there are special consideration you should just use a `rubocop:disable` comment around the relevant code.

**Comment by formigarafa** [comment]
This cop does not come up in my project very often, TBH I guess it warned me 2 or 3 times before about cases like the one raised here (and today again).

I came here to check if there have been any update on the cop to make it smarter but to be fair I think I **agree** with @bbatsov  ("can't possibly know all such implications from static analysis").

But I will go further and **disable the whole cop for the project** as I could not find evidence of it doing the work he meant to do in my project. ¯\_(ツ)_/¯

I will add this use-case to help illustrate the case in the hope this could lead to improvements (even if in my code 😉)

```
    if ids.nil?
      full_set # no filter applied
    elsif ids.empty?
      empty_result # filter matching to empty list of ids
    elsif ids.all?(String)
      filter_by_uuids(ids)
    elsif ids.all?(Integer)
      filter_by_ids(ids)
    else
      empty_result # mixed ids: invalid filter
    end
```

Thanks :slightly_smiling_face:
