### ISSUE TITLE
RuboCop is slow - why not mention rubocop-daemon?

### ISSUE THREAD

**Issue by vfonic** [rubocop/rubocop#10172]
I'm always hesitant to use RuboCop as it's too slow and it adds up if it's run too often.
Just running `time rubocop` in one project (~200 files), takes 6 seconds. (after multiple runs)
In another project, with ~400 files, it takes 10 seconds.

It would be great if RuboCop could be run on file save and it would run fast.
I'd love to be able to use RuboCop the same way I use Prettier for my JS/TS files.

Today I discovered an incredible tool called `rubocop-daemon`.
I managed to set it up and it runs RuboCop so fast, it's crazy. :)

I saw this issue where `rubocop-daemon` was mentioned before (3.5 years ago!): [rubocop -a is slow](https://github.com/rubocop/rubocop/issues/6492)
The conclusion of the discussion there was that, in @jonas054's words:
> It sounds like `rubocop-daemon` is the way forward.

I used RuboCop in the meantime and even [contributed a bit](https://github.com/rubocop/rubocop/pulls?q=author%3Avfonic), but I've never heard of `rubocop-daemon` which is a life saver when it comes to "format on save" functionality.

Do you think we should add `rubocop-daemon` somewhere in the documentation and if so, where do you suggest would be the best place to mention it?

/cc @gurgeous @ndbroadbent

**Comment by bbatsov** [comment]
I thought we had mentioned it somewhere already, but I guess we haven't. @dvandersluis can you please tackle this?

**Comment by gurgeous** [comment]
I want to be clear that I love `rubocop-daemon`, and they've done a decent job with reloading, versioning issues, etc. It's just a hard problem. Many moving parts when you throw in rbenv, vscode, vscode-ruby, $PATH, etc. I agree with @dvandersluis - a bit like spring. Not their fault at all.
