### ISSUE TITLE
Do not count explicit block argument for Metrics/ParameterLists

### ISSUE THREAD

**Issue by singpolyma** [rubocop/rubocop#10186]
## Is your feature request related to a problem? Please describe.

A block capture is not really another argument, and having the parameter list be too long vs not based on switching between yield and explicit block feels inconsistent.

## Describe the solution you'd like

`Metrics/ParameterLists` should not count explicit block argument.

## Describe alternatives you've considered

Could offer it as an option instead of changing the behaviour.

**Comment by koic** [comment]
This makes sense to me. I've opened #10188.
