### ISSUE TITLE
Consider flagging all uses of OpenStruct

### ISSUE THREAD

**Issue by mttkay** [rubocop/rubocop#10206]
## Is your feature request related to a problem? Please describe.

`OpenStruct` has been considered problematic for a while now; with the arrival of Ruby 3, those problems have compounded enough for a "Caveats" section to be added: https://docs.ruby-lang.org/en/3.0.0/OpenStruct.html#class-OpenStruct-label-Caveats. In fact, it states at the end:

> For all these reasons, consider not using OpenStruct at all. 

In fact, we found another (undocumented) issue with this class while working on the Ruby 3 migration at GitLab: an application settings test fake inherited from OpenStruct and mixed in other module methods, so as to fake settings keys on code paths where they do not matter.

We found that in Ruby 3, method dispatch in OpenStruct works differently: instead of struct methods being defined lazily upon first access, [they are now defined eagerly in the initializer](https://github.com/ruby/ruby/commit/e026e186f4a01aa3f6cd02ae6ef33f44f129361c#diff-fcafc50c8e2ed25a9c3851150cc0bdb9c9282c201d80574d126e65e8ea84e946). This means that if a class inheriting from OpenStruct attempts to override methods it expects to be dispatched to this struct (such as those included from other modules), the original struct methods would be called instead of the manually defined methods (and all return `nil`), leading to surprising behavior that is inconsistent with ordinary method dispatch in superclass hierarchies.

We therefore started to write a `Cop` that also flags classes inheriting from `OpenStruct`: https://gitlab.com/gitlab-org/gitlab-styles/-/merge_requests/91

However, given the sheer number of potential issues with this class, I think it could be a good idea to flag any use of it outright. Its behavior can typically be approximated by use of test doubles, hashes, or `Struct`s.

## Describe the solution you'd like

Include a Cop that flags any use of `OpenStruct` as potentially problematic. This could be disabled by default.

## Describe alternatives you've considered

A more specific Cop that only flags the additional problem we found, which is broken inheritance chains when inheriting from OpenStruct: https://gitlab.com/gitlab-org/gitlab-styles/-/merge_requests/91

**Comment by mildred** [comment]
> However, given the sheer number of potential issues with this class, I think it could be a good idea to flag any use of it outright. Its behavior can typically be approximated by use of test doubles, hashes, or Structs.

We are using OpenStruct in our codebase for simple things, and this does not belongs to tests. We cannot replace them with doubles. Hashes does not provides a nice method interface like OpenStruct and Struct needs you to define your structure schema beforehand.

Example of code that uses OpenStruct that I believe is completely harmless:


```ruby
    def self.glyphs
      OpenStruct.new(
        action: OpenStruct.new(
          edit_item: 'pen',
          edit_line: 'edit',
          copy_item: 'copy',
          cut_item: 'cut',
          paste_item: 'paste',
        ),
        import: 'cloud-download-alt',
        information: 'info-circle',
        info: 'info'
      )
    end
```

We use it to bundle information about enums too:

```ruby
  FOLDER          = OpenStruct.new(id: 0, name: 'folder',      glyph: 'folder',       export_id: 'F')
  PART            = OpenStruct.new(id: 1, name: 'part',        glyph: 'puzzle-piece', export_id: 'P')
```

**Comment by mttkay** [comment]
@mildred what you describe can be done entirely with `Struct`:

```ruby
Action = Struct.new(
  :edit_item,
  :edit_line,
  :copy_item,
  :cut_item,
  :paste_item,
  keyword_init: true
)

Glyph = Struct.new(
  :action,
  :import,
  :info,
  keyword_init: true
)

def self.glyphs
  Glyph.new(
    action: Action.new(
      edit_item: 'pen',
      edit_line: 'edit',
      copy_item: 'copy',
      cut_item: 'cut',
      paste_item: 'paste',
    ),
    import: 'cloud-download-alt',
    info: 'info'
  )
end
```

In fact, your example does not even utilize the principle use case for `OpenStruct`, which is synthesizing fields on demand:

```ruby
os = OpenStruct.new
os.a = 1
```

The above is not possible to do with `Struct`, and it is this behavior that makes `OpenStruct` difficult to work with and maintain.

**Comment by mildred** [comment]
Here, in your example, there are a lot of repetitions. You need to declare the struct type first, which leads to much more repetition than when using OpenStruct.

**Comment by mttkay** [comment]
Fair enough. In that case, why not just silence the rule?

**Comment by ReganRyanNZ** [comment]
Without fully understanding the problem.. is this a legit substitute? (rubocop is fine with this even when flagging OpenStruct)

    Struct.new(:name, :number).new("Dennis", "123456")
    
It's not as pretty as OpenStruct.new(name: "Dennis", number: "123456"), but gets the job done for 99% of my OpenStruct use cases. If it _is_ legit, then can this monkeypatch replace OpenStruct?

class BetterStruct
  def self.new(**args)
    Struct.new(*(args.keys)).new(*(args.values))
  end
end

This keeps the prettiness of OpenStruct, and avoids OpenStruct. Am I on the right path here, or just reintroducing the same problems?

**Comment by mttkay** [comment]
@ReganRyanNZ Your example is completely legit and is in fact the recommended way to replace _most_ uses of OpenStruct.

You also don't need `BetterStruct`; there is a flag you can set when creating a `Struct` to pass constructor arguments as kwargs:

```ruby
Person = Struct.new(:name, :number, keyword_init: true)
dennis = Person.new(name: "Dennis", number: "123456")
```

Hope that helps!
