### ISSUE TITLE
Issue with Layout/DotPosition

### ISSUE THREAD

**Issue by mdemare** [rubocop/rubocop#10231]
We have `Layout/DotPosition` configured to `trailing`, and suddenly we get warnings for the following code.

```
data_by_row = cells.map do |k,v|
  r,c = CSV::ColumnHelper.from_char_notation(k)
  [r,c,v]
end.group_tuples # <-- rubocop doesn't like this
```

That's new, and we like this style, so we've disabled `Layout/DotPosition`, but we preferred the old behavior.

**Comment by koic** [comment]
This issue is a dup with #10140 and resolved by RuboCop 1.22.3. Can you upgrade to the newer RuboCop? Thank you.
