### ISSUE TITLE
`Lint/IncompatibleIoSelectWithFiberScheduler` suggestion omits require io/wait

### ISSUE THREAD

**Issue by merrilymeredith** [rubocop/rubocop#10269]
The cop `Lint/IncompatibleIoSelectWithFiberScheduler` suggests switching to wait_readable / wait_writeable, but those methods aren't necessarily available without requiring `io/wait`.  In a small script, for example, this may not have been loaded by some other library, so the suggestion and auto-correction as given may be breaking.

--------

## RuboCop version

```
$ rubocop -V
1.22.3 (using Parser 3.0.2.0, rubocop-ast 1.13.0, running on ruby 3.0.2 x86_64-darwin20)
```

**Comment by koic** [comment]
Thank you for the feedback. I've confirmed it and open #10269.
