### ISSUE TITLE
`Style/SoleNestedConditional` incorrectly corrects when assignment in conditional

### ISSUE THREAD

**Issue by michaelglass** [rubocop/rubocop#10285]
When there's an assignment in a conditional (don't judge me! it's an old codebase!), `rubocop -a` creates an invalid autocorrection

```ruby
if a = 4 
  foo(a) if false
end
```

## Expected behavior

either the autocorrector is marked unsafe or the assignment is wrapped in parens, e.g.

```ruby
if (a = 4) && false
  foo(a)
end
```

## Actual behavior

```ruby
if a = 4 && false
  foo(a)
end
```
this autocorrection incorrectly changes the value of `a`  from its original `4` to `false`

## Steps to reproduce the problem

`rubocop -a` over the example at the top of the file

## RuboCop version

```
1.23.0 (using Parser 3.0.3.2, rubocop-ast 1.14.0, running on ruby 3.0.3 x86_64-darwin21)
```

**Comment by michaelglass** [comment]
also I failed to mention: @koic you are incredible!!

**Comment by koic** [comment]
@michaelglass Thank you for your feedback. I will work on this!
