### ISSUE TITLE
Add `IgnoredValues` or `ExcludedValues` to `Style/NumericLiterals` cop

### ISSUE THREAD

**Issue by thestelz** [rubocop/rubocop#10303]
## Is your feature request related to a problem? Please describe.

This isn't related to a problem with RuboCop, but something that would be nice.

There are configuration files that we use that have port numbers (like `8080`). This will throw an error in rubocop due to our `MinDigits: 4` config. 

## Describe the solution you'd like

To have an `IgnoredValues` or `ExcludedValues` setting/config added to [`Style/NumericLiterals`](https://docs.rubocop.org/rubocop/1.23/cops_style.html#stylenumericliterals) that defaults to `[]`. This will allow me to set specific numbers to be ignored without having to do the `# rubocop:disable/enable Style/NumericLiterals` for each time this happens.

## Describe alternatives you've considered

Currently I just put `# rubocop:disable Style/NumericLiterals` and `# rubocop:enable Style/NumericLiterals` between each time the issue comes up.

## Additional context

Our port numbers include 3-4 digits. The 3 digit numbers pass, but the 4 digit numbers fail. Instead of polluting the file with a bunch of RuboCop `disable` and `enable` flags, it would be nice to have a global config option.

Examples: `8080`, `3000`, `3030`, etc.

I know that changing the `MinDigits` or continue to use the comments fix the issue, but we can't change the `MinDigits` due to other files that we need it to be triggered on and the comments are just extra work.

I'm sure this won't be something you guys would implement due to it being too specific, but I figured I'd give it a shot anyway.

Thanks!

**Comment by koic** [comment]
I think it makes sense and I opened #10304. However, any default values will not set because false negatives occur when `3000`, `8080` (,and other values) are used other than the port number.

**Comment by thestelz** [comment]
@koic This is awesome! Thank you!
