### ISSUE TITLE
New cop to suggest `delete_suffix`/`delete_prefix`/`delete` for Strings

### ISSUE THREAD

**Issue by pirj** [rubocop/rubocop#10347]
```diff
- path.sub(/Controller$/, '').underscore
+ path.delete_suffix('Controller').underscore
```

```diff
- path.sub(/$Controller/, '').underscore
+ path.delete_prefix('Controller').underscore
```

```diff
- path.gsub(/abc/, '')
+ path.delete('abc')
```

## Describe alternatives you've considered

:shrug:

**Comment by koic** [comment]
This issue is implemented by `Performance/DeleteSuffix` cop. And `SafeMultiline: true` by default for safety,.
https://docs.rubocop.org/rubocop-performance/cops_performance.html#performancedeletesuffix
