### ISSUE TITLE
Style/BlockDelimiters missing a 1 line do/end block

### ISSUE THREAD

**Issue by tas50** [rubocop/rubocop#10360]
## Expected behavior

One line do/end block that is an argument for a send should be detected.

## Actual behavior

Not detected.

```
rubocop --force-default-config --only Style/BlockDelimiters ~/Desktop/test.rb --debug
Default configuration from /opt/homebrew/lib/ruby/gems/3.0.0/gems/rubocop-1.24.1/config/default.yml
Inspecting 1 file
Scanning /Users/tsmith/Desktop/test.rb
.

1 file inspected, no offenses detected
Finished in 0.0791750000207685 seconds
```

## Steps to reproduce the problem

Test Chef resource with a not_if that takes a 1 line block:

```ruby
ruby_block 'reload_ohai' do
  block do
    o = Ohai::System.new
    o.all_plugins
    node.automatic_attrs.merge! o.data
  end
  only_if do
    node['languages']['bash']['shellshock_vulnerable']
  end
end
```

My assumption after reading the docs for this cop is that it would autocorrect it to:

```ruby
ruby_block 'reload_ohai' do
  block do
    o = Ohai::System.new
    o.all_plugins
    node.automatic_attrs.merge! o.data
  end
  only_if { node['languages']['bash']['shellshock_vulnerable'] }
end
```

## RuboCop version

```
1.24.1 (using Parser 3.1.0.0, rubocop-ast 1.15.1, running on ruby 3.0.3 arm64-darwin21)
  - rubocop-performance 1.13.1
```

As always a super huge thank you to everyone involved on the project. RuboCop is amazing and the well thought out design makes it possible for me to extend the Ruby checking out to Chef cookbooks to cleanup a pile of old DSL.

**Comment by Darhazer** [comment]
`Style/BlockDelimiters` doesn't check whether the block would fit one line - it checks whether you are using do/end when inlining, or braces when there are multiple lines.

What you want to achieve is supported by `Layout/RedundantLineBreak` when `InspectBlocks` is set to true. Note that this cop is disabled by default.
