### ISSUE TITLE
Use rubocop to find untranslated strings

### ISSUE THREAD

**Issue by mathieujobin** [rubocop/rubocop#10369]
I'm not sure if this feature might already exists somewhere,.. my google-foo can't find anything useful.

For a project that uses translations, we either do `I18n.t('foo')`, or just `_('foo')` sometimes
Could a cop be made to return an offense anytime an English string `"I am a father"` is found within the source code?

## Describe the solution you'd like

Rubocop to report places where I left hardcoded text strings, which won't be translated

## Describe alternatives you've considered

Going through the code manually

## Additional context

We are going to implement multi-language in a large software which was never prepared for it.

Thanks

**Comment by koic** [comment]
Will rubocop-i18n help with the issue?
https://github.com/puppetlabs/rubocop-i18n

**Comment by mathieujobin** [comment]
Exactly what I was looking for, thank you

**Comment by koic** [comment]
You are welcome!
