### ISSUE TITLE
The `Layout/TrailingBlankLines` cop has been renamed to `Layout/TrailingEmptyLines`

### ISSUE THREAD

**Issue by sbk-kore** [rubocop/rubocop#10380]
Hello, I'm trying to run **rubocop** with ruby 2.6.3 and rails 5.2.3 it throws below errors,

`
Error: The `Layout/TrailingBlankLines` cop has been renamed to `Layout/TrailingEmptyLines`.
(obsolete configuration found in vendor/ruby/2.6.0/gems/jwt-2.2.3/.rubocop_todo.yml, please update it)
`Performance/*` has been extracted to the `rubocop-performance` gem.
(obsolete configuration found in vendor/ruby/2.6.0/gems/jwt-2.2.3/.rubocop_todo.yml, please update it)
`

**Comment by koic** [comment]
The latest RuboCop is excluded by default in `vendor/**/*` path.
https://github.com/rubocop/rubocop/blob/v1.25.0/config/default.yml#L66

It may have been overwritten with `Exclude` in .rubocop.yml. Please add `vendor/**/*` path to `Exclude`.
