### ISSUE TITLE
Lint/ShadowedArgument doesn't take into account super

### ISSUE THREAD

**Issue by crericha** [rubocop/rubocop#10390]
The following example produces `Lint/ShadowedArgument: Argument value was shadowed by a local variable before it was used.`; however, value is used by super and should not cause a lint error.

def foo( value )
  value = super
  ....
end

## RuboCop version
1.24.0

**Comment by koic** [comment]
This case should configure `IgnoreImplicitReferences: true`. The default value is false.
Please see the doc for more details. Thank you.
https://docs.rubocop.org/rubocop/cops_lint.html#lintshadowedargument
