### ISSUE TITLE
Generate `.rubocop_todo.yml` without any exclude limit

### ISSUE THREAD

**Issue by andyw8** [rubocop/rubocop#10409]
(Apologies if this has been discussed previously, it's hard to search for with such a large issue volume.)

## Is your feature request related to a problem? Please describe.

When setting up RuboCop on a project with a lot of existing offences, running `--auto-gen-config` results in many cops being entirely disabled (because there are more than the default limit of 15 occurrences).

To avoid that, I typically pass `--exclude-limit` with an arbitrary high limit such as `999999`.

## Describe the solution you'd like

I'd like to have a cleaner way to specify that no limit should supply, e.g:
- `--exclude-limit=0` (treat `0` as a special indicator)
- `--exclude-limit=-1` (treat any negative number as a special indicator)
- `--no-exclude-limit`

## Describe alternatives you've considered

n/a

## Additional context

n/a

**Comment by jonas054** [comment]
I would rule out `--exclude-limit=0` beacuse it breaks compatibility. It can currently be used with the opposite purpose; to generate a todo file with no `Exclude` parameters.

Of the remaining two I like `--no-exclude-limit` the best, as I think using `-1` is not entirely logical.

**Comment by andyw8** [comment]
Thanks for implementing this @r7kamura!
