### ISSUE TITLE
`~/.rubocop.yml` isn't loaded in windows

### ISSUE THREAD

**Issue by sevenc-nanashi** [rubocop/rubocop#10416]
## Expected behavior

Rubocop loads `~/.rubocop.yml` ( = `C:\\users\\UserName\\.rubocop.yml`) in Windows, and should exclude `__gi_*.rb`.
![image](https://user-images.githubusercontent.com/59691627/153839886-bce73315-11eb-44d3-9781-6c5c2a82ed8a.png)

## Actual behavior

It doesn't, loads `__gi_*.rb`.
![image](https://user-images.githubusercontent.com/59691627/153839553-92733357-a8b9-48a5-9201-a995552c3715.png)

## Steps to reproduce the problem

Put this in `%USERPROFILE%/.rubocop.yml` in windows.
```yml
AllCops:
  Exclude:
    - "__gi_*.rb"
    - "__gi_*/**/*.rb"
```

## RuboCop version

```
1.25.1 (using Parser 3.1.0.0, rubocop-ast 1.15.2, running on ruby 3.0.3 i386-mingw32)
```

**Comment by jonas054** [comment]
Could you run with the `-d` flag to get a log of which configuration files are read?

**Comment by sevenc-nanashi** [comment]
```
discorb on  feature/test [$] via  via  v3.0.3 took 10s
❯ rubocop -d
For E:/discorb-projects/discorb: configuration from E:/discorb-projects/discorb/.rubocop.yml
Default configuration from C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.25.1/config/default.yml
Inspecting 95 files
Scanning E:/discorb-projects/discorb/Gemfile
Loading cache from C:/Users/MyUserName/.cache/rubocop_cache/3e7be2158b0cf1ee6e720ca9f6b044cf6f57691d/6d7a3b621ca1730e04accd938619e4bdab66cfb1/2267ef7b5c05f3590f29b9ea4a57157b811de903
....
```

**Comment by jonas054** [comment]
Thanks. It does seem like it's not reading the configuration file from the home directory. Just like you said. 🙂

**Comment by jonas054** [comment]
Oh! I just realized what's going on here. The home directory `.rubocop.yml` is not read if a configuration file is found in the current directory or any ancestor of the current directory. This is expected behavior.

**Comment by sevenc-nanashi** [comment]
ok, so how can I make settings like global gitignore? (It would be feature request)

**Comment by jonas054** [comment]
That's right. There's no support for a global configuration file that would be used even for projects that have their own `.rubocop.yml`. I don't think we've discussed this feature before, so please open a new issue with that feature request, and then link it from here.
