### ISSUE TITLE
Global configuration  file

### ISSUE THREAD

**Issue by sevenc-nanashi** [rubocop/rubocop#10434]
## Is your feature request related to a problem? Please describe.

My git is ignoring `__gi_*` for testing or something that shouldn't be on git. They don't have to be clean, but setting ignore in project configuration is not good because this is not needed for other contributors.

## Describe the solution you'd like

Adding global settings, like global gitignore.

## Describe alternatives you've considered

(None)

## Additional context

This request is from #10416

**Comment by jonas054** [comment]
Would the example from https://docs.rubocop.org/rubocop/1.25/configuration.html#pre-processing solve your problem? It uses ERB pre-processing to exclude all files that are ignored by git.

**Comment by sevenc-nanashi** [comment]
Thanks, but it makes syntax error on yaml, and this is not meaningless for other contributors("Why is this configuration file ignoring gitignore things even it's not on github?"), so I want to keep it in only me

**Comment by jonas054** [comment]
I think it's possible to solve your special problem without adding more functionality to RuboCop.

The search for configuration files starts in the directory where the inspected file is and goes upwards in the directory tree until a `.rubocop.yml` file is found. Configuration is taken from the closest configuration file found. With one exception. `Exclude` parameters are taken from the highest level configuration file.

This means that you can add a `.rubocop.yml` in the parent directory of your project. So if the project is in `/discorb-projects/discorb`, you can add the file `/discorb-projects/.rubocop.yml` with the following contents:

```yaml
AllCops:
  Exclude:
    - discorb/**/__gi_*
```

**Comment by jonas054** [comment]
Relabeled as question since I don't think any new features are needed in this case.
