### ISSUE TITLE
Spurious useless assignment warning on reduce

### ISSUE THREAD

**Issue by michaelmior** [rubocop/rubocop#1044]
```
$ rubocop -V
0.21.0 (using Parser 2.1.9, running on ruby 2.0.0 x86_64-linux-gnu)
```

The following code example produces the warning below. Of course in this case the assignment isn't useless as sum is carried on to the next  call of the block.

``` ruby
x = [1, 4, 9].reduce(0) do |sum, n|
  sum += Math.sqrt n
end
puts x
```

```
Inspecting 1 file
W

Offenses:

/tmp/x.rb:2:3: W: Useless assignment to variable - sum. Use just operator +.
  sum += Math.sqrt n
  ^^^

1 file inspected, 1 offense detected
```

**Comment by SherSpock** [comment]
I also thought this was a bug, and I wasted a chunk of time troubleshooting it. The error message was very unclear to me.

I believe this might be very easily fixed by saying something like 'use just operator + instead of +='.
