### ISSUE TITLE
unrecognized cop or department Style/NestedFileDirname 

### ISSUE THREAD

**Issue by rahulthakur1390** [rubocop/rubocop#10448]
![image](https://user-images.githubusercontent.com/19193671/157598005-5058887d-3708-4a88-8f63-f1ca2f660331.png)

--------

## Expected behavior
Should run rubocop

## Actual behavior
Getting above error

# Common configuration.
---
.github/linters/.rubocop.yml

inherit_from:
  - https://raw.githubusercontent.com/rubocop/rubocop/master/config/default.yml
  - .rubocop-custom.yml
  ------------------------------------
  rubocop (1.25.0) (gem version)

**Comment by rahulthakur1390** [comment]
**.github/linters/.rubocop-custom.yml**
Lint/UselessAssignment:
  Description: 'Checks for useless assignment to a local variable.'
  StyleGuide: '#underscore-unused-vars'
  Enabled: true
  VersionAdded: '0.11'
  Severity: error

**Comment by koic** [comment]
> rubocop (1.25.0) (gem version)

`Style/NestedFileDirname` cop has been introduced by RuboCop 1.26. Can you upgrade RuboCop to 1.26.0?

- https://docs.rubocop.org/rubocop/1.26/cops_style.html#stylenestedfiledirname
- https://github.com/rubocop/rubocop/releases/tag/v1.26.0
