### ISSUE TITLE
Return only the number of auto-correctable and safe offenses

### ISSUE THREAD

**Issue by jonathanloos** [rubocop/rubocop#10481]
## Is your feature request related to a problem? Please describe.

We introduced Rubocop to a fairly large codebase and wanted to enforce only safe, auto-correctable cops while we worked on the non-auto-correctable offences. After reading through everything I could find I couldn't find out how to answer "How many auto-correctable offences do I have in my codebase" easily through the Rubocop CLI. It seems like the return count ALWAYS reports on every offence (I.e. only passes if both auto-correctable and non-auto-correctable are clear).

## Describe the solution you'd like

I would like to be able to specify that Rubocop only return the number of auto-correctable and safe offenses that are in the codebase.

## Describe alternatives you've considered

Our current workaround just lists all of the non-auto-correctable cops we have yet to correct in our rubocop.yml and fully omits them from the scan.

## Additional context

N/A

If this is achievable I would like to know where to find the answer.. I've combed through a lot of documentation to no avail.

**Comment by dobham** [comment]
Yea anything to help out with this would help with my project too! Would appreciate any eyes taking a look at this,

**Comment by suvasan19** [comment]
This would be super helpful for my app!
