### ISSUE TITLE
Rubocop version 1.26.1 and RedundantInitialize

### ISSUE THREAD

**Issue by altjx** [rubocop/rubocop#10486]
I noticed that `RedundantInitialize` was recently added, but for some reason I'm having issues in my pipeline:

```
Error: unrecognized cop or department Style/RedundantInitialize found in .github/linters/.rubocop-https---raw-githubusercontent-com-rubocop-rubocop-master-config-default-yml
Did you mean `Style/RedundantCapitalW`?
Error: Process completed with exit code 123.
```

I'm using Rubocop version 1.26.1 and for some reason this cop isn't available:

```
root@7f1a880eaaf8:/home/ubuntu/myapp# rubocop --version
1.26.1
root@7f1a880eaaf8:/home/ubuntu/myapp# rubocop --show-cops | grep -i "RedundantInitialize"
root@7f1a880eaaf8:/home/ubuntu/myapp#
```

Noticed this was added pretty recently, so not quite sure what I may be doing incorrectly.

**Comment by dvandersluis** [comment]
Hi @altjx it hasn’t been released yet, you have to wait for the next release or use the github version in your gemfile if you can’t wait. The next release will probably be out soon.

**Comment by altjx** [comment]
> Hi @altjx it hasn’t been released yet, you have to wait for the next release or use the github version in your gemfile if you can’t wait. The next release will probably be out soon. 

Gotcha. Thanks a lot!
