### ISSUE TITLE
Cop idea:  Set the default value of `ENV.fetch` by autocorrect

### ISSUE THREAD

**Issue by johnny-miyake** [rubocop/rubocop#10578]
## Is your feature request related to a problem? Please describe.

From: https://github.com/rubocop/rubocop/pull/10502#issuecomment-1106950555

With `Style/FetchEnvVar`, code like
```ruby
value = ENV['EXAMPLE_KEY'] || 'default_value'
```

gets autocorrected to
```ruby
value = ENV.fetch('EXAMPLE_KEY', nil) || 'default_value'
```

Autocorrecting like below helps people reduce their manual changings like above.
```ruby
value = ENV.fetch('EXAMPLE_KEY', 'default_value')

# This version would be better on performance if the default value is calculated by an expensive computation.
value = ENV.fetch('EXAMPLE_KEY'){'default_value'}
```

## Describe the solution you'd like

- When `ENV[]` is the left-hand of `||`, the autocorrect can move the right-hand of `||` to the default value of `ENV.fetch`.
- In some cases, the right hand of `||` can't be the default value (e.g., `next`), so we need to carefully handle them.

**Comment by bbatsov** [comment]
Seems like a good idea to me. 

As for the auto-correct - I guess if the default is some literal or a local value we can use the first form and if it's a method call we can go for the block style, although I don't have a strong preference. The performance gains would be notable only if the computation of the default value is expensive.

**Comment by ShockwaveNN** [comment]
Please note that if you got code like this:

```ruby
return ENV['foo'] if ENV.key?('foo')

File.read('file_if_foo_not_exists')
```
Code like this will work fine if `ENV['foo']` exists and File `file_if_foo_not_exists` not exists

But if you by similarity with proposal from this issue change it to

```ruby
ENV.fetch('foo', File.read('file_if_foo_not_exists'))
```

If will fail in any case if `file_if_foo_not_exists` do not exists (even if `ENV['foo']` is initialized)

**Comment by johnny-miyake** [comment]
Great point. That would be one of the cases we should use the block style.
```ruby
ENV.fetch('foo') { File.read('file_if_foo_not_exists') }
```
In my opinion, in most cases always using the block style is safer and reduces the rules. Any thoughts?

**Comment by johnny-miyake** [comment]
I created a PR for this.
https://github.com/rubocop/rubocop/pull/10585
I made the default value style configurable so that users can choose their preferred way.
Any help in finding missing test cases or edge cases is very appreciated.
