### ISSUE TITLE
Error while Layout/BlockAlignment cop was inspecting an RSpec source file

### ISSUE THREAD

**Issue by xeger** [rubocop/rubocop#10599]
## Expected behavior

Rubocop should succeed in my project when I run it with Ruby 3.1.1 without crashing (just as it succeeds with 3.0 and 2.7.x).

## Actual behavior

```
Inspecting 20 files
..............An error occurred while Layout/BlockAlignment cop was inspecting /tmp/rubocop_issue/spec/breaks_rubocop_spec.rb:3:0.
undefined method `op_asgn_type?' for [s(:block,
  s(:send, nil, :describe,
[snip]

[snip]rubocop-0.93.1/lib/rubocop/cop/layout/block_alignment.rb:96:in `start_for_block_node'
[snip]/rubocop-0.93.1/lib/rubocop/cop/layout/block_alignment.rb:81:in `on_block'
```

## Steps to reproduce the problem

Write `spec/breaks_rubocop_spec.rb` (see attached file) and then invoke Rubocop 0.93.1 with Ruby 3.1.1.

```
$ bundle exec rubocop -c .rubocop.yml
```

## RuboCop version

```
$ bundle exec rubocop -V
0.93.1 (using Parser 3.1.2.0, rubocop-ast 1.17.0, running on ruby 3.1.1 arm64-darwin21)
```
[breaks_rubocop_spec.rb](https://github.com/rubocop/rubocop/files/8608209/breaks_rubocop_spec.rb.txt)

**Comment by cesc1989** [comment]
2024, was doing an upgrade to ruby 3.1 and needed to upgrade rubocop. If you're googling, bumping to 1.28.2 removes this error as mentioned in the previous comment.
