### ISSUE TITLE
Rubocop SVG logo file

### ISSUE THREAD

**Issue by zrfisaac** [rubocop/rubocop#10601]
## Is your feature request related to a problem? Please describe.
I need a pull request with Rubocop SVG logo file for the [simple-icons](https://github.com/simple-icons/simple-icons) that allows you create beautiful shields likes this: 
[![](https://img.shields.io/badge/-VS_Code-0078d7?style=for-the-badge&logo=visualstudiocode&logoColor=white)](https://en.wikipedia.org/wiki/Microsoft_Visual_Studio) [![](https://img.shields.io/badge/-Visual_Studio-484095?style=for-the-badge&logo=visualstudio&logoColor=white)](https://en.wikipedia.org/wiki/Microsoft_Visual_Studio) [![](https://img.shields.io/badge/-Delphi-BF2126?style=for-the-badge&logo=delphi&logoColor=white)](https://en.wikipedia.org/wiki/Delphi_(software)) [![](https://img.shields.io/badge/-Lazarus-375390?style=for-the-badge&logo=lazarus&logoColor=white)](https://en.wikipedia.org/wiki/Lazarus_(software)) [![](https://img.shields.io/badge/-Godot-263256?style=for-the-badge&logo=godotengine&logoColor=white)](https://en.wikipedia.org/wiki/Godot_(game_engine)) [![](https://img.shields.io/badge/-SQL_Server-555555?style=for-the-badge&logo=microsoftsqlserver&logoColor=white)](https://en.wikipedia.org/wiki/Microsoft_SQL_Server) [![](https://img.shields.io/badge/-MySQL-00758F?style=for-the-badge&logo=mysql&logoColor=white)](https://en.wikipedia.org/wiki/MySQL) [![](https://img.shields.io/badge/-PostgreSQL-395877?style=for-the-badge&logo=postgresql&logoColor=white)](https://en.wikipedia.org/wiki/PostgreSQL) [![](https://img.shields.io/badge/-SQLite-3BA3F3?style=for-the-badge&logo=sqlite&logoColor=white)](https://en.wikipedia.org/wiki/SQLite) [![](https://img.shields.io/badge/-CSharp-167266?style=for-the-badge&logo=csharp&logoColor=white)](https://en.wikipedia.org/wiki/C_Sharp_(programming_language)) [![](https://img.shields.io/badge/-Bash-333333?style=for-the-badge&logo=gnubash&logoColor=white)](https://en.wikipedia.org/wiki/Bash_(Unix_shell)) [![](https://img.shields.io/badge/-.Net-484095?style=for-the-badge&logo=dotnet&logoColor=white)](https://en.wikipedia.org/wiki/.NET) [![](https://img.shields.io/badge/-HTML5-E34C26?style=for-the-badge&logo=html5&logoColor=white)](https://en.wikipedia.org/wiki/HTML5) [![](https://img.shields.io/badge/-CSS3-0F5298?style=for-the-badge&logo=css3&logoColor=white)](https://en.wikipedia.org/wiki/CSS) [![](https://img.shields.io/badge/-JavaScript-FBA91A?style=for-the-badge&logo=javascript&logoColor=white)](https://en.wikipedia.org/wiki/JavaScript) [![](https://img.shields.io/badge/-Android-77C159?style=for-the-badge&logo=android&logoColor=white)](https://en.wikipedia.org/wiki/Android_(operating_system)) [![](https://img.shields.io/badge/-Linux-000000?style=for-the-badge&logo=linux&logoColor=white)](https://en.wikipedia.org/wiki/Linux) [![](https://img.shields.io/badge/-Arch_Linux-1793D1?style=for-the-badge&logo=archlinux&logoColor=white)](https://en.wikipedia.org/wiki/Arch_Linux) [![](https://img.shields.io/badge/-Windows-0078D7?style=for-the-badge&logo=windows&logoColor=white)](https://en.wikipedia.org/wiki/Microsoft_Windows)

**Comment by pboling** [comment]
In this [directory](https://github.com/rubocop-semver/rubocop-ruby2_0/tree/main/docs/images/logo) you will find a [rubocop-dark.svg](https://github.com/rubocop-semver/rubocop-ruby2_0/blob/main/docs/images/logo/rubocop-dark.svg) and [rubocop-light.svg](https://github.com/rubocop-semver/rubocop-ruby2_0/blob/main/docs/images/logo/rubocop-light.svg):
https://github.com/rubocop-semver/rubocop-ruby2_0/tree/main/docs/images/logo

The sources and licenses of each are documented in the accompanying README.txt in the same [directory](https://github.com/rubocop-semver/rubocop-ruby2_0/tree/main/docs/images/logo), and copied here for convenience:

The Rubocop Logo (Light) - rubocop-light.svg

Original PNG Source: rubocop/rubocop <https://github.com/rubocop/rubocop/blob/master/logo/rubo-logo-symbol.png?raw=true>
Original PNG Author: Copyright (c) 2014 Bozhidar Batsov
Original PNG License: MIT <https://github.com/rubocop/rubocop/blob/master/LICENSE.txt>
SVG Source: gilbarbara/logos <https://github.com/gilbarbara/logos>
SVG Author: Gil Barbara <https://github.com/gilbarbara>
SVG License: CC0 <https://raw.githubusercontent.com/gilbarbara/logos/master/LICENSE.txt>

---

The Rubocop Logo (Dark) - rubocop-dark.svg

Original PNG Source: rubocop/rubocop <https://github.com/rubocop/rubocop/blob/master/logo/rubo-logo-symbol.png?raw=true>
Original PNG Author: Copyright (c) 2014 Bozhidar Batsov
Original PNG License: MIT <https://github.com/rubocop/rubocop/blob/master/LICENSE.txt>
SVG Source: vscode-icons/vscode-icons <https://github.com/vscode-icons/vscode-icons>
SVG Author: Roberto Huertas <https://github.com/vscode-icons/vscode-icons>
SVG License: MIT <https://github.com/vscode-icons/vscode-icons/blob/master/LICENSE>

**Comment by zrfisaac** [comment]
Thanks! this solve my problem. I will do a pull request soon in [simple-icons](https://github.com/simple-icons/simple-icons). 🙌

**Comment by pboling** [comment]
CC @bbatsov :)
