### ISSUE TITLE
make --parallel and --auto-correct work together

### ISSUE THREAD

**Issue by grosser** [rubocop/rubocop#10613]
I can do it with xargs, so we can also do it internally 🤷 
... maybe it needs to say "rules xyz are not enforced because they would rename files" or whatever the reason was to disable this, but for 99% case they should just work! :)

**Comment by jonas054** [comment]
@marcandre asked about the same thing [here](https://github.com/rubocop/rubocop/issues/7544#issuecomment-813089351) but it was never answered.

I think the reason why we've disabled parallel execution for autocorrection is that it's not trivial to get it to work consistently. Just removing the lines https://github.com/rubocop/rubocop/blob/8fa156c7c5d35c1cc02e0530cdb4aecdf7ee326e/lib/rubocop/options.rb#L426-L428 mostly does what we want, but the output from `rubocop -a` is always a long row of green dots. I.e., we don't see any indication of offenses that were found and corrected. So the normal algorithm for parallel execution, which is to warm up the cache in parallel and then do the inspection in a single thread, doesn't fulfill the needs of autocorrection.

**Comment by grosser** [comment]
amazing! :D

**Comment by jonas054** [comment]
@grosser Thanks! I hope you read in the PR that it's a somewhat limited improvement that only guarantees that the cache is warm before starting to correct files. Sometimes that translates into a big gain in speed, sometimes it's a small one. :slightly_smiling_face:
