### ISSUE TITLE
Decouple minimum TargetRubyVersion from supported runtime platform

### ISSUE THREAD

**Issue by mvz** [rubocop/rubocop#10625]
## Is your feature request related to a problem? Please describe.

For many of the gems I maintain, I've set up a combination of the following:

- A dev dependency on RuboCop with rather liberal version specification (e.g., "~> 1.27"
- A GitHub Action to run (among others) a RuboCop check, set up to run on pull requests, of course, but also once a month. This Action runs on Ruby 2.7 at the moment.

This combination is intended to catch any new offenses without having to update the gemspec.

However, this plan is no longer working since the Action for some of my projects now fails because latest RubyCop dropped support for Ruby 2.5 as a TargetRubyVersion.

## Describe the solution you'd like

Allow TargetRubyVersion 2.5, even when RuboCop itself will only run on Ruby 2.6 and up. This should be possible since Parser supports 2.5 just fine when running on a later Ruby version.

## Describe alternatives you've considered

I could use a tighter version specification for RuboCop. However this means churn in the repositiories, and/or potentially not keeping my dependencies up-to-date with the latest versions. Both of these I'd like to avoid, to support my scheme to make maintaining my gems as light-weight as possible.

## Additional context

There was a very short but heated discussion about this in the semver repository starting here: https://github.com/semver/semver/issues/716#issuecomment-1115128186. I'd like to avoid any discussion of what semver really means and focus on this specific feature.

**Comment by bbatsov** [comment]
Hmm, I was under the impression we removed only runtime support for Ruby 2.5, but perhaps I didn't read the PR carefully enough. I'll defer to @koic here, but in principle I agree that we should maintain support for `TargetRubyVersion` much longer than runtime support. 

I also feel that removing support for a `TargetRubyVersion` is technically speaking a breaking change, which should not happen in a minor release.

**Comment by koic** [comment]
I'm sorry about it. I've opened #10626 to resolve this issue.
