### ISSUE TITLE
Gemspec/DateAssignment removed in a minor version

### ISSUE THREAD

**Issue by jcoyne** [rubocop/rubocop#10753]
After upgrading to 1.31.0 I get the following error:
```
Error: The `Gemspec/DateAssignment` cop has been removed. Please use `Gemspec/DeprecatedAttributeAssignment` instead.
(obsolete configuration found in .rubocop.yml, please update it)
```

I did not get this error in 1.30, so the change of acceptable configuration seems like it might break SemVer.  Should this change have been a deprecation warning or gone out in a major version instead?

Note: I added this directive to my config back when I upgraded to 1.10 as it was suggested when I ran rubocop:

```yaml
Gemspec/DateAssignment: # (new in 1.10)
  Enabled: true
```

**Comment by ydah** [comment]
`Gemspec/DateAssignment` will be merged into `Gemspec/DeprecatedAttributeAssignment` in the future.
However, the integration is pending because RuboCop 1.x does not allow breaking changes.

PRs that have implemented this change include
- https://github.com/rubocop/rubocop/pull/10634

**Comment by koic** [comment]
Unfortunately, `Gemspec/DateAssignment` is shipped removed. So this is a breking change.
https://github.com/rubocop/rubocop/pull/10634/commits/0bcd7600a1890a34670eb28bfffdfa3190b57b59

I'm not sure if it's better to revert the removal of `Gemspec/DateAssignment` from now on (This breaking change has already happened), but it seems better to refrain from removing it until 2.0 in the future.

**Comment by jcoyne** [comment]
I think it would be great if it would just accept `Gemspec/DateAssignment` and do nothing other than issue a deprecation that this has been removed and will be an error in the next major version.

**Comment by bbatsov** [comment]
@koic My bad, I was under the impression this wouldn't break the user setup. Yeah, let's make the old cop do nothing. 

P.S. Seems to me such removals should result in warnings, not errors in general.

**Comment by koic** [comment]
I'm closing this issue because the removal of the cop is a past issue. And it would be ideal if future non-breaking rename cop could be done [without hacks](https://github.com/rubocop/rubocop-rspec/pull/1519#discussion_r1064220232).
