### ISSUE TITLE
Provide option to require leading space for Layout/LineContinuationLeadingSpace

### ISSUE THREAD

**Issue by mvz** [rubocop/rubocop#10752]
## Is your feature request related to a problem? Please describe.

When using line continuations, I put space at the beginning of the next line on purpose, to make the spaces more visible. This conflicts with the new Layout/LineContinuationLeadingSpace cop.

## Describe the solution you'd like

I'd like to configure Layout/LineContinuationLeadingSpace to require spaces at the beginning of the line instead of at the end of the previous one.

## Describe alternatives you've considered

I can disable Layout/LineContinuationLeadingSpace. I can also let Layout/LineContinuationLeadingSpace autocorrect these offenses, but it will make the presence of spaces less salient. It may also push some lines over the maximum line length.

## Additional context

N/A

**Comment by jonas054** [comment]
This seems to be in the works. See #10762.
