### ISSUE TITLE
Odd inconsistency with `--cache-root`

### ISSUE THREAD

**Issue by dgollahon** [rubocop/rubocop#10766]
## Expected behavior

Configuring `--cache-root` would behave exactly like setting `RUBOCOP_CACHE_ROOT` or `AllCops: CacheRootDirectory`, modulo precedence.

## Actual behavior

The `--cache-root` flag specifies the exact cache folder. The other two options end up creating a nested `rubocop_cache` directory. I think I see from the code why this is happening but it is perplexing as an end user (and messed up my CI cache at first).

## Steps to reproduce the problem

Specify a directory to `--cache-root` and separately either of the other options and observe that the directory structure it creates is different.

## RuboCop version

```
1.31.0 (using Parser 3.1.2.0, rubocop-ast 1.18.0, running on ruby 2.7.6 x86_64-linux)
  - rubocop-performance 1.14.2
  - rubocop-rspec 2.11.1
```

I'm not sure if this should be changed to match or if the difference should just be documented but it is very surprising as-is. I actually prefer the `--cache-root` behavior (so i don't have an extra nesting of directories) but the main issue here is that it is confusing.

**Comment by jonas054** [comment]
I think this is a bug. A `rubocop_cache` directory level should be added, also for `--cache_root`.
