### ISSUE TITLE
Performance issues with 1.31.0 (Layout/FirstHashElementIndentation and Layout/FirstArrayElementIndentation)

### ISSUE THREAD

**Issue by seandilda** [rubocop/rubocop#10764]
After updating to 1.31.0, my editor started complaining about rubocop timeouts.   Some testing has narrowed the issue to the recent changes in `Layout/FirstHashElementIndentation` and `Layout/FirstArrayElementIndentation`.

Here are some timings from running `time rubocop --cache false testfile.rb` on a file I'm currently working on.

| rubocop version | `Layout/FirstHashElementIndentation` enabled | `Layout/FirstArrayElementIndentation` enabled | time |
| --- | --- | --- | --- |
| 1.30.1 | `true` | `true` | 3.5s |
| 1.31.0 | `true` | `true`| 9.3s |
| 1.31.0 | `true` | `false` | 5.3s |
| 1.31.0 | `false` | `true` | 7.8s |
| 1.31.0 | `false` | `false` | 3.4s |

--------

## Expected behavior
RuboCop 1.31.0 should run at the same speed as 1.30.1

## Actual behavior

Version 1.31.0 is several times slower when  `Layout/FirstHashElementIndentation`  and/or  `Layout/FirstArrayElementIndentation` is enabled

## Steps to reproduce the problem

Run `rubocop --cache false` on a file using a large number of hashes and arrays.

## RuboCop version

```
1.31.0 (using Parser 3.1.2.0, rubocop-ast 1.18.0, running on ruby 2.7.6 x86_64-linux)
  - rubocop-rails 2.15.1
```

**Comment by dvandersluis** [comment]
I'm curious if you get the same results now that 1.31.1 was released? Did #10750 help?

**Comment by seandilda** [comment]
Thanks for the heads up!   I just checked with 1.31.1 and I'm still seeing 9 second runs on that file. :(

**Comment by dvandersluis** [comment]
Are you able to share the file or an anonymized version of it?

**Comment by seandilda** [comment]
I've created a test file to reproduce this issue at https://gist.github.com/seandilda/a5872778c19fd82624809d856f0b7435

With 1.31.1, and both cops enabled, it takes 4.5s
With 1.31.1 and both cops disabled, it takes 2.1s
With 1.30.1 and both cops enabled, it takes 2.1s

**Comment by j-miyake** [comment]
I found that the cop takes a lot of time when inspecting a large file.

With a small file (55bytes)
$ time exe/rubocop --cache false --only "Layout/FirstHashElementIndentation" small.rb
1.30s user 0.44s system 97% cpu 1.774 total

With a large file (2MB)
$ time exe/rubocop --cache false --only "Layout/FirstHashElementIndentation" large.rb  
3.13s user 0.45s system 99% cpu 3.605 total

With a extra large file (163MB)
$ time exe/rubocop --cache false --only "Layout/FirstHashElementIndentation" xlarge.rb
56.58s user 0.57s system 99% cpu 57.336 total

I guess a part of the logic for searching an offensive node is expensive. For a small file, that may not be a big deal, but for a large file.
https://github.com/rubocop/rubocop/blob/023e0ea404025072506307a56cf5c24b1dc64d24/lib/rubocop/cop/mixin/multiline_element_indentation.rb#L70-L76
