### ISSUE TITLE
`Lint/NonAtomicFileOperation` create broken code (`else` without `if`

### ISSUE THREAD

**Issue by ShockwaveNN** [rubocop/rubocop#10760]
## Steps to reproduce the problem

1. Create file `test.rb`:
```
# frozen_string_literal: true

folder = '/tmp/test'
if Dir.exist?(folder)
  p 'a'
else
  FileUtils.mkdir(folder)
end

```
2. run `rubocop -A test.rb`
3. In result we got code like this:

```
# frozen_string_literal: true

folder = '/tmp/test'

  p 'a'
else
  FileUtils.mkdir_p(folder)


```

This is incorrect ruby code, `else` is missing it's `if`
## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler.
If you see extension cop versions (e.g. `rubocop-performance`, `rubocop-rspec`, and others)
output by `rubocop -V`, include them as well. Here's an example:

```
$ [bundle exec] rubocop -V
1.31.0 (using Parser 3.1.2.0, rubocop-ast 1.18.0, running on ruby 3.1.2 x86_64-linux)
  - rubocop-rspec 2.11.1

```

**Comment by AlexWayfer** [comment]
My case:

```ruby
FileUtils.rm_r project_name if Dir.exist? project_name
```

Now causes offense.

"Fix" without `if` causes the error:

```
Failure/Error: FileUtils.rm_r project_name

Errno::ENOENT:
  No such file or directory @ apply2files - foo_bar
```

**Comment by AlexWayfer** [comment]
Should I notify case with `FileUtils.rm_r(@filename) if File.exist?(@filename)`?

**Comment by ShockwaveNN** [comment]
@AlexWayfer Try to add `require 'fileutils'` to your file, it solve Errno:ENOENT error for `FileUtils.rm_rf` for me

**Comment by AlexWayfer** [comment]
> @AlexWayfer Try to add `require 'fileutils'` to your file, it solve Errno:ENOENT error for `FileUtils.rm_rf` for me

Doesn't help.
