### ISSUE TITLE
`Style/FetchEnvVar` autocorrect not very readable in boolean-or chains

### ISSUE THREAD

**Issue by merrilymeredith** [rubocop/rubocop#10788]
The `Style/FetchEnvVar` cop is autocorrecting to code that doesn't seem like a style improvement when given code that accepts a few possible ENV variable names or has a chain of alternatives.  Note that since ENV values are strings, `||` does not risk discarding a `0` in the environment as it's a truthy `"0"` right now.

```diff
-      ENV["LOG_NAME"] || Core.app_name || File.basename($PROGRAM_NAME)
+      ENV.fetch("LOG_NAME") { Core.app_name } || File.basename($PROGRAM_NAME)
```

```diff
-      ENV["BUILD_METADATA"] || ENV["APPBASE_BUILD_METADATA"] || File.read("/BUILD_METADATA")
+      ENV.fetch("BUILD_METADATA") { ENV.fetch("APPBASE_BUILD_METADATA") { File.read("/BUILD_METADATA") } }
```

This satisfies the cop and might be a better autocorrect when there's more than a single alternative, but it's still a bit odd:

```ruby
ENV.fetch("FOO", nil) || ENV.fetch("BAR", nil) || baz
```

and short sets of options seem like too little to switch to an array-oriented way of doing this:

```ruby
ENV.values_at("BUILD_METADATA", "APPBASE_BUILD_METADATA").compact.first || File.read("/BUILD_METADATA")
```

I'd ask someone to prefer simplicity over cleverness if I saw the above.

One could definitely get out of hand with with a boolean chain but I'm sure they'd cross other cops in doing so, while the longest examples I'm dealing with here are 3 terms.  Four is the point where I'd personally switch to a different style or refactor.

I think this cop could be relaxed when it finds `ENV[...] || ...` on the LHS of another `|| ...`?

## RuboCop version

```
1.30.1 (using Parser 3.1.2.0, rubocop-ast 1.18.0, running on ruby 3.1.2 x86_64-linux)
  - rubocop-rspec 2.11.1
```

**Comment by jonas054** [comment]
@j-miyake Do you have any comments on this?

**Comment by j-miyake** [comment]
Indeed. The autocorrect of this cop may decrease readability like the case reported by this issue. Considering some improvements or comments (like #10652,  https://github.com/rubocop/rubocop/pull/10585#issuecomment-1113699094) made until today, `ENV[]` in LHS of `||` operator probably should be allowed because the `||` is put by the developer who knows the LHS may be `nil`. I would like to hear others' thoughts.

**Comment by j-miyake** [comment]
The code would be like [this](https://github.com/rubocop/rubocop/pull/10819) if we relax the cop.
