### ISSUE TITLE
Suggested cop: Detect repeated names in method chains

### ISSUE THREAD

**Issue by andyw8** [rubocop/rubocop#10793]
## Is your feature request related to a problem? Please describe.

Every so often I see some code where the same method name is called twice on a chain of objects e.g. `element.element`. In fact, here's an example from `rubocop-rails` itself:

https://github.com/rubocop/rubocop-rails/blob/cc383320e878f7e5da1eb57015d505a4a8a3cf61/lib/rubocop/cop/rails/deprecated_active_model_errors_methods.rb#L124

Although I haven't looked into the specifics of the above case, in general this often indicates a problem with bad naming or a flawed API.

## Describe the solution you'd like

Report an offence when this is detected.

## Describe alternatives you've considered

n/a

## Additional context

n/a

**Comment by koic** [comment]
A similar example is to use `node.parent.parent` when exploring a node. This can happen not only with AST, also with DOM operation API, so it would be difficult to make it a general rule with static analysis. Maybe there are other false positives.
