### ISSUE TITLE
AndOr sees `render and return` as a violation

### ISSUE THREAD

**Issue by itavero** [rubocop/rubocop#1083]
How can I configure RuboCop to no longer see the code below as a violation to the `AndOr` check?

``` ruby
render nothing: true, status: :bad_request and return
```

Currently it tells me to replace `and` with `&&`, which is not correct as far as I know.

**Comment by paulschreiber** [comment]
I naively switched some of these to `render "foo" && return` which _definitely_ doesn't work.

Sometime I can do this:
```ruby
if @something
  render "foo"
  return
end
```
…but sometimes you end up with an error about not using a guard statement.

I ended up with some code like this:
```ruby
def create
  ...
  render :create unless @person.save
  render 'thanks'
end
```
...which seems clunky and unnatural when compared to:
```ruby
def create
  ...
  render 'thanks' and return if @person.save
end
```

How would you write this?

**Comment by bbatsov** [comment]
Obviously the simple solution is to add parentheses when needed.

**Comment by paulschreiber** [comment]
Where would the parens go in this case?

**Comment by mikegee** [comment]
```ruby
def create
  ...
  render('thanks') && return if @person.save
end
```

Or

```ruby
def create
  ...
  (render 'thanks') && return if @person.save
end
```

**Comment by krishantaylor** [comment]
This conflicts with the current Rails guides, meaning this issue should probably be reopened.

> Make sure to use `and return` instead of `&& return` because `&& return` will not work due to the operator precedence in the Ruby Language.
http://guides.rubyonrails.org/layouts_and_rendering.html#avoiding-double-render-errors

**Comment by mikegee** [comment]
I'd rather see the guide changed to promote good practice rather than a common workaround.

The example there could be:
```ruby
def show
  @book = Book.find(params[:id])
  if @book.special?
    render action: "special_show"
    return
  end
  render action: "regular_show"
end
```
or
```ruby
def show
  @book = Book.find(params[:id])
  if @book.special?
    render action: "special_show"
  else
    render action: "regular_show"
  end
end
```

**Comment by wjdhamilton** [comment]
Part of the problem here is that the Rails community have decided that the `and` operator has different semantics than that which the `and` operator was originally intended for. Whereas `&&` is still viewed as the logical and, `and` has come to mean 'do something and then do something else'.

**Comment by uri** [comment]
I don't think it's fair to call `and return` a hack or a workaround. Sure `and`/`or` can cause developers grief when used in a conditional, but I think they have a place when used as flow control operators (as in the case of `and return`. I've always had the impression that `and return` was considered idiomatic Ruby.

**Comment by jonas054** [comment]
@uri It depends. If your intention is to always return and you're using `and` as a more visually pleasing alternative to `;`, depending on the left hand side to always return a truthy value, then I think it's an ugly hack. @mikegee said this earlier in the discussion.

**Comment by uri** [comment]
>If your intention is to always return and you're using and as a more visually pleasing alternative to ;

This is not the case. I agree, if your intention is to **always** return then yes, use `;`. Otherwise you have some kind of expectation from the left-hand side and you can use `and`/`or` to do something:

```ruby
pass_or_fail and "it passed"
pass_or_fail or "it failed"
pass_or_fail ; "unknown"
```

That's a trivial example which can easily be replaced with `if`/`unless` but I hope it illustrates that `;`  is not `and`.

It's true that the intention for `render` is to always return. But by using `;` you're not chaining the operations together. This is evident if you have a conditional:

```ruby
some_conditional = false
render 'new' ; return if some_conditional
# ...
render 'form' # double render
```
