### ISSUE TITLE
Rubocop uses outdated `parallel` gem version

### ISSUE THREAD

**Issue by nouseforaname** [rubocop/rubocop#10854]
The minor version of the parallel that rubocop is pinned to 1.12.x and that is quite old. 

Can this please be updated? 

We face an issue where we use parallel for our project and want to add a dependency (that itself) depends on rubocop. This effectively locks parallel for our project to 1.12 and that is already 5y old.

The parallel dependency hasn't been updated since it got introduced in: https://github.com/rubocop/rubocop/commit/1551c24c78a2b5a3b4bb143aba21ea97ef22fe70

Is there any specific reason that the version pinning is set to 1.12? Can this instead be pinned to the major instead of the minor version of parallel?

FWIW I did change it to 1.22.1 locally and ran the tests and haven't seen any issues with ruby 3.1.2.

**Comment by koic** [comment]
`~> 1.10` means greater than or equal to version 1.10 and less than version 2.0, not pin. 

```ruby
s.add_runtime_dependency('parallel', '~> 1.10')
```

https://github.com/rubocop/rubocop/blob/v1.32.0/rubocop.gemspec#L35

So, `bundle update` can update to Parallel 1.22.1.

Runtime dependency version bumps have user impact. If there is no intention such as updating the dependent API, it should not be changed.
