### ISSUE TITLE
Ambiguous output from `Lint/ShadowedException`

### ISSUE THREAD

**Issue by liijunwei** [rubocop/rubocop#10861]
I'm trying to understand the behavior of `contains_multiple_levels_of_exceptions` in `lib/rubocop/cop/lint/shadowed_exception.rb`

however the following behavior really confuses me.

+ Q1: I believe if we rescue multiple exceptions in one `rescue clause`, we tend to treat them equally, so there is no `shadowing`, why offence detected?
+ Q2: why both `rescue NoMethodError, StandardError => e` and `rescue StandardError, NoMethodError => e` have offence detected?

--------

example fixture

```ruby
# tmp4.rb
class ShawdowedExceptionFixture
  def run
    puts "running..."
  rescue NoMethodError, StandardError => e
    puts e.message
  end
end

# tmp3.rb
class ShawdowedExceptionFixture
  def run
    puts "running..."
  rescue StandardError, NoMethodError => e # reverse the order
    puts e.message
  end
end
```

## Expected behavior

```bash
exe/rubocop --cache false --only Lint/ShadowedException tmp4.rb
exe/rubocop --cache false --only Lint/ShadowedException tmp3.rb
```

Expect the check not complain

## Actual behavior

both tmp4.rb and tmp3.rb have offences

```bash
$ exe/rubocop --cache false --only Lint/ShadowedException tmp/tmp4.rb
Inspecting 1 file
W

Offenses:

tmp/tmp4.rb:8:3: W: Lint/ShadowedException: Do not shadow rescued Exceptions.
  rescue NoMethodError, StandardError => e ...
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected

$ exe/rubocop --cache false --only Lint/ShadowedException tmp/tmp3.rb
Inspecting 1 file
W

Offenses:

tmp/tmp3.rb:8:3: W: Lint/ShadowedException: Do not shadow rescued Exceptions.
  rescue StandardError, NoMethodError => e ...
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected
```

## Steps to reproduce the problem

rubycop commit: 6b6d5542a156cb855529bc9bf536f260a4dabde6

+ clone repo
+ git checkout 6b6d5542a156cb855529bc9bf536f260a4dabde6
+ make file like tmp4.rb and tmp3.rb
+ run check: `exe/rubocop --cache false --only Lint/ShadowedException tmp/tmp4.rb tmp/tmp3.rb`

## RuboCop version

```bash
$ exe/rubocop -V
1.32.0 (using Parser 3.1.2.0, rubocop-ast 1.19.1, running on ruby 3.1.1 x86_64-darwin20)
  - rubocop-performance 1.14.3
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.11.1
```

**Comment by liijunwei** [comment]
pls help

**Comment by dvandersluis** [comment]
I believe the error is because `NoMethodError` is shadowed by `StandardError` so the behaviour would be the same without `NoMethodError` in your `rescue` statements.

**Comment by liijunwei** [comment]
so are you telling me  these 3 forms are considered exactly the same in rubocop ?
```ruby
# 1
class ShawdowedExceptionFixture
  def run
    puts "running..."
  rescue NoMethodError, StandardError => e
    puts "handler for NoMethodError and StandardError"
  end
end

# 2
class ShawdowedExceptionFixture
  def run
    puts "running..."
  rescue StandardError, NoMethodError => e
    puts "handler for NoMethodError and StandardError"
  end
end

# 3
class ShawdowedExceptionFixture
  def run
    puts "running..."
  rescue StandardError => e
    puts "handler for NoMethodError and StandardError"
  rescue NoMethodError => e
    puts "handler for NoMethodError and StandardError"
  end
end
```

**Comment by dvandersluis** [comment]
I invite you to try it out for yourself:

```ruby
begin
  raise NoMethodError
rescue StandardError
  puts "rescued StandardError"
rescue NoMethodError
  puts "rescued NoMethodError"
end

=> rescued StandardError
```

**Comment by liijunwei** [comment]
I know this behavoir, but I don't understand what you mean ..

**Comment by dvandersluis** [comment]
I don't know that I understand your question then? In all three of your cases, the `NoMethodError` rescue is redundant because the `StandardError` rescue will take priority. The only way you will have a rescue that is only targeting `NoMethodError` but not other `StandardError`s is to rescue it separately, first.

```
begin
  raise NoMethodError
rescue NoMethodError
  puts "rescued NoMethodError"
rescue StandardError
  puts "rescued StandardError"
end

=> rescued NoMethodError
```

**Comment by liijunwei** [comment]
OK, when you say "redundant", I get it now.

```ruby
# 1
class ShawdowedExceptionFixture
  def run
    puts "running..."
  rescue NoMethodError, StandardError => e # "NoMethodError" is called "redundant" and "shadowed" in this case
    puts "handler for NoMethodError and StandardError"
  end
end

# 3
class ShawdowedExceptionFixture
  def run
    puts "running..."
  rescue StandardError => e
    puts "handler for NoMethodError and StandardError"
  rescue NoMethodError => e # "NoMethodError" is called "shadowed" in this case
    puts "handler for NoMethodError and StandardError"
  end
end
```

slight difference, but it's acceptable for me.

I was complaining because I saw a lot of code like case#1, and they're sharing the same exception handler.

I used to think they kind of make sense, but now I have better understanding about them.

Thank you for your patience :pray:

```ruby
begin
  # business logic
rescue NoMethodError,
       StandardError
  puts "rescued StandardError"
end
```
