### ISSUE TITLE
Prevent `Hash.new` with reference values like `Hash.new([])`

### ISSUE THREAD

**Issue by baweaver** [rubocop/rubocop#11013]
## Is your feature request related to a problem? Please describe.

One of the more confusing parts of Ruby is the ability to create a default Hash value pointing at a reference, like:

```ruby
Hash.new([])
Hash.new({})
Hash.new("") # vs frozen
```

This behavior is seldom if ever intended, and leads to unexpected results.

## Describe the solution you'd like

I had managed to create at least a decent skeleton start for this:

```ruby
# Code

module RuboCop
  module Cop
    module Style
      class HashNewReferenceValues < Cop
        MSG = 'Do not use reference values in Hash constructors.'

        def_node_matcher :value_in_constructor, <<~PATTERN
          (send (const nil? :Hash) :new $(...))
        PATTERN

        def_node_matcher :non_reference_value, <<~PATTERN
          {
            # Literals
            (int _) (float _) false true nil

            # BigDecimal explicit
            (send nil? :BigDecimal ...)

            # Coercions to literals
            (send _ { :to_i :to_f :to_d })
          }
        PATTERN

        def_node_matcher :frozen_reference, <<~PATTERN
          (send $... :freeze)
        PATTERN

        def on_send(node)
          constructor_value = value_in_constructor(node)

          return unless constructor_value
          return if non_reference_value(constructor_value)

          add_offense(node)
        end

        def extract_constructor_source(node)
          constructor_value = value_in_constructor(node)
          frozen_ref = frozen_reference(constructor_value)

          return extract_frozen_source(frozen_ref) if frozen_ref

          case constructor_value
          when :array
            "[]"
          when :hash
            "{}"
          when RuboCop::AST::Node
            constructor_value.source
          else
            raise ArgumentError, "Undefined case encountered"
          end
        end

        def extract_frozen_source(node_collection)
          node_collection.first.source
        end

        def autocorrect(node)
          -> (corrector) do
            ref_source = extract_constructor_source(node)

            corrector.replace(node, "Hash.new { |h, k| h[k] = #{ref_source} }")
          end
        end
      end
    end
  end
end

# Spec

RSpec.describe RuboCop::Cop::Style::HashNewReferenceValues, :config do
  let(:cop) { described_class.new(config) }

  [
    "Hash.new(0)",
    "Hash.new(false)",
    "Hash.new(true)",
    "Hash.new(nil)",
    "Hash.new(BigDecimal('0.0'))",
    "Hash.new(0.0)",
    "Hash.new(0.0.to_d)",
    "Hash.new(BigDecimal(0))",
    "Hash.new { |h, k| h[k] = [] }",
  ].each do |good_source|
    it "handles the literal value #{good_source}" do
      expect_no_offenses(good_source)
    end
  end

  it 'flags Array reference values' do
    expect_offense(<<~RUBY)
      Hash.new([])
      ^^^^^^^^^^^^ Do not use reference values in Hash constructors.
    RUBY

    expect_correction(<<~RUBY)
      Hash.new { |h, k| h[k] = [] }
    RUBY
  end

  it 'flags Hash reference values' do
    expect_offense(<<~RUBY)
      Hash.new({})
      ^^^^^^^^^^^^ Do not use reference values in Hash constructors.
    RUBY

    expect_correction(<<~RUBY)
      Hash.new { |h, k| h[k] = {} }
    RUBY
  end

  it 'handles frozen references' do
    expect_offense(<<~RUBY)
      Hash.new([].freeze)
      ^^^^^^^^^^^^^^^^^^^ Do not use reference values in Hash constructors.
    RUBY

    expect_correction(<<~RUBY)
      Hash.new { |h, k| h[k] = [] }
    RUBY
  end

  [
    "Hash.new('some_string')",
    "Hash.new(CONSTANT)",
  ].each do |bad_source|
    it "handles additional bad sources like #{bad_source}" do
      expect_offense(<<~RUBY)
        #{bad_source}
        #{'^' * bad_source.size} Do not use reference values in Hash constructors.
      RUBY

      extracted_source = cop.extract_constructor_source(RuboCop::ProcessedSource.new(bad_source, RUBY_VERSION.to_f).ast)

      expect_correction(<<~RUBY)
        Hash.new { |h, k| h[k] = #{extracted_source} }
      RUBY
    end
  end
end
```

...but wanted to run it by all of you first. It's not comprehensive, but it does serve as a good start for conversation.

**Comment by ioquatix** [comment]
Wouldn't it make more sense for `Hash` to call `dup` in this case? What I mean is, can we propose and fix the behaviour in Ruby rather than plastering over it?

**Comment by baweaver** [comment]
I can write something up on that, though I worry if it's not backported we end up with some real odd discrepancies between versions.

**Comment by ioquatix** [comment]
Sure it can be, but since it's introducing new behaviour which was previously "impossible to use correctly", I don't think there should be any compatibility issues in practice.

**Comment by baweaver** [comment]
Done: https://bugs.ruby-lang.org/issues/19063

I will keep the RuboCop issue open as I have a feeling the answer will be "works as intended", and we should have some form of warning / fix around this behavior as it does make Ruby more difficult for folks.

**Comment by baweaver** [comment]
@bbatsov - Would you all be up for this type of rule being added? I can code up most of it and clean up some of the rough edges here.

**Comment by halostatue** [comment]
> Sure it can be, but since it's introducing new behaviour which was previously "impossible to use correctly", I don't think there should be any compatibility issues in practice, and it might even fix a few bugs :)

I’ve replied on the Ruby bug, but given that there is live code out there that uses this (e.g., Gitlab), but then later does `hash[key] |= values`, I think that there are examples of it being used correctly…if excessively cleverly. Automatically `#dup`ing in that case would be a net negative.

I think that it’s absolutely worth having in Rubocop (and eventually Standard, as that’s my preferred Rubocop runner).

**Comment by markijbema** [comment]
Upvote from me (just shot myself in the foot ;) )

**Comment by corsonknowles** [comment]
We have a `custom_cop` for this, and this type of bug was just the subject of the closing keynote for RubyConf (cheers to  @nodunayo ). 

I'm going to put together a PR to upstream the Rubocop rule to alert on this.

**Comment by corsonknowles** [comment]
Here's the PR to upstream it:

https://github.com/rubocop/rubocop/pull/13463

**Comment by nodunayo** [comment]
> We have a `custom_cop` for this, and this type of bug was just the subject of the closing keynote for RubyConf (cheers to @nodunayo ).
> 
> I'm going to put together a PR to upstream the Rubocop rule to alert on this.

Wow — this is so cool to see! 😍
