### ISSUE TITLE
Every linter diagnostic message is appended with: Using Ruby #{ruby_version} parser; configure using 'TargetRubyVersion' parameter, under 'AllCops'

### ISSUE THREAD

**Issue by WayneNoschang** [rubocop/rubocop#11033]
When using solargraph language server with rubocop each linter diagnostic message has "(Using Ruby 3.0 parser; configure using TargetRubyVersion parameter, under AllCops)" appended to it. 

<img width="1439" alt="189960705-36572249-2c56-48e6-9de8-0fbe852e35fc" src="https://user-images.githubusercontent.com/43730526/193364951-3a267586-f1c3-4303-bbbd-6c712662dbc5.png">

<img width="1440" alt="189960859-58160019-3c35-43d5-9439-af3867912b47" src="https://user-images.githubusercontent.com/43730526/193364818-5eacaecf-64c3-4f94-9b29-c19bf63d59be.png">

<img width="1440" alt="189961527-b4a4305c-eab6-4c34-bc43-88f47463bfef" src="https://user-images.githubusercontent.com/43730526/193364827-7b7ed2b5-7aef-4e99-b835-5718d2d96c33.png">

<img width="1440" alt="189965427-442f8963-68c3-40c6-8eeb-ca72570aed41" src="https://user-images.githubusercontent.com/43730526/193364832-eace5c5a-fb83-4ad6-8fe3-a5b8310153e0.png">

Above setup is also using neovim in iTerm2 on MacOS.

## Expected behavior

Linter diagnostic messages from rubocop should only show linter info only. Notice how formatter diagnostic messages (in blue) do not have any configuration info appended. Appending information about rubocop configurations if there is a configuration issue would be appropriate however. 

## Actual behavior

Each linter diagnostic message has info about the ruby version parser. This message is distracting and removing it would make intuitive sense. [I initially posted this issue to the solargraph repo](https://github.com/castwide/solargraph/issues/597) who was helpful enough to show me the probable culprit located in [lib/rubocop/cop/lint/syntax.rb](https://github.com/rubocop/rubocop/blob/00e7ac78fb83383ef537e9e08ecf2301a1427578/lib/rubocop/cop/lint/syntax.rb)
<img width="1440" alt="Screen Shot 2022-09-30 at 7 10 49 PM" src="https://user-images.githubusercontent.com/43730526/193367969-a8b1a18e-33a1-4476-9182-02b571d6aa1b.png">

## Steps to reproduce the problem

If anyone uses solargraph lsp with vscode or vim with rubocop configured I would expect this to happened to them as well (does it?). If adding rubocop config info to linting diagnostics is a useful feature to them please help me understand why.

## RuboCop version
<img width="1440" alt="Screen Shot 2022-09-30 at 7 05 03 PM" src="https://user-images.githubusercontent.com/43730526/193367594-6bdf3b49-4e24-4c49-944c-b29697e3d53a.png">

I was unsure to post this as a feature request or a bug, forgive me.

**Comment by brendonrapp** [comment]
This is happening to me as well, using Solargraph through nvim-lsp. It is very noisy, and being told over and over again to configure a setting that's already set is obnoxious.

**Comment by bbatsov** [comment]
Have you tried that the new LSP server bundled with RuboCop? 

As for the why this message appears through Solargraph - I'm not sure how they implemented their integration with RuboCop. Perhaps @koic knows more.

**Comment by jonas054** [comment]
The `Lint/Syntax` cop always appends this information about which Ruby version was used for parsing the inspected code. The reason is that something that's a syntax error in one version of Ruby might be valid in another version.

So it's not to tell you that you've done something wrong in your configuration file.

If people are annoyed by this information, I suggest we add some sort of verbosity parameter for `Lint/Syntax`.
