### ISSUE TITLE
Disallow method names with `send` and `public_send`

### ISSUE THREAD

**Issue by klyonrad** [rubocop/rubocop#11061]
## Is your feature request related to a problem? Please describe.

- every so often ruby programmers need to write code that *sends* data somewhere
- Then they add a method that they name `send`
- another developer adds a TODO comment "don't overwrite that ruby method"

Even though `send` is not exactly a *keyword* with methods named `send` one could the control for metaprogramming that relies on using this method

## Describe the solution you'd like

- a cop in the `Lint` namespace

## Describe alternatives you've considered

None

## Additional context

- https://ruby-doc.org/core-3.1.2/Object.html#method-i-send

**Comment by koic** [comment]
Ruby provides `__send__` considering that `send` is overridden. In other words, `__send__` should not be overridden.
I think metaprogramming like using `send` is used only in limited cases. Disabled by default, but `Style/Send` cop will already be there for that.
Of course, I don't recommend overriding `send`, but I think `Lint` warning is too strict.

**Comment by klyonrad** [comment]
Sorry, I didn't know that this cop existed already and didn't know that a standard library has a `send` method :) https://docs.rubocop.org/rubocop/cops_style.html#stylesend
