### ISSUE TITLE
Request: Allow to add method arguments to Metrics/MethodLength CountAsOne

### ISSUE THREAD

**Issue by hacktivista** [rubocop/rubocop#11070]
## Is your feature request related to a problem? Please describe.

I tend to write
```ruby
method(
  param1, param2, param3
)
```
Instead of
```ruby
method(
  param1,
  param2,
  param3
)
```
Which I think is clearer, just because I need to respect the method length limit.

Sometimes calling the method in one line isn't possible if I respect a 80 characters line width. 

## Describe the solution you'd like

I'd like to be able to specify that method calls can be counted as a single line. Something like:

```yaml
Metrics/MethodLength:
  CountAsOne: ['arguments']
```

**Comment by fatkodima** [comment]
Makes sense to me. 
@bbatsov what do you think on this change?

**Comment by bbatsov** [comment]
Sounds reasonable.
