### ISSUE TITLE
Add a `Lint` cop to ask programmer to clarify `foo.&bar` into either safe navigation or bitwise and

### ISSUE THREAD

**Issue by Qqwy** [rubocop/rubocop#11079]
## Is your feature request related to a problem? Please describe.

Safe navigation uses the syntax `foo&.bar`.

However, when mistakenly writing `foo.&bar` instead, the Ruby parser happily accepts this.
After all:
```ruby
   foo.&bar
== foo.& bar
== foo.&(bar)
== foo & bar
```
That is, this is interpreted as usage of the 'bitwise and' operator. (Or an overloaded version of the binary `&` operator).

While the Ruby parser has to accept this syntax, it is highly unlikely that a user uses the particular way of writing `foo.&bar`
to mean `foo & bar`.
It is much more likely that the user meant to use the safe navigation `foo&.bar` syntax instead.

## Describe the solution you'd like

I would like a simple lint cop that warns when someone writes `foo.&bar`, and suggests the programmer to clarify:
- Whether they meant `foo&.bar`
- Or whether they meant `foo & bar`

## Describe alternatives you've considered

I do not think that there are easy alternatives. 

We cannot alter what the Ruby parser itself does for this kind of situation, since it has to remain consistent with how method dispatching works.

## Extra context

One thing I am not sure about, is how to name this cop.

`Lint/AmbiguousBitwiseAnd` maybe? 

---

What do you think?
I would gladly contribute a PR that implements this cop :blush: .

**Comment by koic** [comment]
I think it's better if the semantics don't change.

```ruby
# bad
foo.&bar

# good
foo & bar
```

So changing `foo.&bar` to `foo & bar` is a safer correction than changing it to `foo&.bar`. Either way, it's up to the user whether `.&` means `&` or `&.`.

I've opened PR #11080 to solved the above.

**Comment by Qqwy** [comment]
Thank you! Your PR is a nice, much more general way to resolve this problem 💚!
