### ISSUE TITLE
Style/RedundantStringEscape cop is crashing on some rare inputs

### ISSUE THREAD

**Issue by denis-kos** [rubocop/rubocop#11089]
The code as follows cause cop to crash:
```
["one", "two"] * ?.
# => "one.two"
```
--------
## Expected behavior
The cop should not crash. Rubocop probably can suggest to rewrite the code like `["one", "two"].join(".")`, but not crash.

## Actual behavior
`An error occurred while Style/RedundantStringEscape cop was inspecting ...`

## RuboCop version
```
$ [bundle exec] rubocop -V
1.37.0 (using Parser 3.1.2.1, rubocop-ast 1.22.0, running on ruby 3.1.1) [x86_64-linux]
  - rubocop-rails 2.15.2
  - rubocop-rspec 2.12.1
```

**Comment by bbatsov** [comment]
@owst Please, take a look.
