### ISSUE TITLE
`Couldn't find Rails/DefaultScope in comment: # rubocop:disable Rails::SkipsModelValidations` for `Lint/RedundantCopDisableDirective` crash

### ISSUE THREAD

**Issue by ShockwaveNN** [rubocop/rubocop#11143]
## Actual behavior

Seems `Lint/RedundantCopDisableDirective` cop failed on single file in my codebase

## Steps to reproduce the problem

1. Create `test.rb` file with:
```ruby
# frozen_string_literal: true

# This migration comes from active_storage (originally 20190112182829)
class AddServiceNameToActiveStorageBlobs < ActiveRecord::Migration[6.0]
  def up
    return if column_exists?(:active_storage_blobs, :service_name)

    add_column :active_storage_blobs, :service_name, :string

    if (configured_service = ActiveStorage::Blob.service.name)
      # rubocop:disable Rails::SkipsModelValidations
      ActiveStorage::Blob.unscoped.update_all(service_name: configured_service)
      # rubocop:enable Rails::SkipsModelValidations
    end

    change_column :active_storage_blobs, :service_name, :string, null: false
  end

  def down
    remove_column :active_storage_blobs, :service_name
  end
end

```

2. run `rubocop test.rb`
```bash
# rubocop test.rb 
Inspecting 1 file
An error occurred while Lint/RedundantCopDisableDirective cop was inspecting /home/lobashov/sources/testing-wrata/test.rb.
To see the complete backtrace run rubocop -d.
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Lint/RedundantCopDisableDirective cop was inspecting /home/lobashov/sources/testing-wrata/test.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop/rubocop/issues

Mention the following information in the issue report:
1.38.0 (using Parser 3.1.2.1, rubocop-ast 1.23.0, running on ruby 3.1.2) [x86_64-linux]
```

## RuboCop version

```
$ [bundle exec] rubocop -V
1.38.0 (using Parser 3.1.2.1, rubocop-ast 1.23.0, running on ruby 3.1.2) [x86_64-linux]
  - rubocop-performance 1.15.0
  - rubocop-rails 2.17.2
  - rubocop-rspec 2.14.2
```

This error introduced in `rubocop-1.38.0`
Everything was fine in 1.37.1

<details>
  <summary>Debug run details</summary>
Couldn't find Rails/DefaultScope in comment: # rubocop:disable Rails::SkipsModelValidations
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cop/lint/redundant_cop_disable_directive.rb:256:in `cop_range'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cop/lint/redundant_cop_disable_directive.rb:233:in `block in add_offense_for_some_cops'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/3.1.0/set.rb:511:in `each_key'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/3.1.0/set.rb:511:in `each'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cop/lint/redundant_cop_disable_directive.rb:233:in `map'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cop/lint/redundant_cop_disable_directive.rb:233:in `add_offense_for_some_cops'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cop/lint/redundant_cop_disable_directive.rb:212:in `block in add_offenses'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cop/lint/redundant_cop_disable_directive.rb:208:in `each'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cop/lint/redundant_cop_disable_directive.rb:208:in `add_offenses'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cop/lint/redundant_cop_disable_directive.rb:51:in `on_new_investigation'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:153:in `block (2 levels) in invoke'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:160:in `with_cop_error_handling'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:153:in `block in invoke'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:153:in `each'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:153:in `invoke'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:84:in `investigate'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cop/team.rb:154:in `investigate_partial'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cop/team.rb:82:in `investigate'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/runner.rb:315:in `inspect_file'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/runner.rb:172:in `block in add_redundant_disables'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/runner.rb:193:in `team_for_redundant_disables'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/runner.rb:171:in `add_redundant_disables'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/runner.rb:139:in `block in file_offenses'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/runner.rb:163:in `file_offense_cache'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/runner.rb:137:in `file_offenses'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/runner.rb:128:in `process_file'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/runner.rb:109:in `block in each_inspected_file'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/runner.rb:108:in `each'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/runner.rb:108:in `reduce'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/runner.rb:108:in `each_inspected_file'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/runner.rb:94:in `inspect_files'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/runner.rb:47:in `run'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cli/command.rb:11:in `run'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cli/environment.rb:18:in `run'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cli.rb:72:in `run_command'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cli.rb:79:in `execute_runners'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/lib/rubocop/cli.rb:48:in `run'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/exe/rubocop:19:in `block in <top (required)>'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/home/lobashov/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.38.0/exe/rubocop:19:in `<top (required)>'
/home/lobashov/.rbenv/versions/3.1.2/bin/rubocop:25:in `load'
/home/lobashov/.rbenv/versions/3.1.2/bin/rubocop:25:in `<main>'
</details>

**Comment by Vasfed** [comment]
example can be shorter:
```ruby
# rubocop:disable Layout
# no offences here
# rubocop:enable Layout
```

**Comment by ngouy** [comment]
PR that where something likely went under radar that causes this issue:
https://github.com/rubocop/rubocop/pull/10987

**Comment by vweidhaas** [comment]
I have the same issue

**Comment by ngouy** [comment]
Anyone found a workaround?

**Comment by z56cjt709** [comment]
This work around seemed to resolve the issue for me:

```
# rubocop:todo Rails/SkipsModelValidations
        ActiveStorage::Blob.unscoped.update_all(service_name: configured_service)
        # rubocop:enable Rails/SkipsModelValidations
```
https://docs.rubocop.org/rubocop/configuration.html#disabling-cops-within-source-code

**Comment by ngouy** [comment]
🙏
