### ISSUE TITLE
How do I get rubocop to accept non-indented `x = if ...`?

### ISSUE THREAD

**Issue by ioquatix** [rubocop/rubocop#11155]
How do I get RuboCop to accept the following format? No matter what I try it basically wants to format this code block with alignment, e.g.

```ruby
      policy = if policy_class
        policy_class.new(user, record)
      else
        cache[possibly_namespaced_record] ||= policy!(user, possibly_namespaced_record)
      end
```

gives:

```
Offenses:

lib/asdf/authorization.rb:48:9: C: [Correctable] Layout/IndentationWidth: Use 2 (not -7) spaces for indentation.
        policy_class.new(user, record)
        ^^^^^^^
lib/asdf/authorization.rb:49:7: C: [Correctable] Layout/ElseAlignment: Align else with if.
      else
      ^^^^
lib/asdf/authorization.rb:51:7: W: [Correctable] Layout/EndAlignment: end at 51, 6 is not aligned with if at 47, 15.
      end
      ^^^
```

I'm completely against code "alignment" as it creates a ton of edit amplification.

**Comment by vlad-pisanov** [comment]
Disable the two alignment rules: `Layout/ElseAlignment` and `Layout/EndAlignment` in your `.rubocop.yml`, i.e.

```yaml
Layout/ElseAlignment:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
```

**Comment by ioquatix** [comment]
Right, but won't that disable it in other useful cases, i.e. when the if statement isn't a nested part of an expression?

**Comment by Drenmi** [comment]
> I'm completely against code "alignment" as it creates a ton of edit amplification.

I share your sentiment, @ioquatix. 🙂 

I'm marking this as a feature request. If we can put enough meat on it we could make it a configuration option. Maybe we can start with one or two examples of the useful cases you mentioned, as code examples form great test cases for cops.

**Comment by koic** [comment]
Can you solve this issue by setting `EnforcedStyleAlignWith` config of `Layout/EndAlignment` cop to `start_of_line`?

```yaml
Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
```

**Comment by koic** [comment]
So, I think the existing `EnforcedStyleAlignWith: start_of_line` config could be the solution instead of a new feature.

**Comment by ioquatix** [comment]
I will try it next week and report back.

**Comment by pahnin** [comment]
looks like now we can do 
```
EnforcedStyleAlignWith: variable
```
https://github.com/rubocop/rubocop/blob/master/lib/rubocop/cop/layout/end_alignment.rb

**Comment by Earlopain** [comment]
For me, both `variable` and `start_of_line` work fine. Per docs there is a difference but I seem to not have written code where it would actually matter.

**Comment by ioquatix** [comment]
Thanks everyone!
