### ISSUE TITLE
online doc: the rendering of the tables is broken

### ISSUE THREAD

**Issue by akimd** [rubocop/rubocop#11153]
https://docs.rubocop.org/rubocop/cops_layout.html for instance shows as:

<img width="829" alt="image" src="https://user-images.githubusercontent.com/232441/200029586-7c58e72d-03d9-497f-982e-588b569e8a2c.png">

(Firefox and Safari)

A bit farther:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/232441/200029678-b66dd90d-0067-4f93-bb5b-8bdc3a367668.png">

Cheers!

**Comment by vlad-pisanov** [comment]
seems to be due to this commit: https://github.com/rubocop/rubocop/commit/52a56f0be2332d61718597261a15860201d1fc3c

**Comment by akimd** [comment]
While at it, you might want to fix the example of AbcSize (https://docs.rubocop.org/rubocop/cops_metrics.html#metricsabcsize):
```
# `model` and `current_user`, refenced 3 times each,
```
I suppose s/refenced/referenced/.

**Comment by koic** [comment]
The rendering of the tables will be recovered by https://github.com/rubocop/rubocop/pull/11136. But not yet applied to the doc site. And `s/refenced/referenced/` has been fixed by https://github.com/rubocop/rubocop/commit/af68c6fc420fcbe7d6bfca1db90df3a93a21938b.

**Comment by koic** [comment]
RuboCop 1.39 has been released. Please see the latest docs. Thank you.
