### ISSUE TITLE
Cop Idea: add to array if not nil should use push with array decomposition

### ISSUE THREAD

**Issue by choosen** [rubocop/rubocop#11195]
I wrote the code:
```ruby
def add_plates
  data_array[:identifiers] << plates unless plates.nil?
end

def plates
  user.plates.map(&:value).map { |v| { plate: v} }
end
```
Then I did not want to write code with memoization so I find the way:
```ruby
def add_plates
  data_array[:identifiers].push *plates
end
```

I imagined that this solution does not require variable to store value and is shorter.
Maybe not straight forward and should be in rubocop-performance ?

**Comment by koic** [comment]
I'm going close this proposal because it looks like incompatible code or very specific background.

**Comment by choosen** [comment]
@koic  what is it here incompatible ?
