### ISSUE TITLE
Support asdf when determining `TargetRubyVersion`

### ISSUE THREAD

**Issue by andyw8** [rubocop/rubocop#11208]
https://docs.rubocop.org/rubocop/configuration.html

> Otherwise, RuboCop will then check your project for a series of files where the version may be specified already. The files that will be looked for are .ruby-version, Gemfile.lock, and *.gemspec.

With [asdf](https://github.com/asdf-vm/asdf) becoming increasingly popular, it would be good to include `.tool-versions` when choosing a suitable Ruby version.

**Comment by koic** [comment]
RuboCop already supports `.tool-version` and I've updated the doc.

**Comment by andyw8** [comment]
Ah thank you, I see it was added in https://github.com/rubocop/rubocop/pull/9319/files.
