### ISSUE TITLE
`--only` only supports one argument

### ISSUE THREAD

**Issue by pirj** [rubocop/rubocop#11243]
```
rubocop --only RSpec/Capybara/MatchStyle --only RSpec/Capybara/SpecificActions --only RSpec/Capybara/SpecificFinders ../real-world-rspec
```

only runs it for `RSpec/Capybara/SpecificFinders`, the rest are ignored.

--------

## Expected behavior

All `--only` options are considered

## Actual behavior

Only the last `--only` is considered

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler.
If you see extension cop versions (e.g. `rubocop-performance`, `rubocop-rspec`, and others)
output by `rubocop -V`, include them as well. Here's an example:

```
$ [bundle exec] $ rubocop -V
1.38.0 (using Parser 3.1.2.1, rubocop-ast 1.23.0, running on ruby 3.0.3) [x86_64-darwin18]
  - rubocop-performance 1.15.0
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.15.0
```

**Comment by dvandersluis** [comment]
FYI `—only RSpec/Capybara/MatchStyle, RSpec/Capybara/SpecificActions, RSpec/Capybara/SpecificFinders` should work (but I agree multiple `only`s are not working as I’d expect either).

**Comment by pirj** [comment]
Oh, this is even in the help output. I apologize for my ignorance. Thanks for the heads-up!
```
--only [COP1,COP2,...]       Run only the given cop(s).
```
I'll just close this since there's a way to achieve what I wanted.
