### ISSUE TITLE
Cop idea: `Style/InadvertStringLiteralConcatenation`

### ISSUE THREAD

**Issue by pirj** [rubocop/rubocop#11259]
## Is your feature request related to a problem? Please describe.

```ruby
> puts 'a', 'b'
a
b
> puts 'a' 'b'
ab
```

A missed comma can cause string literal arguments to be concatenated mistakenly when passed to a method accepting varargs.

## Describe the solution you'd like

Introduce a cop that would detect such cases when two string literals are on a single line.

## Describe alternatives you've considered

Unaware of.

**Comment by bbatsov** [comment]
I like this idea.
