### ISSUE TITLE
Lint/UnreachableCode does not handle ActiveRecord::Rollback exceptions correctly

### ISSUE THREAD

**Issue by kd-panix** [rubocop/rubocop#11296]
1.39.0 (using Parser 3.1.2.1, rubocop-ast 1.23.0, running on ruby 3.0.4) [x86_64-netbsd9.1]

code such as
if condition
  raise ActiveRecord::Rollback
  do_something
  redirect_to somewhere and return
end

is incorrectly triggering the cop

**Comment by koic** [comment]
It seems to work correctly:

```ruby
if condition
  raise ActiveRecord::Rollback
  do_something
  redirect_to somewhere and return
end
```

```console
% bundle exec rubocop --only Lint/UnreachableCode
(snip)

Inspecting 1 file
W

Offenses:

example.rb:3:3: W: Lint/UnreachableCode: Unreachable code detected.
  do_something
  ^^^^^^^^^^^^

1 file inspected, 1 offense detected
```

What problem do you have?

**Comment by kd-panix** [comment]
In the case if ActiveRecord::Rollback exceptions, the code below IS
reached, as per
https://api.rubyonrails.org/classes/ActiveRecord/Rollback.html

Ken

Quoth Koichi ITO ***@***.***):
> It seems to work correctly:
> 
> ```ruby
> if condition
>   raise ActiveRecord::Rollback
>   do_something
>   redirect_to somewhere and return
> end
> ```
> 
> ```console
> % bundle exec rubocop --only Lint/UnreachableCode
> (snip)
> 
> Inspecting 1 file
> W
> 
> Offenses:
> 
> example.rb:3:3: W: Lint/UnreachableCode: Unreachable code detected.
>   do_something
>   ^^^^^^^^^^^^
> 
> 1 file inspected, 1 offense detected
> ```
> 
> What problem do you have?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/rubocop/rubocop/issues/11296#issuecomment-1355210527
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>
-- 
I use the words you taught me. If they don't mean anything any more,
teach me others. Or let me be silent.
                        Samuel Beckett (Clov, Endgame)

**Comment by koic** [comment]
`do_something` is never reached after `ActiveRecord::Rollback` exception is raised.

```ruby
if condition
  raise ActiveRecord::Rollback
  do_something
  redirect_to somewhere and return
end
```

As the docs say, `Lint/UnreachableCode` won't warn the code below if it's enclosed in `transaction`.

```ruby
def index
  Article.transaction do
    raise ActiveRecord::Rollback
  end
  @articles = Article.all
end
```

```console
% bundle exec rubocop --only Lint/UnreachableCode
(snip)

Inspecting 1 file
.

1 file inspected, no offenses detected
```

So, `Lint/UnreachableCode` seems to work as an expected behavior.
