### ISSUE TITLE
Style/ConcatArrayLiterals documentation mismatch

### ISSUE THREAD

**Issue by delphaber** [rubocop/rubocop#11312]
In the `Style/ConcatArrayLiterals` documentation section it says that cop is unsafe, but the header says it is safe. Who is lying? 😄 

![CleanShot 2022-12-21 at 14 52 54@2x](https://user-images.githubusercontent.com/139284/208922484-b59eb9d7-3f91-434f-90d8-1f276307097b.png)

https://docs.rubocop.org/rubocop/1.41/cops_style.html#styleconcatarrayliterals

**Comment by koic** [comment]
The doc "Safety" description is correct and fixed by https://github.com/rubocop/rubocop/commit/8bb0c47e7a654a72dcfb7024083cbb4898cae03d. Thank you!

**Comment by delphaber** [comment]
Thank you!

**Comment by lucascaton** [comment]
By the way, its autocorrection is not working (not even with `-A` flag) 🙂
