### ISSUE TITLE
Improved "fix" for Style/NumericPredicate: Use changes.size.positive? instead of changes.size > 0.

### ISSUE THREAD

**Issue by PeterHickman** [rubocop/rubocop#11314]
## Is your feature request related to a problem? Please describe.

Given `changes` is an array then code like `changes.size > 0` is converted to `changes.size.positive?`

## Describe the solution you'd like

The simpler solution, given that `changes` is an array, would be `changes.any?`

## Describe alternatives you've considered

This is only a niggle with only the slightest of performance boost (if any)

**Comment by koic** [comment]
Fastest is `array.size > 0` with `EnforcedStyle: comparison`:

```ruby
% cat bench/numeric_predicate.rb
require 'benchmark/ips'

def array
  [1, 2, 3]
end

Benchmark.ips do |x|
  x.report('size > 0')       { array.size > 0 }
  x.report('size.positive?') { array.size.positive? }
  x.report('any?')           { array.any? }

  x.compare!
end

% ruby bench/numeric_predicate.rb
Warming up --------------------------------------
            size > 0     1.129M i/100ms
      size.positive?   928.545k i/100ms
                any?   889.469k i/100ms
Calculating -------------------------------------
            size > 0     11.598M (± 4.6%) i/s -     58.731M in   5.077203s
      size.positive?      9.099M (± 1.7%) i/s -     45.499M in   5.002043s
                any?      9.857M (± 1.9%) i/s -     49.810M in   5.054979s

Comparison:
            size > 0: 11597663.1 i/s
                any?:  9857306.0 i/s - 1.18x  (± 0.00) slower
      size.positive?:  9098950.8 i/s - 1.27x  (± 0.00) slower
```

`size.positive` and `any?` are probably different expressions intended by user. I'm not sure whether `any?` is always better than that.

**Comment by koic** [comment]
@vlad-pisanov Good point. `array.length == 0` and `array.length.zero?` are equivalent, it should be possible to convert to `array.emtpy?` in the same way. I've opened #11327.
