### ISSUE TITLE
Style/FrozenStringLiteralComment docs and default

### ISSUE THREAD

**Issue by halilim** [rubocop/rubocop#11311]
The [documentation](https://github.com/rubocop/rubocop/blob/91fe2cf9f69dbf6d35c17acf492b6494d691c3f5/lib/rubocop/cop/style/frozen_string_literal_comment.rb#L9-L10) states that:

> Frozen string literals may be default in future Ruby.

I believe that was meant for Ruby 3. However, it [did not](https://bugs.ruby-lang.org/issues/11473#note-53) come to pass:

> I consider this for years. I REALLY like the idea but I am sure introducing this could cause HUGE compatibility issue, even bigger than Ruby 1.9. So I officially abandon making frozen-string-literals default (for Ruby3).
>
> This does not mean we are going to remove the frozen-string-literal feature that can be specified by magic comments.
>
> Matz.

I was going to go ahead and create a small pull request to remove that sentence. But first, I wanted to clarify a few things:

1. Is there any other plan for Ruby to make this change that I have missed?
2. More importantly; since the change was abandoned, do we still want to keep the cop enabled by default? That would normally look like the preferable option, but some projects do not use it. For example, a new Rails project does not feature it, so one would need to go over all Ruby files as soon as they add Rubocop. There seems to be relatively little discussion about the current state of things at large ([an example](https://www.jakeworth.com/frozen-string-comment-yagni/) against it).

**Comment by koic** [comment]
Plans to make frozen string literals the default have been resumed:
https://bugs.ruby-lang.org/issues/20205#note-35

So, I'll close this issue. Thank you.
