### ISSUE TITLE
Failing example for Naming/BlockForwarding and Lint/UselessAssignment

### ISSUE THREAD

**Issue by kalsan** [rubocop/rubocop#11313]
The following code gets refactored in a wrong way by `rubocop -A` (with `rubocop-rails` installed:

## Source

```ruby
def foo(&block)
  block = proc {} unless block_given?
  pass_to_bar(&block)
end
```

## Misbehavior

- `Naming/BlockForwarding: Use anonymous block forwarding`
- `Lint/UselessAssignment: Useless assignment to variable - block.` but the block is actually used on line 3 (after correction, possibly fixed implicitely when BlockForwarding is fixed)

The code becomes:

```ruby
def foo(&)
  block = proc {} unless block_given?
  pass_to_bar(&)
end
```

--> Line 2 is now ineffective and the `pass_to_bar` crashes then given a nil block.

## RuboCop version

```
1.41.0 (using Parser 3.1.3.0, rubocop-ast 1.24.0, running on ruby 3.1.3) [x86_64-linux]
  - rubocop-rails 2.17.3
```

**Comment by kalsan** [comment]
Thank you, that was blazing fast! Looking forwad to the next release :-)

**Comment by koic** [comment]
RuboCop 1.41.1 has just been released! You can upgrade to the latest version to fix the bug. Thank you.

**Comment by kalsan** [comment]
Awesome - it works flawlessly! Thanks and have a great day!
