### ISSUE TITLE
Cop idea: prefer `to_set {...}` over `map {...}.to_set`

### ISSUE THREAD

**Issue by vlad-pisanov** [rubocop/rubocop#11339]
This new cop would be a twin of [Style/MapToHash](https://docs.rubocop.org/rubocop/cops_style.html#stylemaptohash), but for `.to_set`:

```ruby
# bad
list.map { |x| x + 1 }.to_set
list.collect(&:to_s).to_set
# good
list.to_set { |x| x + 1 }
list.to_set(&:to_s)
```

Performance-wise, both ways appear to be identical (although there may be some additional memory benefit in avoiding the intermediate `.map` since sets are implemented using hashes internally 🤷‍♂️)

**Comment by koic** [comment]
This idea looks good to me. I've opened #11340.
