### ISSUE TITLE
Add Lint/DeprecatedAttr cop

### ISSUE THREAD

**Issue by dduugg** [rubocop/rubocop#11350]
## Is your feature request related to a problem? Please describe.

`attr` with a second boolean parameter has been marked as deprecated since Ruby 2.5:

https://github.com/ruby/ruby/commit/7b19e6f3fdf8b0238752cb1561dfe42a283f5308#diff-1b7f91891e9afd5c2c43fea4d989d0c4f8495cca99ac3ff5f825a7b30c435055R2309-R2310
https://ruby-doc.org/core-2.5.0/Module.html#method-i-attr

I would like a rule to flag such deprecated uses of `attr`. It could also autocorrect to their non-deprecated equivalents.

## Describe the solution you'd like

```ruby
# bad
attr :foo, true
attr :bar, false

# good
attr_accessor :foo
attr_reader :bar
attr :baz
```

## Describe alternatives you've considered

Optionally, we could also encourage `attr_reader :baz` over `attr :baz` as a stylistic opinion, but that doesn't relate to deprecation, and thus feels out of scope here.

## Additional context

N/A

**Comment by koic** [comment]
It will extend `Lint/DeprecatedClassMethods` instead of new cop. However, it seems that an extension that can notice the arguments is required.

**Comment by dduugg** [comment]
Thanks @koic ! 😍
