### ISSUE TITLE
New cop to check for commented out debug calls 

### ISSUE THREAD

**Issue by adamzapasnik** [rubocop/rubocop#11352]
## Is your feature request related to a problem? Please describe.

Sometimes, accidentally you can commit commented out debug calls like this:

```ruby
def something
  something
  # debugger
  something2 

  # debugger
end
```

I think these `# debugger` lines are ugly and they shouldn't get committed after a code review, but it's easy to miss them, so why not have Rubocop take care of them?

## Describe the solution you'd like

At first I was thinking of adding this capability to `RuboCop::Cop::Lint::Debugger`, but it seems like a wrong place. Someone could accidentally disable the cop and commit a real debug call, even though they just wanted to disable it for commented out calls. Thus the idea for a new cop 🤔 

## Describe alternatives you've considered

No idea how else to tackle it

**Comment by koic** [comment]
I will close this proposal. Because AFAIK there is no general convention that this comment is for debugging.
You can create custom cop in your application:
https://docs.rubocop.org/rubocop/1.41/development.html

Thank you.
