### ISSUE TITLE
"Style/ZeroLengthPredicate: Use empty? instead of size.zero?." triggering for StringIO

### ISSUE THREAD

**Issue by HoneyryderChuck** [rubocop/rubocop#11376]
## Expected behavior

autocorrect should not rewrite ".size.zero?" to ".empty?", as not all objects implementing ".size" implement ".empty?" (such as stringio).

## Steps to reproduce the problem

run with `-a` option this script:

```ruby

require "stringio"

io = StringIO.new
puts io.size.zero?
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler.
If you see extension cop versions (e.g. `rubocop-performance`, `rubocop-rspec`, and others)
output by `rubocop -V`, include them as well. Here's an example:

```
$ [bundle exec] rubocop -V
1.42.0 (using Parser 3.1.3.0, rubocop-ast 1.24.1, running on ruby 3.1.2) [x86_64-darwin20]
  - rubocop-performance 1.15.2
```

**Comment by koic** [comment]
This cop is already marked as unsafe:
https://docs.rubocop.org/rubocop/1.42/cops_style.html#stylezerolengthpredicate

Thank you.
