### ISSUE TITLE
Style/ArrayIntersect causes undefined method `intersect?' for #<ActiveRecord::Associations::CollectionProxy

### ISSUE THREAD

**Issue by WillTaylor22** [rubocop/rubocop#11412]
rails 7.0.3
ruby-3.2.0

Rubocop corrected `(accounts & other_accounts).any?` to `accounts.intersect?(other_accounts)`, however `accounts` and `other_accounts` are instances of `ActiveRecord::Associations::CollectionProxy`, not arrays, and `intersect?` is not present on `ActiveRecord::Associations::CollectionProxy`.

Fortunately this was caught by my test suite, but was a bit scary as I was about to deploy to production, and I traditionally have run rubocop after the tests.

**Comment by fatkodima** [comment]
Yeah, this cop is not safe - https://github.com/rubocop/rubocop/blob/1e5f19a9afddb0e5123c86efb0f5957431c7a6d4/lib/rubocop/cop/style/array_intersect.rb#L14-L16. So this is expected.

**Comment by tindron** [comment]
> Yeah, this cop is not safe -
> 
> https://github.com/rubocop/rubocop/blob/1e5f19a9afddb0e5123c86efb0f5957431c7a6d4/lib/rubocop/cop/style/array_intersect.rb#L14-L16
> 
> . So this is expected.

But it's not marked `Safe: false` in `config/default.yml` so it's being autocorrected on a safe autocorrect.

**Comment by fatkodima** [comment]
Ah, I see. Would you like to open a PR with this change?

**Comment by koic** [comment]
This issue fixed by https://github.com/rubocop/rubocop/commit/d02d3149231d67f5a7fd59e00fe4ede0c3e01de6.
