### ISSUE TITLE
Custom formatter guide recommends use of an API marked as private

### ISSUE THREAD

**Issue by sambostock** [rubocop/rubocop#11434]
The [custom formatter guide says to use `BaseFormatter`](https://docs.rubocop.org/rubocop/extensions.html#creating-a-custom-formatter):

> ### Creating a Custom Formatter
> To implement a custom formatter, you need to subclass `RuboCop::Formatter::BaseFormatter` and override some methods, or implement all formatter API methods by duck typing.
> 
> Please see the documents below for more formatter API details.
> - [`RuboCop::Formatter::BaseFormatter`](https://www.rubydoc.info/gems/rubocop/RuboCop/Formatter/BaseFormatter)
> - [`RuboCop::Cop::Offense`](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Offense)
> - [`Parser::Source::Range`](https://www.rubydoc.info/gems/parser/Parser/Source/Range)

However, [the class is listed as private API](https://www.rubydoc.info/gems/rubocop/RuboCop/Formatter/BaseFormatter)

> ## Class: RuboCop::Formatter::BaseFormatter <sub><code>Private</code></sub>
> ### Overview
> > **Warning**
> > **This class is part of a private API.** You should avoid using this class if possible, as it may be removed or be changed in the future.
> 
> Abstract base class for formatter, implements all public API methods.

--------

## Expected behavior

Either the guide should recommend another approach, or the API documentation should not describe the formatter as private.

## Actual behavior

The guide and API docs conflict.

## Steps to reproduce the problem

Visit current (January 12 2023) versions of links above.

## RuboCop version

Not really relevant, since it's docs. Current SHAs of `master` branches are:
- [rubocop/rubocop@c11a8b1421](https://github.com/rubocop/rubocop/commit/c11a8b1421852ef6c71e2d4be41abb1559098e36)
- [rubocop/docs.rubocop.org@471f20505c](https://github.com/rubocop/docs.rubocop.org/commit/471f20505c3e2c4cadcff535da1372b6aca46cb4)

**Comment by koic** [comment]
This is an erroneous `@api private` mark for `RuboCop::Formatter` introduced in #11294. So the guide is correct. I've fixed it by https://github.com/rubocop/rubocop/commit/b1fb518828854c5bbf4f0b3c6d0a0348ff518b7b.
