### ISSUE TITLE
[Discussion] do you think adding a Cop to detect `puts/ap/p/pp` usage in code reasonable ?

### ISSUE THREAD

**Issue by liijunwei** [rubocop/rubocop#11517]
## Is your feature request related to a problem? Please describe.

I noticed that our organization project has many `puts/ap/p/pp` usage in production code, and I think it's a not reasonable to keep them unless we're debugging.

## Describe the solution you'd like

I developed a simple cop to detect `puts/ap/p/pp` usage that helps me quickly spot them and remove them from codebase

## Describe alternatives you've considered

NA

## Additional context

I'm submitting this issue to open a discussing for:
- do you think my logic stands?
- if it does, do you want this cop ?
- if it's not necessary, any alternatives suggestion is appreciated 🙏 

this is what I've developed
https://github.com/rubocop/rubocop/compare/master...junwei-lii:rubocop:cop-to-detect-printer

**Comment by koic** [comment]
These can consist of `Lint/Debugger`. I've opened #11518 that adds the standard API `p`, `pp`, and `PP.pp` to the config by default. OTOH, `puts` is not included in the config because it is used for the intended stdout. The same is true for `ap`, which is not a standard API. So, please make it config in user side .rubocop.yml if needed.

**Comment by liijunwei** [comment]
let me try and see, will close this issue if it works.

Thank you so much~

**Comment by liijunwei** [comment]
It's working as expected, really appreciate your help, good day~

**Comment by koic** [comment]
JFYI, I reconsidered based on some feedback and opened #11564. It should be configured print debug methods in user side .rubocop.yml after #11564 will be patched.

**Comment by liijunwei** [comment]
Noted, I've added those methods to our project config file.

Thanks for the information
