### ISSUE TITLE
Cop to catch unescaped `]` in RegExp

### ISSUE THREAD

**Issue by sambostock** [rubocop/rubocop#11514]
## Is your feature request related to a problem? Please describe.

Ruby emits a warning for the following:

```sh
ruby -c -e '/abc]123/'
-e:1: warning: regular expression has ']' without escape: /abc]123/
Syntax OK
```

## Describe the solution you'd like

It would be nice if Rubocop could catch this statically, as that integrates better into CI.

## Describe alternatives you've considered

Tools like [Deprecation Toolkit](https://github.com/Shopify/deprecation_toolkit) can be configured to catch warnings, but in the case of Deprecation Toolkit, it will only do so while running tests, whereas we encountered a case where the file had already been read by then.

**Comment by imskr** [comment]
Can I work on this?

**Comment by bbatsov** [comment]
Sure.

**Comment by sonalinavlakhe** [comment]
@bbatsov, if no one picked up this, I wanted to work on it.

**Comment by imskr** [comment]
I was about to make a PR. I will let you know if I will not be working on this. Sorry for the delay. @sonalinavlakhe

**Comment by TechTarun** [comment]
@bbatsov can I take this up?

**Comment by bbatsov** [comment]
Sure!

**Comment by yamakoud** [comment]
any update?

Is someone working for this?

**Comment by TechTarun** [comment]
Yess I am! Will raise MR soon

**Comment by rimshach2** [comment]
If no one is working on this, can I take this issue?

**Comment by TechTarun** [comment]
I am working on it!

Thanks
Tarun

**Comment by bbatsov** [comment]
See also https://github.com/rubocop/rubocop/pull/12805

**Comment by petrenkorf** [comment]
@TechTarun any updates on this?
