### ISSUE TITLE
Could not find gem 'rubocop (~> 1.44.0)' with platform 'x86_64-linux'

### ISSUE THREAD

**Issue by drjeon92** [rubocop/rubocop#11538]
1.44.1 (using Parser 3.2.0.0, rubocop-ast 1.24.1, running on ruby 3.1.3) [x86_64-linux]
  - rubocop-performance 1.15.2
  - rubocop-rails 2.17.4

error message

$ bundle install

Fetching gem metadata from https://rubygems.org/.........
Could not find gem 'rubocop (~> 1.44.0)' with platform 'x86_64-linux' in rubygems repository https://rubygems.org/ or installed locally.

The source contains the following gems matching 'rubocop (~> 1.44.0)':
  * rubocop-1.44.0
  * rubocop-1.44.1

I confirmed that robocop is clearly written in the gem list. How can I solve this problem?

**Comment by drjeon92** [comment]
For beginners like me, this is an advisory answer.
I met this problem in docker environment and solved it through sudo command.
Perhaps it was a recommendation issue.

**Comment by drjeon92** [comment]
sorry. it wasn't resolved. Same error occurs.

**Comment by koic** [comment]
Probably not a Rubocop specific issue, this issue is about how to use Bundler. Please open an issue to Bundler instead.
https://github.com/rubygems/rubygems/issues

**Comment by drjeon92** [comment]
> Probably not a Rubocop specific issue, this issue is about how to use Bundler. Please open an issue to Bundler instead. https://github.com/rubygems/rubygems/issues

thx sir!
