### ISSUE TITLE
Regression: rubocop 1.45.0 crashes when we use rubocop-i18n

### ISSUE THREAD

**Issue by Tietew** [rubocop/rubocop#11549]
After upgrading rubocop 1.45.0, rubocop crashes:
``` console
$ bundle exec rubocop
NoMethodError: private method `begin_investigation' called for #<RuboCop::Cop::I18n::RailsI18n::DecorateStringFormattingUsingInterpolation:(...snip...)>
.../rubocop-1.45.0/lib/rubocop/cop/commissioner.rb:100:in `block in begin_investigation'
.../rubocop-1.45.0/lib/rubocop/cop/commissioner.rb:99:in `each'
.../rubocop-1.45.0/lib/rubocop/cop/commissioner.rb:99:in `begin_investigation'
...
```

This seems to be introduced at 3c9c49416c0fd3db077cec8410cb1280f6771dbb.

Before:
``` ruby
@cops.each { |cop| cop.send :begin_investigation, processed_source }
```
After:
``` ruby
@cops.each do |cop|
  cop.begin_investigation(processed_source, offset: offset, original: original)
end
```

`RuboCop::Cop::Base#begin_investigation` is moved to public section,
but `RuboCop::Cop::Cop#begin_investigation` is still in private section.
`rubocop-i18n`'s cops are extended from `RuboCop::Cop::Cop` instead of `Base`.

--------

## Expected behavior

Rubocop works with no errors.

## Actual behavior

Rubocop crashes.

## Steps to reproduce the problem

``` console
$ bundle init
$ bundle add rubocop rubocop-i18n
$ echo "require: [rubocop-i18n]" > .rubocop.yml
$ bundle exec rubocop
```

## RuboCop version

```
1.45.0 (using Parser 3.2.0.0, rubocop-ast 1.24.1, running on ruby 3.1.3) [x86_64-linux]
  - rubocop-i18n 1.12.0
```

**Comment by kerby82** [comment]
Same issue in our build/test pipeline. It's blocking our ability to merge code. Can be this fixed soon please?
