### ISSUE TITLE
Errors are usually caused by RuboCop bugs.

### ISSUE THREAD

**Issue by unimafy** [rubocop/rubocop#11593]
0.90.0 (using Parser 3.2.1.0, rubocop-ast 0.8.0, running on ruby 3.2.0 x86_64-darwin22)

**Comment by koic** [comment]
The latest RuboCop version is 1.45.1 with many bug fixes. Please upgrade to the latest RuboCop. Thank you.

**Comment by unimafy** [comment]
> 1.45.1

Thank you a lot. 🙏
