### ISSUE TITLE
Does sider no longer exist? If so perhaps we can remove from docs?

### ISSUE THREAD

**Issue by smcabrera** [rubocop/rubocop#11636]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/4121835/221633445-721e536b-1c64-43e8-90cc-c4d14a8fba86.png">

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/4121835/221633519-f5c897d6-2176-46aa-a3df-bb4b03d42a4d.png">

**Comment by koic** [comment]
Sider Review may have been migrated to [Sider Scan](https://siderscan.com/en/), but I'm not familiar with it. Anyway Sider Review seems to be over. I've fixed by https://github.com/rubocop/rubocop/commit/ff7c0040071f5c776e2932a587a1d9ca119de6a8.
