### ISSUE TITLE
Remove `require "set"` if TargetRubyVersion is 3.2 or higher

### ISSUE THREAD

**Issue by yahonda** [rubocop/rubocop#11656]
## Is your feature request related to a problem? Please describe.

Ruby 3.2 promotes `Set` as a built-in class. Starting from Ruby 3.2 `require "set"` is not needed anymore. 

https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
> Set is now available as a builtin class without the need for require "set". [[Feature #16989](https://bugs.ruby-lang.org/issues/16989)] It is currently autoloaded via the Set constant or a call to Enumerable#to_set.

## Describe the solution you'd like

If `TargetRubyVersion` is 3.2 or higher, I want a cop that detects `require "set"` and auto-corrects (removes) it.

## Describe alternatives you've considered
`git grep 'require "set"'` and remove these lines.

**Comment by koic** [comment]
This issue was solved by https://github.com/rubocop/rubocop/pull/11126 and already shipped.

**Comment by yahonda** [comment]
I have overlooked that one. Thanks for the info.
