### ISSUE TITLE
Layout/LineLength long string and array autocorrection?

### ISSUE THREAD

**Issue by broksonic21** [rubocop/rubocop#11680]
## Is your feature request related to a problem? Please describe.

Let's say you want a Layout/LineLength of 80 (or 120)

And you have a string like this

```
z = "This is a long string, it just keeps going and going. Ideally it would be broken into multiple lines automatically so I can lower my max line length, but unfortunately I need to manually break this and other strings myself into HereDocs or line continuation"
```

or an array like this:

```
r = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 33_333_333_333_333_333, 2_333_333_333, 233_333, 22_211, 2333, 333, 1, 2, 3,
     4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 33_333_333_333_333_333, 2_333_333_333, 233_333, 22_211, 2333, 333, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 33_333_333_333_333_333, 2_333_333_333, 233_333, 22_211, 2333, 333, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 33_333_333_333_333_333, 2_333_333_333, 233_333, 22_211, 2333, 333, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 33_333_333_333_333_333, 2_333_333_333, 233_333, 22_211, 2333, 333, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 33_333_333_333_333_333, 2_333_333_333, 233_333, 22_211, 2333, 333]
```

## Describe the solution you'd like

A cop (or update to Layout/LineLength) that can automatically split strings (HEREDOC? Line continuation?) where appropriate to avoid having to manually clean up so much when lowering the Layout/LineLength on an existing code base, as well as split and balance arrays automatically as well.

## Describe alternatives you've considered

Keeping length longer, or manually cleaning up, or disabling cop.

## Additional context

Not sure if this exists, and we just are missing a config, but our current Layout/LineLength isn't splitting for us, so I wanted to ask

**Comment by broksonic21** [comment]
Actually, I think there's a broader ability to update LineLength autocorrect. for example this file contains a long string and a long array, neither of which autocorrect.


```
# frozen_string_literal: true

z = 'This is a long string, it just keeps going and going. Ideally it would be broken into multiple lines automatically so I can lower my max line length, but unfortunately I need to manually break this and other strings myself into HereDocs or line continuation'

r = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 33_333_333_333_333_333, 2_333_333_333, 233_333, 22_211, 2333, 333, 1, 2, 3,
     4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 33_333_333_333_333_333, 2_333_333_333, 233_333, 22_211, 2333, 333, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 33_333_333_333_333_333, 2_333_333_333, 233_333, 22_211, 2333, 333, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 33_333_333_333_333_333, 2_333_333_333, 233_333, 22_211, 2333, 333, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 33_333_333_333_333_333, 2_333_333_333, 233_333, 22_211, 2333, 333, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 33_333_333_333_333_333, 2_333_333_333, 233_333, 22_211, 2333, 333]

puts z
puts r
```


fails three ways without autocorrect when all seem doable with a stock Rubocop install. (rubocop is only thing in Gemfile, no further .yml config)

Interesting, it did partially break the array on my first attempt, but then got stuck moving forward.

```
Inspecting 1 file
C

Offenses:

a.rb:3:121: C: Layout/LineLength: Line is too long. [263/120]
z = 'This is a long string, it just keeps going and going. Ideally it would be broken into multiple lines automatically so I can lower my max line length, but unfortunately I need to manually break this and other strings myself into HereDocs or line continuation'
                                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
a.rb:5:121: C: Layout/LineLength: Line is too long. [159/120]
r = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 33_333_333_333_333_333, 2_333_333_333, 233_333, 22_211, 2333, 333, 1, 2, 3,
                                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
a.rb:6:121: C: Layout/LineLength: Line is too long. [725/120]
     4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 33_333_333_333_333_333, 2_333_333_333, 233_333, 22_211, 2333, 333, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 33_333_333_333_333_333, 2_333_333_333, 233_333, 22_211, 2333, 333, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 33_333_333_333_333_333, 2_333_333_333, 233_333, 22_211, 2333, 333, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 33_333_333_333_333_333, 2_333_333_333, 233_333, 22_211, 2333, 333, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 33_333_333_333_333_333, 2_333_333_333, 233_333, 22_211, 2333, 333]
                                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 3 offenses detected
```

**Comment by dvandersluis** [comment]
Are you only running `Layout/LineLength`, or other cops too? Autocorrection for LineLength is not exhaustive but a long list of other cops are suggested when running autocorrect: https://docs.rubocop.org/rubocop/1.46/cops_layout.html#layoutlinelength

**Comment by broksonic21** [comment]
@dvandersluis I did this - stock config, all cops

https://github.com/broksonic21/sample-rubocop

The .sh file has the example of what I ran: https://github.com/broksonic21/sample-rubocop/blob/main/test-run.sh

Sample file that doesn't autocorrect in full: https://github.com/broksonic21/sample-rubocop/blob/main/test-split.rb

**Comment by broksonic21** [comment]
Turning on all listed in that doc (side note: it mentions Layout/* ones, but BlockDelimiters is Style, not Layout)

Does correct the arrays (albeit one-per-line, not balanced to fit the line length, which would make more sense)

but does not correct the strings.

**Comment by dvandersluis** [comment]
Thanks for the reproduction case.

Autocorrection doesn't operate on strings first off, only corrections that are guaranteed safe (ie. converting a long string to a heredoc could add whitespace).

For the things it can correct (arrays, hashes and method parameter lists), only the first line is currently corrected. I'm not sure yet if there's a historical reason for that (@bbatsov?)

Also, some of the cops suggested in the documentation are disabled by default FYI!

**Comment by broksonic21** [comment]
Thanks @dvandersluis for explaining. Long string to line continuation would be safe and make a huge difference, IMO

Be great to get the arrays cleaned up (and the doc)

**Comment by formigarafa** [comment]
So there is not an equivalent way to writing one long single line string that would make all the Cops happy. Ok.

Before anyone say we could do concatenation, heredocs or whatever: By equivalent I mean not adding extra operations like a multiline Array.

Man, I would love to just ignore the single line long strings.
