### ISSUE TITLE
Cop idea: Read ruby version from `.ruby-version` source in `Gemfile`

### ISSUE THREAD

**Issue by anthony-robin** [rubocop/rubocop#11744]
## Is your feature request related to a problem? Please describe.

Currently, the Ruby version for a project is duplicated twice which is not very practical when a Ruby update is necessary as it has to be modified in both places:

- once in the `Gemfile`

  ```ruby
  # Gemfile

  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  ruby "3.1.1"

  # ...
  ```

- once in `.ruby-version`

  ```
  3.1.1
  ```

## Describe the solution you'd like

It could be great to have a cop that detects it and replace the `Gemfile` line reading it from `.ruby-version` (the cop should automatically autocorrect it as well)

```ruby
# Gemfile

ruby File.read('.ruby-version').strip
```

## Describe alternatives you've considered

/

## Additional context

What do you think about this cop ? Do you see any reason to not make a cop that detect this behavior ?
(sorry if there was already discussions about this, I didn't find any of them in the repo, feel free to close if this subject is not relevant)

Thank you :)

**Comment by koic** [comment]
I'm not sure if this makes sense, for the following reasons:

- Case where tools with formats different from .ruby-version such as `asdf` are used
- Case where Docker images are used and .ruby-version is not used
- Case where specification on Heroku is required, but development is not dependent on .ruby-version

I think it's not a suitable enforcement rule for the above cases. In other words, I'm wondering if it should not be supported in the RuboCop core as a general purpose rule, as this feature request seems to be specific to an application development environment.

**Comment by anthony-robin** [comment]
Thank you for the explanation @koic !

Indeed, there are too many edge cases to make it an enforcement rule 👍
