### ISSUE TITLE
Split CHANGELOG?

### ISSUE THREAD

**Issue by vlad-pisanov** [rubocop/rubocop#11763]
The CHANGELOG has gotten so big that Github has trouble loading and rendering it. Perhaps old entries could be extracted to another file?

![image](https://user-images.githubusercontent.com/55465196/229954213-f06cb66a-2464-46d9-94e0-8174e1c045d4.png)

**Comment by valscion** [comment]
I have opened a discussion about this and #12175 to GitHub community discussions: https://github.com/orgs/community/discussions/65658
