### ISSUE TITLE
Infinite loop Layout/SpaceAfterSemicolon -> Layout/SpaceInsideStringInterpolation

### ISSUE THREAD

**Issue by MaxLap** [rubocop/rubocop#11861]
With this code:

```ruby
"spam#{foo;}"
```

Running `rubocop -a the_file.rb`

Generates an Infinite loop error:

```
Infinite loop detected in the_file.rb and caused by Layout/SpaceAfterSemicolon -> Layout/SpaceInsideStringInterpolation
```

The error also happens when using `-A`.

## Expected behavior

No infinite loop. I would probably expect rubocop to get rid of that semicolon, but that's a bonus. 😄 

## Steps to reproduce the problem

Explained in intro

## RuboCop version

```
rubocop -V
1.50.2 (using Parser 3.2.2.1, rubocop-ast 1.28.0, running on ruby 2.6.6) [x86_64-linux]
```

**Comment by koic** [comment]
> I would probably expect rubocop to get rid of that semicolon, but that's a bonus. 😄

FYI, I opened https://github.com/rubocop/rubocop/pull/11866 to implement the enhancement request :-)

**Comment by MaxLap** [comment]
Nice, it's always amazing to submit issues to RuboCop. Thank you!
