### ISSUE TITLE
cannot load such file -- rubocop-performance

### ISSUE THREAD

**Issue by olegantonyan** [rubocop/rubocop#11894]
I'm trying to use rubocop-performance in a new project:

```
# .rubocop.yml
require:
- rubocop-rake
- rubocop-rails
- rubocop-performance
```

```
# Gemfile
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rake', require: false
```

## Expected behavior

bundle exec rubocop runs succesfully 

## Actual behavior

```
$ bundle exec rubocop --debug
For /home/oleg/projects/omnipackage/omnipackage-web: configuration from /home/oleg/projects/omnipackage/omnipackage-web/.rubocop.yml
cannot load such file -- rubocop-performance
/home/oleg/.rbenv/versions/3.3.0-preview1/lib64/ruby/gems/3.3.0+0/gems/rubocop-1.51.0/lib/rubocop/feature_loader.rb:46:in `rescue in rescue in load'
/home/oleg/.rbenv/versions/3.3.0-preview1/lib64/ruby/gems/3.3.0+0/gems/rubocop-1.51.0/lib/rubocop/feature_loader.rb:39:in `rescue in load'
/home/oleg/.rbenv/versions/3.3.0-preview1/lib64/ruby/gems/3.3.0+0/gems/rubocop-1.51.0/lib/rubocop/feature_loader.rb:32:in `load'
/home/oleg/.rbenv/versions/3.3.0-preview1/lib64/ruby/gems/3.3.0+0/gems/rubocop-1.51.0/lib/rubocop/feature_loader.rb:21:in `load'
```

## Steps to reproduce the problem

Uncomment rubocop-performance in  .rubocop.yml here: https://github.com/olegantonyan/omnipackage-web and try running rubocop in that project.

In rails console:
```
$ be rails c
Loading development environment (Rails 7.1.0.alpha)
[1] pry(main)> require 'rubocop-performance'
=> true
```

## RuboCop version

```
1.51.0 (using Parser 3.2.2.1, rubocop-ast 1.28.1, running on ruby 3.3.0) +server [x86_64-linux]
  - rubocop-rails 2.19.1
  - rubocop-rake 0.6.0
```

Leaving rubocop-performance enabled results in the same error when running rubocop -V. Switching Ruby versions makes no difference

**Comment by fatkodima** [comment]
Can not reproduce on Mac using ruby 3.2.0.

**Comment by olegantonyan** [comment]
Strange. I tried the same project both cloned and just copied to another location and it worked. 
Originaly it lives in `~/projects/omnipackage/omnipackage-web` on my pc and at this location rubocop fails, but merely `cp -R omnipackage-web omnipackage-web1` and suddenly rubocop works with rubocop-performance

**Comment by olegantonyan** [comment]
Ok, so I made a naive debugging mistake - 2 changes at once and it helped, so not sure which one actually did the trick:
1) remove the original project dir and clone a new one into the same location
2) rm -rf ~/.cache/rubocop_cache
