### ISSUE TITLE
require_relative with "same folder" prefix "./"

### ISSUE THREAD

**Issue by bquorning** [rubocop/rubocop#11924]
## Is your feature request related to a problem? Please describe.

I sometimes see people use e.g. `require_relative "./foo"` where the shorter, cleaner `require_relative "foo"` would suffice. The same goes for e/g/ `require_relative "./foo/bar/baz"` vs `require_relative "foo/bar/baz"`. I see no reason for ever using the `./` prefix when calling `require_relative`.

## Describe the solution you'd like

I think we should have a cop that disallows the `./` prefix (but of course allows `../`) on `require_relative`.

## Describe alternatives you've considered

—

## Additional context

The `./` prefix has its merit when calling shell commands, and you want to distinguish e.g. `./rubocop` from a `rubocop` found in your `$PATH`.

In Ruby we have `require` finding code in `$LOAD_PATH`, whereas `require_relative` only loads code in a path relative to the requiring file’s path. The `./` is superfluous.

**Comment by ixti** [comment]
I believe this cop should be configurable with `EnforcedStyle: implicit|explicit`. Especially that `rescue` is an implicit version of `rescue StandardError` and the default for the `Style/RescueStandardError` cop to be explicit.
