### ISSUE TITLE
Lint/RedundantSafeNavigation is not safe to correct for .to_i

### ISSUE THREAD

**Issue by jcoyne** [rubocop/rubocop#11929]
Autocorrect for Lint/RedundantSafeNavigation changes the behavior of the code when the value is nil. 

This code before autocorrect:
```ruby
nillable = nil
nil&.to_i
# =>  nil
```

And after autocorrect
```ruby
nillable = nil
nil.to_i
# =>  0
```

**Comment by koic** [comment]
This issue is a dup with #11927 and resolved by https://github.com/rubocop/rubocop/pull/11915.
