### ISSUE TITLE
Style/AccessorSorting?

### ISSUE THREAD

**Issue by broksonic21** [rubocop/rubocop#11934]
## Is your feature request related to a problem? Please describe.

We just turned on Style/AccessorGrouping, and was wondering if there's a cop to enforce/ensure sort order for the accessors as well. 

## Describe the solution you'd like

Consistent alphabetical accessors.

## Describe alternatives you've considered

Writing our own or manual cleanup

## Additional context

```
 attr_reader :start_time
 attr_reader :end_time
 attr_reader :base_name
```

be nice if that was automatically formatted to (in separated mode)

```
 attr_reader :base_name
 attr_reader :end_time
 attr_reader :start_time
```

**Comment by koic** [comment]
Given the importance of respecting the context that arranges attributes in order of importance, even if this cop will be provided, it should be disabled by default.

**Comment by broksonic21** [comment]
closing older ticket, no longer need this one
