### ISSUE TITLE
Style/EmptyLiteral with --enable=frozen-string-literal flag

### ISSUE THREAD

**Issue by khiav223577** [rubocop/rubocop#11977]
## Expected behavior

`String.new` should not be auto-corrected with `''` when have `Style/EmptyLiteral` enabled and run with the `--enable=frozen-string-literal` flag.

## Actual behavior

`String.new` will be replaced with `''`

## Steps to reproduce the problem

1. add a ruby file with a line `String.new`.
2. run `export RUBYOPT="--enable-frozen-string-literal"` in command line.
3. run auto-correct on the ruby file.
4. `String.new` will be replaced with `''`

## RuboCop version

```
$ [bundle exec] rubocop -V
1.53.0 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.0.0) [x86_64-linux]
  - rubocop-performance 1.15.0
  - rubocop-rails 2.16.1
```

## Possible fixes:

We can check `RUBYOPT` in `frozen_string_literals_enabled?` method.
Ex:
```rb
return true if ENV['RUBYOPT'].include?('--enable-frozen-string-literal')
```
https://github.com/rubocop/rubocop/blob/a7b7c5f95ac32612b0f9c0a9661281b5633ae07b/lib/rubocop/cop/mixin/frozen_string_literal.rb#L21-L41

**Comment by koic** [comment]
Hhm, environment variables given to `ruby` command are for runtime information, so I wonder about their use in static analysis.

**Comment by khiav223577** [comment]
How about adding an option for rubocop to know that `frozen_string_literals` is always enabled in this project, so that `String.new` will never be replaced with `''` while `Hash.new` will still be replaced with `{}`

**Comment by Earlopain** [comment]
You can use AllCops/StringLiteralsFrozenByDefault: true` in the next RuboCop` version for this.
