### ISSUE TITLE
LSP server --fix-layout

### ISSUE THREAD

**Issue by tradiff** [rubocop/rubocop#12044]
As a frequent saver, I really like the LSP correcting my indenting and whitespace. But I would prefer it to not do things like rename unused parameters while I'm still working on a method. I would like to run the new built-in LSP and use it to auto-format only layout cops. This would be the equivalent of the `--fix-layout` (aka `-x`) when running rubocop from the command line. When using solargraph + rubocop, I had solargraph configured to send `-x` to rubocop to get the behavior I prefer. 

I saw that there is a `safeAutocorrect` option. Can we have fixLayout also?

BTW thanks for the LSP! It's noticeably faster at format on save compared to solargraph + rubocop.

**Comment by koic** [comment]
Yeah, this feature request aligns perfectly with what I'm looking to extend on the LSP. I wasn't certain if this feature would be demanded, but your use case has given me the confidence to proceed! Thank you!

**Comment by koic** [comment]
FYI, vscode-rubocop 0.4.0 has been released for the option.

- https://github.com/rubocop/vscode-rubocop/releases/tag/v0.4.0
- https://github.com/rubocop/vscode-rubocop#rubocoplayoutmode
