### ISSUE TITLE
Consider testing against YARP's fixtures

### ISSUE THREAD

**Issue by andyw8** [rubocop/rubocop#12085]
## Is your feature request related to a problem? Please describe.

Writing cops which work against all possible Ruby syntax variations can be difficult. In particulary, newly added a cops often need fixes once they are enabled on real world codebases.

## Describe the solution you'd like

The YARP project contains a large collection of fixtures which may be useful to test against:

https://github.com/ruby/yarp/tree/main/test/fixtures

Running it against the latest RuboCop shows one failure currently:

```
An error occurred while Lint/SuppressedException cop was inspecting /Users/andyw8/src/github.com/Shopify/yarp/test/fixtures/rescue.rb:26:34.
```

The YARP fixtures could be added as a submodule.

## Describe alternatives you've considered

n/a

## Additional context

I initially thought this may have prevented https://github.com/rubocop/rubocop/issues/12079 but there's no fixture in YARP for that currently. I still believe it could be useful to test against though.

**Comment by koic** [comment]
That's an interesting idea, but its implementation needs to be considered. In the meantime, I opened #12086 to prevent the `Lint/SuppressedException`'s error.

**Comment by andyw8** [comment]
@koic Since https://github.com/rubocop/rubocop/pull/12086 only fixes the example mentioned in the description rather than the idea itself, should this be kept open?
