### ISSUE TITLE
Use of Whitelist as a config key

### ISSUE THREAD

**Issue by hemalvarambhia** [rubocop/rubocop#12090]
## Is your feature request related to a problem? Please describe.

The use of the word `Whitelist` in Rubocop configs goes against diversity, equity and inclusion.

## Describe the solution you'd like

It be removed (I could guess this would be a breaking change), or guidance on what existing solution exists that is a more inclusive alternative e.g. `AllowedList`.

## Describe alternatives you've considered

I am unaware of any alternative right now hence my request for guidance on an alternative as well as a change request.

## Additional context

Unsure of what additional context I can provide.

**Comment by koic** [comment]
RuboCop itself has already been updated:
https://github.com/rubocop/rubocop/pull/7469

`Naming/InclusiveLanguage` is provided to detect them:
https://docs.rubocop.org/rubocop/1.55/cops_naming.html#naminginclusivelanguage
