### ISSUE TITLE
After update to rubocop 1.56: "An error occurred while Style/ArgumentsForwarding cop was inspecting file_path."

### ISSUE THREAD

**Issue by JasmienVC** [rubocop/rubocop#12131]
Rubocop (Style/ArgumentsForwarding cop) fails due to encountering an error while inspecting one of the methods in our codebase.

## Expected behavior

Rubocop passes or allows disabling of Style/ArgumentsForwarding cop.

## Actual behavior

Rubocop fails and disabling Style/argumentsForwarding cop does not resolve the error (there are no offenses found, I just get an extra offense stating an unnecessary disabling and still get the error as well).

1 error occurred:
An error occurred while Style/ArgumentsForwarding cop was inspecting /app/app/helpers/icons_helper.rb:5:2

## Steps to reproduce the problem => method that throws the error

`def custom_heroicon(icon, **opts, &blk)
    if REPLACEMENTS.include?(icon.to_s)
      render "heroicons_replacements/#{icon}", **opts, &blk
    else
      heroicon icon, **opts, &blk
    end
  end`

## RuboCop version

1.56.0 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.0.5) [aarch64-linux]

**Comment by ydah** [comment]
Maybe, following PRs solve the problem. Please wait for the next release.
- https://github.com/rubocop/rubocop/pull/12110
