### ISSUE TITLE
Installation instructions don't work

### ISSUE THREAD

**Issue by xobs** [rubocop/rubocop#12130]
I'm trying to format some Ruby code. I do not know anything about Ruby, and the code I'm looking at isn't properly formatted, so I'd like to run it through a formatter.

According to the website, I can install Rubocop by running:

```
$ gem install rubocop
```

However, this does not work as described.

--------

## Expected behavior

RuboCop should be installed, as indicated on the website. Similar to how `npm iinstall` or `cargo install` causes the program to be installed in a place that can be run.

## Actual behavior

```
$ gem install rubocop
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
$
```

## Steps to reproduce the problem

1. Run `gem install rubocop` as directed on the site

## RuboCop version

Unknown

**Comment by koic** [comment]
This looks like a RubyGems error, not a RuboCop issue. If you search the RubyGems discussions and can't find it, open a discussions:
https://github.com/rubygems/rubygems/discussions?discussions_q=is%3Aopen+label%3ARubyGems
