### ISSUE TITLE
Changelog is so large that GitHub no longer renders it

### ISSUE THREAD

**Issue by valscion** [rubocop/rubocop#12175]
## Is your feature request related to a problem? Please describe.

It seems that the CHANGELOG.md file is nowadays so large that GitHub is having troubles rendering it.

## Describe the solution you'd like

Changelog entries before 1.0 release could be separated to a different file so that the changelog itself would be smaller and thus allow GitHub to render it.

## Describe alternatives you've considered

Changelog entries before 1.0 release could also be removed as they could be recollected from git history if someone would so want to.

## Additional context

This is how viewing the [CHANGELOG.md file at `master` branch](https://github.com/rubocop/rubocop/blob/master/CHANGELOG.md) looks like in GitHub to me:

<img width="558" alt="rubocop__at_master_·_rubocop_rubocop" src="https://github.com/rubocop/rubocop/assets/482561/e1c9b111-9724-4262-8aad-6c4d7342a1bf">

**Comment by koic** [comment]
I mentioned this in https://github.com/rubocop/rubocop/issues/11763. So I think this might be worth raising as a GitHub issue. It's probably better to open feedback on GitHub first if you'd like. Thank you.

**Comment by valscion** [comment]
Thanks! Sorry for not spotting the duplicate issue.
