### ISSUE TITLE
Style/EmptyCaseCondition creates syntax error on autocorrect when following a return

### ISSUE THREAD

**Issue by marvinthepa** [rubocop/rubocop#12172]
## Expected behavior

I don't know. Certainly rubocop corrections should not lead to syntax errors.

## Actual behavior

```ruby
def foo(bar)
  return case
         when bar == 1
           2
         when bar != 12
           3
         else
           4
         end
end
```

is corrected to

```ruby
def foo(bar)
  return if bar == 1
           2
         elsif bar != 12
           3
         else
           4
         end
end
```

which is a syntax error, as the "return if bar == 1" is parsed as a postfix if.

## Steps to reproduce the problem

see above

## RuboCop version

```
$ [bundle exec] rubocop -V
1.42.0 (using Parser 3.1.3.0, rubocop-ast 1.24.1, running on ruby 3.1.3) +server [x86_64-linux] 
```

**Comment by mheguy-stingray** [comment]
I was about to create a ticket for exactly this issue. Amazing to see that it's being worked on so quickly! Thank you. :)

**Comment by marvinthepa** [comment]
@koic I think that some fixes that convert ternary to if statements have a similar issue. Do you want me to create an issue for that as well? I think I can quickly provide a simple test case.

**Comment by koic** [comment]
@marvinthepa Thank you! Please open an issue if you like! 😃
