### ISSUE TITLE
Additional Option for Cyclomatic Complexity

### ISSUE THREAD

**Issue by jasonmk** [rubocop/rubocop#1220]
I'd like to see an option for Cyclomatic Complexity that allows me to ignore 'when' statements when computing the complexity of a method.  Basically, any method with a case statement is virtually guaranteed to exceed the Complexity limit.  If I only had 1 or two possible conditions, I'd probably be using if/elsif/else anyways.  Case statements are great for a method that branches off into a number of different paths, but that doesn't make it inherently complex.

**Comment by dpashk-figma** [comment]
Just want to add my two cents. While it's true that the classic cyclomatic complexity is a strict metric of testability, practical applications have led to the creation of its variant, _modified complexity_.

_Modified cyclomatic complexity_ is almost exactly the same as the classic [cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity), except that a switch statement only increases the value by 1 regardless of how many case statements it contains. 

A number of other code analysis tools implement this metric. See:
* https://github.com/terryyin/lizard?tab=readme-ov-file#options (`-m, --modified ` option)
* [Understand](https://support.scitools.com/support/solutions/articles/70000582297-understanding-mccabe-cyclomatic-complexity)
* [Matlab's checkcode](https://www.mathworks.com/help/matlab/matlab_prog/measure-code-complexity-using-cyclomatic-complexity.html)
* [CodeSonar](https://codesecure.com/learn/code-complexity/)

Given that it's common enough in the industry, I propose that you still consider adding an option to the existing cyclomatic complexity rule, or accepting a PR for a separate Modified Complexity rule (it'll probably just inherit from the existing Cyclomatic Complexity rule). Note that this is still different from the PerceivedComplexity rule that now exists.

I'd be happy to make a contribution either way. What do you think?

**Comment by dpashk-figma** [comment]
I ended up forking the cop and modifying it to count the whole case statement as "1" towards the complexity score. The modification is simple: just replace `when` and `in_pattern` in `COUNTED_NODES` with `case` and `case_match` (and update the tests accordingly).

https://github.com/rubocop/rubocop/blob/7aa3a48e59e53a73e1ee2171e4f4e458c0c50dcd/lib/rubocop/cop/metrics/cyclomatic_complexity.rb#L40-L41

Leaving this here for anyone needing this. Happy to contribute upstream behind a new cop option, if you'll accept.

P.S. `case_match`/`in_pattern` are nodes for the new case/in block in Ruby that implements [pattern matching](https://docs.ruby-lang.org/en/3.0/syntax/pattern_matching_rdoc.html).
