### ISSUE TITLE
Sponsored issue: Cop Idea: Enhancing Code Readability by Flagging Explicit Usage Of Public Access Modifiers

### ISSUE THREAD

**Issue by PhillipUg** [rubocop/rubocop#12209]
### Problem Description:
The issue highlights a concern regarding the explicit usage of the public access modifier within a class definition. This usage might be surprising for developers accustomed to placing private methods at the bottom of a class.

```ruby
class ExampleClass
  def some_method
    # ...
  end

  private

  def private_method
    # ...
  end

  public # This usage might be unexpected for developers

  def public_method
    # ...
  end

  # Any method added here will be public
end
```
### Proposed Solution:
The suggested solution is to implement a cop that will flag the explicit usage of the public access modifier. This would help maintain code clarity and prevent potential confusion for developers.

### Alternative Considerations:
While the Layout/ClassStructure cop may cover this issue to some extent, it's not explicitly specified in its specifications. Disabling Layout/ClassStructure might be an alternative approach, but it may not fully address the underlying concern.

It's important to note that the purpose of this proposed cop is to completely restrict the potentially confusing usage, rather than simply rearranging the methods.

### Additional Context:
The concern raised in this issue emphasizes the need for codebase consistency and clarity. By flagging explicit public access modifiers, developers can avoid potential misunderstandings and adhere to established best practices.

This issue aims to enhance the readability and maintainability of Ruby code, ultimately contributing to a more robust and comprehensible codebase.

## Priority Support

- @phillipug is using  [Mintycode](https://mintycode.io) to fund this issue.
- If you would like to accept ![amount](https://imageupload.io/ib/zwkd2EaAY6YpPsg_1693209112.png) bounty for solving this issue join [Mintycode](https://mintycode.io/profile?action=CREATOR_SUPPORT_MODAL&requestId=ff8d50b1-1721-40f9-b8ec-a2c18f25d2aa&owner=rubocop&name=rubocop).
- Thank you in advance for helping.

[![mintycode](https://imageupload.io/ib/LvxMwrPxam1JW9e_1693210482.png)](https://mintycode.io)

**Comment by koic** [comment]
This feature request is a dup with #11957.
