### ISSUE TITLE
Rubocop 1.56.3 consuming high CPU and memory on CircleCI

### ISSUE THREAD

**Issue by akhilgkrishnan** [rubocop/rubocop#12225]
We recently upgraded our RuboCop version from 1.42.0 to 1.56.3, and following the upgrade, we observed occasional crashes in our CircleCI environment, characterized by high CPU and memory usage.

With the previous RuboCop version, everything was running smoothly without any such issues. In our CircleCI configuration, we have been utilizing resource_class: small to allocate resources.

## Expected behavior

We anticipate that the CircleCI RuboCop tests should execute successfully without encountering any problems.

## Actual behavior

![Screenshot 2023-09-28 at 6 53 50 PM](https://github.com/rubocop/rubocop/assets/22231095/9f6ad91e-6929-4f82-b428-8f9f96df1eb0)

## RuboCop version

1.56.3

**Comment by fatkodima** [comment]
It is hard to tell what is wrong.

1. Is upgrading rubocop version the only thing you did before observing the mentioned errors?
2. Do you see the same behavior when running locally?
3. Can you profile rubocop on CircleCI (see https://github.com/rubocop/rubocop/pull/11396)?

**Comment by koic** [comment]
I will close this issue due to the lack of sufficient information for analysis. Please feel free to reopen it once you have gathered information to analyze the problem. Thank you.

**Comment by letrungkien** [comment]
For those who have the same issue. Here's how to fix it:
```
PARALLEL_PROCESSOR_COUNT=2 bundle exec rubocop --config .rubocop.yml --parallel
```
by adding `PARALLEL_PROCESSOR_COUNT`.
ref from Parallel gem: https://github.com/grosser/parallel/blob/f66f10552e32681bf47f7dfd2f8183d7e0de442e/lib/parallel.rb#L347

In circleci, I checked that it returned 36 processors (???). That's why CircleCI runner couldn't handle and kill the rubocop command because of OOO
```
Etc.nprocessors
36
```
