### ISSUE TITLE
Improve `Style/SlicingWithRange` cop

### ISSUE THREAD

**Issue by ydakuka** [rubocop/rubocop#12233]
## Describe the solution you'd like

Required Ruby version: 2.7

https://github.com/rubocop/rubocop/blob/master/docs/modules/ROOT/pages/cops_style.adoc#styleslicingwithrange

https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/

```ruby
module ApplicationHelper
  # bad
  def my_method
    arr[0..n]
  end

  # good
  def my_method
    arr[..n]
  end
end
```

## Rubocop

```bash
ydakuka@yauhenid:~/Work/project$ bin/rails_docker rubocop -V
1.56.4 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 2.7.8) [x86_64-linux]
  - rubocop-capybara 2.19.0
  - rubocop-factory_bot 2.24.0
  - rubocop-performance 1.19.1
  - rubocop-rails 2.21.1
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.24.0
  - rubocop-thread_safety 0.5.1
```

**Comment by djberg96** [comment]
The fact that Ruby even parses that syntax surprises me. I will never use that syntax, puke.
