### ISSUE TITLE
Cop idea: `Style/AllowModifiersOnAttrs`

### ISSUE THREAD

**Issue by ntkme** [rubocop/rubocop#12242]
## Is your feature request related to a problem? Please describe.

In Ruby >=3.0, we can write the modifier and `attr_*` helpers inline like:

``` ruby
class Foo
  public attr_accessor :a
  protected attr_reader :b
  protected attr_writer :c
  private attr :d, true
end
```

Today, this is an offend on `Style/AccessModifierDeclarations`. However, just for `attr*` helpers this style looks much cleaner than the default group style.

## Describe the solution you'd like

After all the default `group` style of `Style/AccessModifierDeclarations` works well for normal `def` methods, that I don't want to change that to `inline` style. Therefore I think the best approach is to add a new option called `Style/AllowModifiersOnAttrs` similar to `Style/AllowModifiersOnSymbols` to allow inlined modifier on `attr*` methods.

## Describe alternatives you've considered

Use the group style everywhere - the problem is that I think most of the developers would prefer to put the attr declarations together, and then normal methods together, in that case we need to toggle public and private back and forth like below: 

``` ruby
class Foo
  attr_accessor :a

  private

  attr_accessor :b

  public # <-- extra "public" to toggle group back and forth

  def c; end

  private

  def d; end
  def e; end
end
```

Use the inline style everywhere, the problem would be simply we don't want to add the modifier to each normal method.

``` ruby
class Foo
  attr_accessor :a
  private attr_accessor :b

  def c; end
  private def d; end 
  private def e; end
  private def f; end
end
```

With a `Style/AllowModifiersOnAttrs` rule similar to `Style/AllowModifiersOnSymbols`, we would be able to write:

``` ruby
class Foo
  attr_accessor :a
  private attr_accessor :b

  def c; end

  private

  def d; end
  def e; end
  def f; end
end
```

**Comment by DIEGOHJJACOBO** [comment]
$ [bundle exec] rubocop -V
1.56.4 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.2.2) [x86_64-linux]
  - rubocop-performance 1.18.0
  - rubocop-rspec 2.23.2

**Comment by DIEGOHJJACOBO** [comment]
> ## Is your feature request related to a problem? Please describe.
> In Ruby >=3.0, we can write the modifier and `attr_*` helpers inline like:
> 
> ```ruby
> class Foo
>   public attr_accessor :a
>   protected attr_reader :b
>   protected attr_writer :c
>   private attr :d, true
> end
> ```
> 
> Today, this is an offend on `Style/AccessModifierDeclarations`. However, just for `attr*` helpers this style looks much cleaner than the default group style.
> 
> ## Describe the solution you'd like
> After all the default `group` style of `Style/AccessModifierDeclarations` works well for normal `def` methods, that I don't want to change that to `inline` style. Therefore I think the best approach is to add a new option called `Style/AllowModifiersOnAttrs` similar to `Style/AllowModifiersOnSymbols` to allow inlined modifier on `attr*` methods.
> 
> ## Describe alternatives you've considered
> Use the group style everywhere - the problem is that I think most of the developers would prefer to put the attr declarations together, and then normal methods together, in that case we need to toggle public and private back and forth like below:
> 
> ```ruby
> class Foo
>   attr_accessor :a
> 
>   private
> 
>   attr_accessor :b
> 
>   public # <-- extra "public" to toggle group back and forth
> 
>   def c; end
> 
>   private
> 
>   def d; end
>   def e; end
> end
> ```
> 
> Use the inline style everywhere, the problem would be simply we don't want to add the modifier to each normal method.
> 
> ```ruby
> class Foo
>   attr_accessor :a
>   private attr_accessor :b
> 
>   def c; end
>   private def d; end 
>   private def e; end
>   private def f; end
> end
> ```
> 
> With a `Style/AllowModifiersOnAttrs` rule similar to `Style/AllowModifiersOnSymbols`, we would be able to write:
> 
> ```ruby
> class Foo
>   attr_accessor :a
>   private attr_accessor :b
> 
>   def c; end
> 
>   private
> 
>   def d; end
>   def e; end
>   def f; end
> end
> ```
> https://github.com/rubocop/rubocop/issues/12242#issue-1924807554
> ## Additional context
