### ISSUE TITLE
Tempfile closing and unlinking

### ISSUE THREAD

**Issue by Alagaesia93** [rubocop/rubocop#12328]
## Is your feature request related to a problem? Please describe.

I was today years old when I found out that Tempfile are supposed to be unlinked and closed for the GC to free the memory. I had a huge spike in memory and took me hours of investigations

## Describe the solution you'd like

whenever using a Tempfile, raise a Rubocop error if it's not unlinked and closed - something similar to what happens when calling Kernel.open

## Describe alternatives you've considered

I have not considered any, tbh

## Additional context

I'm more than happy to help with a PR, but I don't know where to start and I don't have enough time in the next few weeks

**Comment by Alagaesia93** [comment]
Thank @fatkodima, that was exactly my concern. I'm not super experienced in Rubocop, so I have no idea how to check that a Tempfile is created and never closed. It could be in the same metod, or another method, or somewhere else. Is that possible with Rubocop?

**Comment by fatkodima** [comment]
> Is that possible with Rubocop?

No, because rubocop is a static code analyzer and does not run the user's code. The best it can do, as seen in the mentioned cop, is checking that `File.open` with block is used.

**Comment by fatkodima** [comment]
Actually you can check that the file is closed in the same method, but this is a perfect case for calling `open` with a block.

**Comment by koic** [comment]
I opened #12330 and also refactored it to tweak some redundant logic.
