### ISSUE TITLE
Detect extra/unnecessary whitespace in method call argument list

### ISSUE THREAD

**Issue by orhantoy** [rubocop/rubocop#12327]
## Is your feature request related to a problem? Please describe.

Detect extra/unnecessary whitespace in method call argument list.

## Describe the solution you'd like

```ruby
# bad
hey a,                  b
hey(a,                  b)

# good
hey a, b
hey(a, b)
```

## Describe alternatives you've considered

I couldn't find an existing configuration for this but it might already exist?
`Layout/ExtraSpacing` seems related but it's not detecting the examples ^

**Comment by ydakuka** [comment]
This has good uses too.

```ruby
# good
hey(12345,      true, var2,  20_000_000, var3)
hey(10_000_000, var1, false, 6789,       var3)

# bad
hey(12345, true, var2, 20_000_000, var3)
hey(10_000_000, var1, false, 6789, var3)
```

**Comment by koic** [comment]
You can change the behavior with the following configuration:

```yaml
Layout/ExtraSpacing:
  AllowForAlignment: false
```
