### ISSUE TITLE
Cop idea: Prefer `#flat_map` over `flatten(1)`

### ISSUE THREAD

**Issue by ydakuka** [rubocop/rubocop#12335]
## Description

Use `flat_map` instead of `map + flatten`. This does not apply for arrays with a depth greater than 2, i.e. if `users.first.songs == ['a', ['b','c']]`, then use `map + flatten` rather than `flat_map`. `flat_map` flattens the array by 1, whereas flatten flattens it all the way.

https://rubystyle.guide/#flat-map

## Behavior

```ruby
# bad
users.map(&:songs).flatten(1)

# good
users.flat_map(&:songs)
```

**Comment by fatkodima** [comment]
There is a `Performance/FlatMap` cop for this in `rubocop-performance` gem.

**Comment by ydakuka** [comment]
Agree, my bad.
