### ISSUE TITLE
Cop idea: reverse_each

### ISSUE THREAD

**Issue by ydakuka** [rubocop/rubocop#12349]
## Description

Prefer `reverse_each` to `reverse.each` because some classes that `include Enumerable` will provide an efficient implementation. Even in the worst case where a class does not provide a specialized implementation, the general implementation inherited from `Enumerable` will be at least as efficient as using `reverse.each`.

https://rubystyle.guide/#reverse-each

## Describe the solution you'd like

```ruby
# bad
array.reverse.each { ... }

# good
array.reverse_each { ... }
```

**Comment by fatkodima** [comment]
Can you please do a check in the future for the existence of cops? 
https://github.com/rubocop/rubocop-performance/blob/master/lib/rubocop/cop/performance/reverse_each.rb

**Comment by ydakuka** [comment]
> Can you please do a check in the future for the existence of cops?

Yes, of course. I've done such checks before publication. Please look, I checked it again. Unfortunately, I checked as in 1 case.

1.

```ruby
def my_method
  result = [1, 2, 3].reverse.each { |x| puts(x) }

  [result]
end
```

```bash
ydakuka@yauhenid:~/Work/project$ bin/rails_docker rubocop app/models/test.rb 
Inspecting 1 file
.

1 file inspected, no offenses detected
```

2.

```ruby
def my_method
  [1, 2, 3].reverse.each { |x| puts(x) }
end
```

```bash
ydakuka@yauhenid:~/Work/project$ bin/rails_docker rubocop app/models/test.rb 
Inspecting 1 file
C

Offenses:

app/models/test.rb:5:15: C: [Correctable] Performance/ReverseEach: Use reverse_each instead of reverse.each.
    [1, 2, 3].reverse.each { |x| puts(x) }
              ^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense autocorrectable
```

**Comment by fatkodima** [comment]
For the first example, see https://github.com/rubocop/rubocop-performance/issues/36 why is it ignored.

**Comment by ydakuka** [comment]
I see, thanks for the explanation.
