### ISSUE TITLE
Cop idea: Use Hash Blocks

### ISSUE THREAD

**Issue by ydakuka** [rubocop/rubocop#12340]
## Description

Prefer the use of the block instead of the default value in `Hash#fetch` if the code that has to be evaluated may have side effects or be expensive.

https://rubystyle.guide/#use-hash-blocks

## Behavior

```ruby
batman = { name: 'Bruce Wayne' }

# bad - if we use the default value, we eager evaluate it
# so it can slow the program down if done multiple times
batman.fetch(:powers, obtain_batman_powers) # obtain_batman_powers is an expensive call

# good - blocks are lazy evaluated, so only triggered in case of KeyError exception
batman.fetch(:powers) { obtain_batman_powers }
```

**Comment by fatkodima** [comment]
I don't think this should be implemented as a cop, because there is no way we can know if we deal with an expensive operation or not. This rule is just a general recommendation.

There is a cop `Style/RedundantFetchBlock` that warns regarding the use of blocks where it is clearly not needed.

**Comment by koic** [comment]
I agree with @fatkodima.
