### ISSUE TITLE
Cop idea: Using Exceptions for Flow of Control

### ISSUE THREAD

**Issue by ydakuka** [rubocop/rubocop#12356]
## Description

Don’t use exceptions for flow of control.

https://rubystyle.guide/#no-exceptional-flows

## Describe the solution you'd like

```ruby
# bad
begin
  n / d
rescue ZeroDivisionError
  puts 'Cannot divide by 0!'
end

# good
if d.zero?
  puts 'Cannot divide by 0!'
else
  n / d
end
```

**Comment by fatkodima** [comment]
I do not think this is possible to implement as a cop.

**Comment by koic** [comment]
I think so too.
