### ISSUE TITLE
Style/NumericPredicate Error

### ISSUE THREAD

**Issue by mamirad** [rubocop/rubocop#12369]
An error occurred while Style/NumericPredicate cop was inspecting

**Comment by koic** [comment]
Can you provide a repro code and the error log?

**Comment by koic** [comment]
It will be closed because steps to reproduce it are unknown, but please feel free to reopen it with information in the template below.
https://github.com/rubocop/rubocop/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
