### ISSUE TITLE
False positive for `Style/StringLiteralsInInterpolation` when 'interpolating' inside `%i[]`/`%w()` arrays

### ISSUE THREAD

**Issue by Earlopain** [rubocop/rubocop#12382]
Rubocop registers an offense for the following code:

```rb
%i(foo-#{"bar"})
# => [:"foo-\#{\"bar\"}"

# Autocorrect suggestion:
%i(foo-#{'bar'})
# => [:"foo-\#{'bar'}"]
```

It seems that interpolation just isn't possible when using this notation. The same is true when using `%w[]`.
`%I()` and `%W()` on the other hand are able to handle interpolation.

## RuboCop version

```
1.57.2 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.2.2) [x86_64-linux]
  - rubocop-performance 1.19.1
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.25.0
```

**Comment by koic** [comment]
I cannot reproduce this issue with the latest master branch and v1.57.2:

```console
$ cat example.rb
%i(foo-#{"bar"})

$ bundle exec rubocop --only Style/StringLiteralsInInterpolation -a
Inspecting 1 file
.

1 file inspected, no offenses detected
```

Can you provide repro steps?

**Comment by Earlopain** [comment]
You are right. I don't manage to reproduce myself.
