### ISSUE TITLE
Update `Style/CommentAnnotation` to recognize & autoccorect more annotation comments

### ISSUE THREAD

**Issue by bkjohnson** [rubocop/rubocop#12396]
## Is your feature request related to a problem? Please describe.

The [`rails notes` command](https://guides.rubyonrails.org/command_line.html#bin-rails-notes) shows annotation comments surrounded by square brackets. This leads to the misconception that an annotation comment must look like `[NOTE]` or `[TODO]` even though the [proper format according to the Ruby style guide](https://rubystyle.guide/#annotate-keywords) is with a colon and no square brackets.

The `Style/CommentAnnotation` cop aims to "check that comment annotation keywords are written according to guidelines" but it doesn't recognize the `[NOTE]` pattern as a possible annotation comment in need of fixing. This means that developers don't know that they _aren't_ writing an annotation comment when they think they are, and as a result none of the tooling will pick up on it without extra work.

## Describe the solution you'd like

Because of the easy misconception, I'd like something like an `AllowBrackets` configurable attribute on the cop that defaults to false. I'd also like the cop to be updated to use that attribute to recognize and autocorrect annotation comments that have the bracket format.

## Describe alternatives you've considered

I thought of making the change to the cop directly with no way of opting out, but a configurable attribute seemed like the better approach given the precedence with the `RequireColon` attribute.

**Comment by bkjohnson** [comment]
I'd be willing to try to implement this myself if people feel like it would be a welcome addition.

**Comment by koic** [comment]
`[NOTE]` appears in the output format of `bin/rails notes`, while actual source code comments seem to use `NOTE:`. This suggests that the discussion is about how to use `bin/rails notes`, and there doesn't seem to be a need to support bracketed `[NOTE]` in source code comments.

**Comment by bkjohnson** [comment]
> This is about how to display `bin/rails notes`, and there doesn't seem to be a need to support bracketed `[NOTE]` in source code comments.

That is not true. I've got a repo full of `[NOTE]` style annotations _in the source_. And because of how the rails notes command behaves, it's reasonable to assume I'm not the only one.

**Comment by koic** [comment]
In the [rails/rails repository](https://github.com/rails/rails), grepping for `NOTE` reveals instances of `NOTE:` but not `[NOTE]`. This suggests a possible misunderstanding about Rails documentation, which might need clarification through an update.

**Comment by bkjohnson** [comment]
I think there's a misunderstanding here. I'm not saying that rails source has `[NOTE]` annotation comments in it or that `bin/rails notes` even scans for `[NOTE]` comments. I'm saying that rails outputs that in the cli. Here is [the source for that](https://github.com/rails/rails/blob/550c5d235bb3fd8151d15438c4619b7d6b4a78b8/railties/lib/rails/source_annotation_extractor.rb#L109) and you can see an example of it in the link I provided above.

![Screenshot from the documentation on the `rails notes` command with example output. the `[TODO]`, `[OPTIMIZE]` and `[FIZME]` output tags for the annotation comments are highlighted.](https://github.com/rubocop/rubocop/assets/2008881/1430bda9-8a8a-42e2-9220-339383b3a6f3)

And this leads to engineers taking that output format and using it to write annotation comments in source code that won't be recognized.

**Comment by bkjohnson** [comment]
I think an update to the rails docs to either mention what the "correct" pattern is or at least link to the style guide would be good (and I might propose that), but I still think that it would be helpful if the default linting rule for this could recognize and correct an easy mistake like that.

**Comment by koic** [comment]
Yes, I understand the point made, but I think the output format of `bin/rails` notes is viewed as one form of view representation, distinct and separate from the source code comment as data.

**Comment by bkjohnson** [comment]
The input and output may seem distinct to you, but that hasn't been the case for the dozen+ engineers working in a repo with years of git history. Since this seems like the kind of thing that could happen to other teams, I thought it would be better to have a fix in upstream rubocop rather than just me writing a local extension for us.
