### ISSUE TITLE
Feature request: Add new option to the `Style/FetchEnvVar` cop

### ISSUE THREAD

**Issue by ydakuka** [rubocop/rubocop#12425]
## Is your feature request related to a problem? Please describe.

In addition to the `ENV` vars, I also have the `CONFIG` vars. I want to use the same cop rules for them.

**Comment by koic** [comment]
`CONFIG` does not exist as a standard Ruby API. It is unknown what kind of behavior is expected.

**Comment by ydakuka** [comment]
I mean I want to have option for alias names.
