### ISSUE TITLE
False Style/RedundantParentheses when wrap lambda

### ISSUE THREAD

**Issue by javierav** [rubocop/rubocop#12514]
When run rubocop over this:

```ruby
scope :with_email_confirmed, (lambda do |email_confirmed|
 # ...
end)
```

```
 C: [Correctable] Style/RedundantParentheses: Don't use parentheses around an expression.
```

The parentheses are necessary, otherwise the code block would be passed directly to the `scope` function as a block instead of to the lambda.

## RuboCop version

```
$ [bundle exec] rubocop -V
1.58.0 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.2.1) [arm64-darwin21]
```

**Comment by ydakuka** [comment]
This was solved here: https://github.com/rubocop/rubocop/pull/12505
