### ISSUE TITLE
`Style/HashEachMethods` incorrectly assumes argument in parentheses to be unused

### ISSUE THREAD

**Issue by paweljw** [rubocop/rubocop#12530]
Rubocop 1.58.0 considers this code to fail `Style/HashEachMethods` because `arg1` and `arg2` are unused.

```
variable.each do |(arg1, arg2), arg3|
  something = something_else[[arg1, arg2]]
  yield some_call(something, arg3)
end
```

Meanwhile `arg1` and `arg2` are clearly used inside the block.

--------

## Expected behavior

I expect Rubocop to pass.

## Actual behavior

Rubocop fails on `Style/HashEachMethods`. Additionally, applying autocorrection results in:

```
variable.each_value do |arg3|
  something = something_else[[arg1, arg2]]
  yield some_call(something, arg3)
end
```

This then obviously fails as `arg1` and `arg2` are no longer declared.

## Steps to reproduce the problem

Run rubocop 1.58.0 with `Style/HashEachMethods` enabled over the snippet provided int he description.

## RuboCop version

```
$ bundle exec rubocop -V
1.58.0 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.2.2) +server [arm64-darwin22]
  - rubocop-factory_bot 2.24.0
  - rubocop-performance 1.19.1
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.25.0
  - rubocop-sequel 0.3.4

```

**Comment by koic** [comment]
This issue is a dup with #12441.
