### ISSUE TITLE
User experience for "Infinite loop detected"

### ISSUE THREAD

**Issue by andyw8** [rubocop/rubocop#12547]
If a user encounters an "Infinite loop detected" error, then I think it makes sense for RuboCop to provide some actionable advice, e.g.:

1. Suggest to the user to update to the latest RuboCop version, if not already in use.
2. Suggest to report a bug if it still occurs on the latest version.

**Comment by Hiroto-Iizuka** [comment]
@andyw8 

I would like to know more about this issue.

Should I simply add that comment?
Or are you saying that I should specify the current version of Rubocop and post the comment?

**Comment by andyw8** [comment]
Displaying the latest version would require a network call, which may not be available, so showing a link to https://rubygems.org/gems/rubocop may be the best option.

**Comment by Hiroto-Iizuka** [comment]
@andyw8 

Thank you very much.
This is my first time so I am not sure but I will give it a try.

**Comment by Hiroto-Iizuka** [comment]
I tried this issue.
Waiting for confirmation from Rubocop maintainers.

https://github.com/rubocop/rubocop/pull/12655
