### ISSUE TITLE
Wrong version of extensions loaded with 1.59.0?

### ISSUE THREAD

**Issue by broksonic21** [rubocop/rubocop#12557]
## Expected behavior

With same exact Gemfile and Gemfile.lock, with updated rubocop extensions, rubocop is loading the wrong version dependencies. (see version info below)

This is true even if the other versions are fully uninstalled (gem uninstall rubocop-performance and bundle exec gem uninstall rubocop-performance before bundle install again)

## Actual behavior

Gemfile has this in it:

```
  gem "rubocop", "~> 1.59.0"
  gem "rubocop-capybara", "~> 2.19.0"
  gem "rubocop-graphql", "~> 1.4.0"
  gem "rubocop-minitest", "~> 0.34.1"
  gem "rubocop-performance", "~> 1.20.0"
  gem "rubocop-rails", "~> 2.23.0"
  gem "rubocop-rake", "~> 0.6.0"
 ```

and this in .rubocop.yml:

```
require:
  - rubocop-rails
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
  - rubocop-graphql
  - rubocop-capybara
```

## Steps to reproduce the problem

with above gemfile, have multiple people run:

```
bundle install
bundle exec rubocop -V
```

## RuboCop version

This is what it should be per Gemfile.lock and there on a number of our machines:

```
1.59.0 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.0.6) [arm64-darwin22]
  - rubocop-capybara 2.19.0
  - rubocop-graphql 1.4.0
  - rubocop-minitest 0.34.1
  - rubocop-performance 1.20.0
  - rubocop-rails 2.23.0
  - rubocop-rake 0.6.0
 ```

But others are seeing:

```
1.59.0 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.0.6) +server [arm64-darwin22]
  - rubocop-capybara 2.19.0
  - rubocop-graphql 1.4.0
  - rubocop-minitest 0.33.0
  - rubocop-performance 1.19.1
  - rubocop-rails 2.22.2
  - rubocop-rake 0.6.0
```

You can further see this in debug mode:

When working, it states:

```
For /Users/REDACTED/REDACTED/app: configuration from /Users/REDACTED/REDACTED/app/.rubocop.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-rails-2.23.0/config/default.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-rails-2.23.0/config/default.yml
Default configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.59.0/config/default.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-minitest-0.34.1/config/default.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-minitest-0.34.1/config/default.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-performance-1.20.0/config/default.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-performance-1.20.0/config/default.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-rake-0.6.0/config/default.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-rake-0.6.0/config/default.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-graphql-1.4.0/config/default.yml
configuration from #{path}
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-capybara-2.19.0/config/default.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-capybara-2.19.0/lib/../config/default.yml
```

But when not, it only has:

```
For /Users/REDACTED/REDACTED/app: configuration from /Users/REDACTED/REDACTED/app/.rubocop.yml
```

**Comment by dgollahon** [comment]
I ran into the same bug and got very, very confused. I discovered that running `--no-server` had the behavior I expected. This makes sense because if you're using `--server` it could cache the old versions. Otherwise I was unclear how this could possibly even be happening.

Seems like `rubocop` needs to detect that dependency versions have changed and restart in that case.

**Comment by r7kamura** [comment]
I have encountered the same problem in using `--server`.
(To be precise, my project uses `rubocop --server` in our pre-commit hook, and a member who is not very familiar with rubocop got stuck with this problem.)

In our example, the RuboCop server is running with rubocop-capybara 2.19.0, which was changed to 2.20.0 by `git pull`. The `Capybara/RedundantWithinFind` cop that was added there was referenced in the new .rubocop_todo.yml, which caused the following error:

```
Error: unrecognized cop or department Capybara/RedundantWithinFind found in .rubocop_todo.yml
Did you mean `Capybara/NegationMatcher`?
```

I think this is a common use case, so we should make sure to check even the dependent gem versions, as dgollahon said.

https://github.com/rubocop/rubocop/blob/3ce4fbfa8865740d963772d6ecd926cf9c5b0893/lib/rubocop/server/client_command/exec.rb#L33-L46

Note that if you are using a custom cop in your project, they are not versioned, so if you have checked the version of the dependent gem, there will be cases where it will not work. If there is a feature in .rubocop.yml that allows you to set an arbitrary cache key, I think it will work well in such cases, as follows:

```yaml
# .rubocop.yml
ServerCacheKey: v2
```

**Comment by pedro-stanaka** [comment]
Got the same behavior in Rubocop `1.64.1` with `rubocop-shopify` gem.

**Comment by bbatsov** [comment]
@koic Not sure we can do much about this, but perhaps we can at least document some of the things @r7kamura mentioned.

**Comment by pirj** [comment]
It’s pretty [well documented](https://docs.rubocop.org/rubocop/usage/server.html#restart-server), but a surprising behaviour nevertheless.

**Comment by koic** [comment]
FYI, I've opened issue #13004, which will likely cover many cases of this issue.
