### ISSUE TITLE
RuboCop icon in GitHub README is not clearly visible

### ISSUE THREAD

**Issue by ArmanGrewal007** [rubocop/rubocop#12553]
## This is the icon that we are using in GitHub readme:

![rubo-logo-horizontal](https://github.com/rubocop/rubocop/assets/66531687/8330ccff-a589-4b91-a10e-abc02ab76fbf)

## But that icon is not clearly visible in dark mode. We should add a light-coloured backgroud to the icon: 
How do these look?

![rubo-logo-horizontal](https://github.com/rubocop/rubocop/assets/66531687/38333310-bd71-4534-858f-e0dfcfe851f5)
![rubo-logo-horizontal](https://github.com/rubocop/rubocop/assets/66531687/81758ae5-402f-4d46-974f-4de562ca989d)

**Comment by koic** [comment]
PR that may be related for reference:
https://github.com/rubocop/rubocop/pull/10440

**Comment by bbatsov** [comment]
PR welcome!

**Comment by koic** [comment]
This issue was fixed by https://github.com/rubocop/rubocop/pull/12554.
