### ISSUE TITLE
Style/RedundantParentheses can change the behaviour of multi-line conditionals

### ISSUE THREAD

**Issue by alexwlchan** [rubocop/rubocop#12556]
I've found an example of a multi-line conditional where using `rubocop --autocorrect` will change the behaviour of the code, caused by the `Style/RedundantParentheses` lint.

## Steps to reproduce the problem

1. Create a file with the following contents:

    ```ruby
    # frozen_string_literal: true

    greeting = 'bricks and mortar'

    with_parentheses = (
      greeting.start_with?('a') or
      greeting.start_with?('b')
    )

    without_parentheses =
      greeting.start_with?('a') or
      greeting.start_with?('b')

    puts "with_parentheses = #{with_parentheses}, without_parentheses = #{without_parentheses}"
    ```

2. Run the file to confirm its output:

    ```console
    $ ruby example.rb
    with_parentheses = true, without_parentheses = false
    ```

3. Use RuboCop to apply safe autocorrects:

    ```console
    $ rubocop --debug --autocorrect example.rb
    For /var/folders/_c/h0g4c9_n6rg8d2v509hztzdc0000gn/T/tmp.KydPRazD: Default configuration from /usr/local/bundle/gems/rubocop-1.59.0/config/default.yml
    Use parallel by default.
    Skipping parallel inspection: only a single file needs inspection
    Inspecting 1 file
    Scanning /var/folders/_c/h0g4c9_n6rg8d2v509hztzdc0000gn/T/tmp.KydPRazD/example.rb
    Loading cache from /root/.cache/rubocop_cache/dca33ae567b4d3467baacfba370306ba30cf128e/6d7a3b621ca1730e04accd938619e4bdab66cfb1/71d6ddab2d6870d37a90933166f033ac16b50652
    C

    Offenses:

    example.rb:5:19: C: [Corrected] Layout/TrailingWhitespace: Trailing whitespace detected.
    with_parentheses =
                      ^
    example.rb:5:20: C: [Corrected] Style/RedundantParentheses: Don't use parentheses around a logical expression.
    with_parentheses = ( ...
                       ^
    example.rb:9:1: C: [Corrected] Layout/EmptyLines: Extra blank line detected.

    1 file inspected, 3 offenses detected, 3 offenses corrected
    Finished in 0.19036692997906357 seconds
    ```

4. Re-run the file to confirm the behaviour hasn't changed:

    ```console
    $ ruby example.rb
    with_parentheses = false, without_parentheses = false
    ```

     But `with_parentheses` used to be `true`!

     😱 

## Expected behavior

RuboCop doesn't change the behaviour of my code if I run "safe" autocorrects.

## Actual behavior

RuboCop is changing the file in a way that causes the behaviour to change. This is what it changes the file to:

```ruby
# frozen_string_literal: true

greeting = 'bricks and mortar'

with_parentheses =
  greeting.start_with?('a') or
  greeting.start_with?('b')

without_parentheses =
  greeting.start_with?('a') or
  greeting.start_with?('b')

puts "with_parentheses = #{with_parentheses}, without_parentheses = #{without_parentheses}"
```

## RuboCop version

I can reproduce this issue with Ruby 3.2.2 and:

* The latest stable version of RuboCop:

    ```
    $ rubocop -V
    1.59.0 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.2.2) [x86_64-linux]
    ```

* The latest Git commit in master at time of writing, 5af4bad:

    ```console
    $ rubocop -V 
    1.59.0 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.2.2) [x86_64-linux]
    ```

    I saw there were a few other issues filed around `Style/RedundantParentheses` and I thought maybe it was fixed in master, but that doesn't seem to be the case. The only currently open issue about this lint is #12511, but that seems to be a stylistic choice rather than a behaviour bug.

* The previous stable version of RuboCop:

    ```
    $ rubocop -V
    1.58.0 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.2.2) [x86_64-linux]
    ```

I **cannot** reproduce this issue with the stable version of RuboCop before that:

```console
$ rubocop -V
1.57.2 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.2.2) [x86_64-linux]
```

which implies this issue was introduced somewhere in v1.58.0.

**Comment by koic** [comment]
For semantic operators using `and` and `or`, parentheses should be maintained regardless of whether it is a single line or multi-line, to preserve the operator precedence:

```console
$ ruby-parse -e "var = (foo or bar)"
(lvasgn :var
  (begin
    (or
      (send nil :foo)
      (send nil :bar))))

$ ruby-parse -e "var = foo or bar"
(or
  (lvasgn :var
    (send nil :foo))
  (send nil :bar))
```

I have opened PR #12563 to address this.

**Comment by alexwlchan** [comment]
@koic Thanks for looking at this so quickly! 💚
