### ISSUE TITLE
Naming/BlockForwarding with anonymous block parameter (Ruby 3.3.0)

### ISSUE THREAD

**Issue by datanoise** [rubocop/rubocop#12571]
With config:

```yaml
AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
```

In Ruby 3.3.0 the following code is invalid:

```ruby
  def do_rollback(&)
    ActiveRecord::Base.transaction do
      after_rollback(&)
    end
  end
```

It generate a SyntaxError:  ```anonymous block parameter is also used within block```

But with Naming/BlockForwarding enabled, rubocop suggests using anonymous block parameter for the following code:

```ruby
  def do_rollback(&block)
    ActiveRecord::Base.transaction do
      after_rollback(&block)
    end
  end
```

**Comment by joevandyk** [comment]
Similar problem with `Style/ArgumentsForwarding`

**Comment by Alagaesia93** [comment]
```
Naming/BlockForwarding:
  EnforcedStyle: explicit
```
Fixed for me, at least temporary

**Comment by joeldrapper** [comment]
This is a bug in Ruby 3.0.0 https://bugs.ruby-lang.org/issues/20090. IMO, Rubocop should work around this when it detects Ruby 3.0.0 by enforcing named forwardings in cases where this bug would be triggered. Once Ruby 3.0.1 is released, it can convert these back to anonymous forwardings.

**Comment by Timmitry** [comment]
@joeldrapper Thanks for pointing out that this is a bug! You wrote Ruby 3.0.0 though, which confused me a bit, but probably meant Ruby 3.3.0, as the bug ticket also points out 👍

**Comment by joeldrapper** [comment]
Ops! Yes, I meant `3.3.0`. I edited my comment.

**Comment by koic** [comment]
This is a technical note. Unfortunately, RuboCop does not recognize the patch version of the runtime Ruby as part of its analysis information. This means it cannot determine whether Ruby 3.3.1 or Ruby 3.3.0 is the runtime Ruby version. Therefore, for the Ruby 3.3 series, the interim solution seems to be to not issue offenses to prevent the syntax error. #12577 is based on that approach.

**Comment by flash-gordon** [comment]
@koic it seems it still has edgecases:
```ruby
# frozen_string_literal: true

def meth(&block)
  if rand > 0.5
    no_block(&block)
  else
    block { no_block(&block) }
  end
end
```

`rubocop foo.rb` shows offenses:

```
foo.rb:5:14: C: [Correctable] Naming/BlockForwarding: Use anonymous block forwarding.
    no_block(&block)
             ^^^^^^
```

But `rubocop -a foo.rb` corrupts code:

```ruby
def meth(&block)
  if rand > 0.5
    no_block(&)
  else
    block { no_block(&block) }
  end
end
```

Can you confirm it?
