### ISSUE TITLE
Option idea: Enable all disabled cops

### ISSUE THREAD

**Issue by ydakuka** [rubocop/rubocop#12602]
## Is your feature request related to a problem? Please describe.

I have some code and I want to check if RuboCop finds any offenses in it using all cops, including those that are disabled by default.

**Comment by koic** [comment]
This can be achieved by specifying `EnabledByDefault: true` in `.rubocop.yml`:
https://docs.rubocop.org/rubocop/1.59/configuration.html#enabled

**Comment by ydakuka** [comment]
Thank you!
