### ISSUE TITLE
RuboCop::CLI unexpected behavior when linting files outside the project

### ISSUE THREAD

**Issue by budu** [rubocop/rubocop#12639]
## Expected Behavior

There is no obvious expected behavior.

## Actual Behavior

I've been having [weird issues](https://github.com/flycheck/flycheck/issues/2049) with slim-lint integration into Emacs flycheck. After some time debugging these problems, it became apparent that the bug lies within slim-lint or some of its dependencies. After reviewing `slim-lint` I'm quite sure this issue is specific to RuboCop::CLI.

When running `slim-lint` (which uses RuboCop::CLI) on a file outside the project, it returns unexpected results. This is an issue with flycheck as it is using temporary files in `/tmp`.

For example, the following code, inside the normal path `app/views/...` doesn't have any warnings.

```slim
p
  | Can't remember your password for
  strong = @user.email
```

It does output a warning (with `rubocop-rails` in the project `.rubocop.yml`) when that file is anywhere outside the project. The slim-lint output also contains weird errors:

```
$ slim-lint ../password_reset.html.slim
...
175 errors occurred:
An error occurred while RSpec/Capybara/FeatureMethods cop was inspecting /home/budu/projects/password_reset.html.slim.rb.
An error occurred while RSpec/Rails/AvoidSetupHook cop was inspecting /home/budu/projects/password_reset.html.slim.rb.
An error occurred while RSpec/Rails/NegationBeValid cop was inspecting /home/budu/projects/password_reset.html.slim.rb.
...
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop/rubocop/issues

Mention the following information in the issue report:
1.60.1 (using Parser 3.3.0.4, rubocop-ast 1.30.0, running on ruby 3.2.2) [x86_64-linux]
../password_reset.html.slim:3 [W] RuboCop: Rails/HelperInstanceVariable: Do not use instance variables in helpers.
```

The errors are repeated for every lines in the file.

I've debugged slim-lint and I found out that the `RuboCop::CLI` instance has a different `@config_store` and `@path_cache`.  Here's the path cache for the file with the correct path:

```ruby
   @path_cache=
    {"/home/budu/projects/teki/app/views/user_mailer"=>"/home/budu/projects/teki/.rubocop.yml",
     "/home/budu/projects/teki"=>"/home/budu/projects/teki/.rubocop.yml"},
```

And here's the one with the wrong path:

```ruby
   @path_cache=
  {"/home/budu/projects"=>"/home/budu/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.60.1/config/default.yml",
   "/home/budu/projects/teki"=>"/home/budu/projects/teki/.rubocop.yml"},
```

As you can see the RuboCop::CLI instance is using the gem default configuration. It shouldn't pose a problem in itself, but the requires (`rubocop-rails`, `rubocop-rspec`) from the project configuration are still enabled, causing the errors/warnings.

In theory, adding Rails/HelperInstanceVariable to the list of slim-lint ignored cops should fix that particular issue but that behavior looks wrong. 

I'm not sure where to go from here.

## RuboCop version

```
$ rubocop -V
1.60.1 (using Parser 3.3.0.4, rubocop-ast 1.30.0, running on ruby 3.2.2) [x86_64-linux]
  - rubocop-minitest 0.34.5
  - rubocop-rails 2.23.1
  - rubocop-rspec 2.26.1
```

**Comment by jonas054** [comment]
I have not been able to reproduce the problem. Could you give all the details I need in order to get the same error?
Here's the set-up I used:
```
~/dev/issues/rubocop$ head slim-code/password_reset.html.slim.rb 12639/.r* 12639/*
==> slim-code/password_reset.html.slim.rb <==
p
  | Can't remember your password for
  strong = @user.email

==> 12639/.rubocop.yml <==
require:
  - rubocop-rails

AllCops:
  NewCops: enable

==> 12639/Gemfile <==
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'slim_lint'
gem 'rubocop-rails'
gem 'rubocop-rspec'

==> 12639/Gemfile.lock <==
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (7.1.3.2)
      base64
      bigdecimal
      concurrent-ruby (~> 1.0, >= 1.0.2)
      connection_pool (>= 2.2.5)
      drb
      i18n (>= 1.6, < 2)
```

but when running I get no error:
```
 ~/dev/issues/rubocop/12639$ bundle exec slim-lint ../slim-code/password_reset.html.slim.rb 
../slim-code/password_reset.html.slim.rb:3 [W] RuboCop: Rails/HelperInstanceVariable: Do not use instance variables in helpers.
```

**Comment by budu** [comment]
I didn't notice before but the errors are all RSpec related. To see them, you just have to require `rubocop-rspec`.

```
==> 12639/.rubocop.yml <==
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
```

**Comment by jonas054** [comment]
What I've found is that the crashes occurs in `.../gems/rubocop-rspec-2.27.0/lib/rubocop/rspec/language.rb` where accessing configuration fails because `Language.config` is `nil`. Is seems that `rubocop-rspec` has a special way of accessing its configuration, and for some reason this doesn't work when `slim-lint` calls `rubocop` with `rubocop-rspec`.

Running `rubocop` itself with the same `.rubocop.yml` as above works well. So it looks like it's this combination of tools that fails to deliver. My recommendation is that you report it in https://github.com/rubocop/rubocop-rspec as they are more likely to have the expertise to resolve it.

**Comment by budu** [comment]
Good to know. This should explain the errors.

Now, my original issue was a bit tangential to these errors. The main problem being that the warning (Rails/HelperInstanceVariable) should be filtered out by the custom configuration used by `slim-lint`. It does when the file is inside the repository.

I've tested a bit further and the rubocop behavior makes sense. It basically fallback to some generic default configuration when outside the current project. This breaks down the custom behavior in `slim-lint` and `rubocop-rspec`.

When calling rubocop directly, we can always force the configuration but this doesn't work with tools wrapping rubocop like `slim-lint`.

These custom behaviors would be hard to account for from rubocop itself. I'll see what I can do with slim-lint once I get more free time. This issue can be closed now.

Thanks a lot!
