### ISSUE TITLE
`Style/DocumentationMethod` to allow us to configure exclusion for special methods

### ISSUE THREAD

**Issue by okuramasafumi** [rubocop/rubocop#12643]
## Is your feature request related to a problem? Please describe.

https://docs.rubocop.org/rubocop/1.60/cops_style.html#styledocumentationmethod

`Style/DocumentationMethod` cop doesn't allow us to exclude some method names such as `included` or `inherited`. Those are special methods that are called by Ruby runtime as hooks. Sometimes we write some boilerplate code in there and we don't have anything special to write about them.

## Describe the solution you'd like

`AllowedMethods` option for `Style/DocumentationMethod` cop such as https://docs.rubocop.org/rubocop/1.60/cops_style.html#configurable-attributes-45

The default value might be something like `initialize, inherited, included`.

## Describe alternatives you've considered

We might simply ignore those hook methods, but I believe some users do not want to ignore them.

## Additional context

I cannot find any list of the special methods. If there is one it will be very helpful.

**Comment by koic** [comment]
This cop is disabled by default, and I don't see a use case for enabling it while also introducing an `AllowedMethods` parameter. Instead of setting the new parameter, consistent handling can be through documentation such as `# nodoc`.

**Comment by okuramasafumi** [comment]
`# nodoc` works only for RDoc and doesn't for YARD.
If adding `AllowedMethods` is not possible, what about excluding these special methods by default?

**Comment by koic** [comment]
Well, either way, it duplicates #11585. The discussion will likely proceed there.

**Comment by okuramasafumi** [comment]
@koic Oh I didn't notice the duplication. Thank you for pointing out!
