### ISSUE TITLE
Compatibility Inquiry: rubocop 1.60.2 with Ruby 3.3.0

### ISSUE THREAD

**Issue by sydverisk** [rubocop/rubocop#12675]
Hi,

I'm seeking confirmation regarding the compatibility of the rubocop 1.60.2 with the recently released Ruby 3.3.0 (December 25, 2023).

While I reviewed the gem's documentation on RubyGems https://docs.rubocop.org/rubocop/1.60/compatibility.html, and https://rubygems.org/gems/rubocop it only specifies a minimum required Ruby version of 2.7.0. Unfortunately, I haven't found any explicit confirmation on compatibility with newer versions like 3.3.0.

Given your expertise in this area, could you offer any insights or leads on this matter? Any information you can provide would be greatly appreciated.

Thank you for your time and assistance!

**Comment by koic** [comment]
Ruby 3.3 is already supported as described in the matrix table of "Support Matrix" section:
https://docs.rubocop.org/rubocop/1.60/compatibility.html#support-matrix

**Comment by sydverisk** [comment]
Thanks for the update @koic. I appreciate it!
