### ISSUE TITLE
Layout/SpaceBeforeFirstArg is not found until after "some code"

### ISSUE THREAD

**Issue by wanchic** [rubocop/rubocop#12704]
When running rubocop, it seems to miss `Layout/SpaceBeforeFirstArg` on the first couple of lines. Only after some other code has been analyzed, it will detect any other `Layout/SpaceBeforeFirstArg`

## Expected behavior
There should have been three errors in total. It is missing two more errors:
```
db/seeds/roles.seeds.rb:3:18: C: Layout/SpaceBeforeFirstArg: Put one space between the method name and the first argument.
db/seeds/roles.seeds.rb:4:18: C: Layout/SpaceBeforeFirstArg: Put one space between the method name and the first argument.

```

## Actual behavior

Rubocop output:
```
$ rubocop db/seeds
Inspecting 5 files
C....

Offenses:

db/seeds/roles.seeds.rb:8:18: C: Layout/SpaceBeforeFirstArg: Put one space between the method name and the first argument.
Rails.logger.info"User Roles... Completed\n"
```

## Steps to reproduce the problem

Example file: `roles.seeds.rb`
```
# frozen_string_literal: true

Rails.logger.info"\nUser Roles..."
Rails.logger.info"--------------\n"

user_roles = %w[admin user]

Rails.logger.info"User Roles... Completed\n"

user_roles.each do |name|
  Role.find_or_create_by(name: name)
end

Rails.logger.info "User Roles... Completed\n"
```

`$ rubocop db/seeds`

## RuboCop version
```
$ rubocop -v
0.68.1
```

**Comment by Earlopain** [comment]
Your version of rubocop seems quite old (almost 5 years), can you upgrade any further? I ran your example on the most recent version and am getting the 3 expected offenses so it has already been fixed somewhere inbetween.

**Comment by koic** [comment]
This issue has been resolved in new versions. Please upgrade to the latest RuboCop. Thank you.

**Comment by wanchic** [comment]
Thank you!
