### ISSUE TITLE
False positive for `Layout/SpaceAroundKeyword` when using `ParserEngine: parser_prism` 

### ISSUE THREAD

**Issue by andyw8** [rubocop/rubocop#12829]
## Steps to reproduce the problem

Create a file containing:

```
while true
  # random
end
```

RuboCop fails with `Layout/SpaceAroundKeyword: Space before keyword do is missing`.

This might relate to some underlying issue in `prism`, I haven't investigated yet.

## RuboCop version

```
% bin/rubocop -V                                                                                                                  
1.62.1 (using Prism 0.24.0, rubocop-ast 1.31.2, running on ruby 3.3.0) [x86_64-linux]
  - rubocop-graphql 1.5.1
  - rubocop-minitest 0.35.0
  - rubocop-performance 1.21.0
  - rubocop-rails 2.24.1
  - rubocop-sorbet 0.8.0
```

**Comment by andyw8** [comment]
(I also get `Style/WhileUntilDo: Do not use do with multi-line while.`).

**Comment by andyw8** [comment]
Another one, which is probably the same underlying cause:

```
if true
  # ;
end
```
Fails with `Style/IfWithSemicolon: Do not use if true; - use a ternary operator instead.`

**Comment by andyw8** [comment]
(this is is Prism 0.24.0, I'll check if it still happens on 0.25.0).

**Comment by andyw8** [comment]
Yes, still happens with 0.25.0.

**Comment by kddnewton** [comment]
Both of these are problems with `srange_find` in the translation layer. They should not be searching comments.

**Comment by andyw8** [comment]
Thanks @kddnewton, I'll look into fixing that in Prism.

@koic I'm not sure if you want to keep this open for tracking, feel free to close it.

**Comment by andyw8** [comment]
Working on a fix in https://github.com/ruby/prism/pull/2694

**Comment by kddnewton** [comment]
@andyw8 this may have been fixed in the latest version of prism, can you check?

**Comment by andyw8** [comment]
Indeed it is, I updated the core branch earlier.
