### ISSUE TITLE
Make `Style/YodaCondition` aware of `#eql?` and `#equal?`

### ISSUE THREAD

**Issue by ydakuka** [rubocop/rubocop#12859]
## Describe the solution you'd like

```ruby
# bad
'foo'.eql?(type)
'foo'.equal?(type)

# good
type.eql?('foo')
type.equal?('foo')
```

**Comment by koic** [comment]
I'm going to close this proposal because Yoda Conditions are generally used in expressions for equivalence comparison involving operators. Thank you.
