### ISSUE TITLE
regression in 1.63.4 -- "Could not locate Gemfile"

### ISSUE THREAD

**Issue by asottile** [rubocop/rubocop#12876]
same as #12846 but has regressed yet again!

**Comment by Earlopain** [comment]
I tested 1.63.2 through 1.63.5 but the only version I can reproduce this is on 1.63.1. Can you check if this is still broken on 1.63.5 for you?

I did notice that this only reproduces if the parent directory doesn't contain a Gemfile/Lockfile so it's possible there are some other preconditions I don't know about, or perhaps it's some other issue entirely. Purely from the code I would say that this exception is now always rescued.

**Comment by Earlopain** [comment]
Nevermind that, I saw the PR you linked to here. This happens if a Gemfile is present without a lockfile.
