### ISSUE TITLE
Suggestion: Ban AndOr almost everywhere

### ISSUE THREAD

**Issue by nathany** [rubocop/rubocop#1288]
Not only conditionals, but in assignments... that's where I've ran into the most trouble.

``` ruby
a = b() and c() # => a is the result of calling b(), c() doesn't impact the result even when called
```

But it is nice for "do this, then that" in the typical Rails case:

``` ruby
redirect_to login_path and return
```

**Comment by bbuchalter** [comment]
I know this is an old, forgotten issue, but perhaps a pragmatic solution is to not blindly suggest that `&&` can replace `and` in all usages? I think with the current message, we're likely to introduce bugs in folks applications. Any interest in changing the message?

**Comment by nathany** [comment]
@bbuchalter Instead of commenting on a closed issue, it's best to open a new issue and link to the closed issue. That way your comment doesn't get lost.

**Comment by webzorg** [comment]
The other way of doing this `redirect_to root_path and return if current_user.id == params[:id].to_i`
is to use an if block which would be 4 lines. This is a legitimate use case of using and, where && is just a syntax error...

**Comment by jonas054** [comment]
That expression is allowed with the configuration
```yaml
Style/AndOr:
  EnforcedStyle: conditionals
```
But note that your specific example was criticized above my @mikegee as it depends on a truthy return value from `redirect_to`, which it happens to give, but it's not documented behavior.
