### ISSUE TITLE
uninitialized constant Bundler::SharedHelpers (NameError)

### ISSUE THREAD

**Issue by djberg96** [rubocop/rubocop#12891]
Curious warning/error with a rubocop rake task, which is simply defined as `RuboCop::RakeTask.new` in the Rakefile:
```
>bundler -v
Bundler version 2.5.10

>gem -v
3.5.10

>ruby -v
ruby 3.2.4 (2024-04-23 revision af471c0e01) [x86_64-linux]

>bundle exec rubocop -V
1.63.4 (using Parser 3.3.1.0, rubocop-ast 1.31.3, running on ruby 3.2.4) [x86_64-linux]
  - rubocop-rspec 2.29.2

>rake rubocop
rake aborted!
NameError: uninitialized constant Bundler::SharedHelpers (NameError)

      Bundler::SharedHelpers.filesystem_access(loaded_from, :read) do
             ^^^^^^^^^^^^^^^
<internal:/home/dberger/.rbenv/versions/3.2.4/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `block in require'
<internal:/home/dberger/.rbenv/versions/3.2.4/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:39:in `synchronize'
<internal:/home/dberger/.rbenv/versions/3.2.4/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:39:in `require'
<internal:/home/dberger/.rbenv/versions/3.2.4/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
<internal:/home/dberger/.rbenv/versions/3.2.4/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
<internal:/home/dberger/.rbenv/versions/3.2.4/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
<internal:/home/dberger/.rbenv/versions/3.2.4/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
Tasks: TOP => rubocop
(See full trace by running task with --trace)
```

**Comment by Earlopain** [comment]
I can't reproduce this. Can you give more detailed instructions?

**Comment by djberg96** [comment]
The weird thing is that I only see this on my Ubuntu laptop. Using my desktop Ubuntu VM, it works. Identical setup as far as I can tell. I double checked the results of `bundler config` (both empty) and neither has anything in a ~/.gemrc file.

**Comment by Earlopain** [comment]
Yeah, there must be more to this. I tried with your repo and it just works for me

**Comment by djberg96** [comment]
I dunno if this is a clue or what, but it works if I first, explicitly `require 'bundler'` at the top of the Rakefile and second, touch the Gemfile.lock file first. Why does it need this file to be present? No clue. It's not checked into the repo.

**Comment by Earlopain** [comment]
That's https://github.com/rubocop/rubocop/issues/12876, I have a PR open for that https://github.com/rubocop/rubocop/pull/12901. Maybe that also fixes this? Give it a try.

For me the lockfile always generated before rubocop tried to access it

**Comment by djberg96** [comment]
@Earlopain Seems to fix running `rubocop`, but not if run as a rake task.

**Comment by djberg96** [comment]
@Earlopain I'm also sort of confused by the lockfile.rb code in general. If rubocop needs bundler to function properly, then why not make it a gem dependency instead of this rigamarole they've got going on in that file?

**Comment by Earlopain** [comment]
I guess it's more of a optional dependency. Since everything around it relies on the contents of a lockfile it's a safe assumption to make that bundler will be around as well. That's how I would rationalize it.

I think you may be running into a bundler bug. https://github.com/rubygems/rubygems/pull/7647 seems very relevant as it mentions rakefiles and `SharedHelpers`. The description is too complicated for me to quickly understand but I think that may be it.

**Comment by djberg96** [comment]
Downgrading to 2.5.9 didn't seem to do it, though I'm also not 100% sure because downgrading bundler required some manual fiddling since it's a default gem. Could be, though.

But, that still wouldn't explain why it only seems to happen on my laptop.

**Comment by Earlopain** [comment]
It does say this:

> However, the autoload does not seem to be triggering under some situations, such as when loading our own Rakefile. But that also does not happen always, but only when you have two different versions of psych installed in your system.

Which I guess could be a difference between your two machines. I installed a different psych version and didn't reproduce though

**Comment by djberg96** [comment]
Yep, I'm only showing psych 5.01.

**Comment by Earlopain** [comment]
Looks like a new bundler version released yesterday. Give that a try?

**Comment by djberg96** [comment]
@Earlopain Yep, that seems to have fixed it, thanks!

**Comment by Earlopain** [comment]
Nice!
