### ISSUE TITLE
Cop idea: Detect `map` where result is discarded

### ISSUE THREAD

**Issue by Earlopain** [rubocop/rubocop#12909]
## Is your feature request related to a problem? Please describe.

I stumbled over the following code:

```rb
details = my_method_call
details.map do |entry|
  entry["assets"] = foo(entry)
end
bar(details)
```

The `map` call is not needed and a plain `each` would accomplish the same thing without needless array allocation.

## Describe the solution you'd like

A cop to correct to the following:

```rb
details = my_method_call
details.each do |entry|
  entry["assets"] = foo(entry)
end
bar(details)
```

**Comment by vlad-pisanov** [comment]
I believe this is what [Lint/Void](https://docs.rubocop.org/rubocop/cops_lint.html#lintvoid) with the `CheckForMethodsWithNoSideEffects: true` option does:

```ruby
W: Lint/Void: Method #map used in void context. Did you mean #each?
details.map do |entry|
   ...
```

**Comment by Earlopain** [comment]
Yes, that seems accurate. Didn't expect something like that to be part of `Lint/Void`, thanks for pointing this config out to me.
