### ISSUE TITLE
Ability to disable `Lint/Syntax` from extension

### ISSUE THREAD

**Issue by Zopolis4** [rubocop/rubocop#12945]
## Is your feature request related to a problem? Please describe.

I am working on a tool to convert Ruby to Crystal via a rubocop extension, which will inevitably produce invalid Ruby code:
![image](https://github.com/rubocop/rubocop/assets/64618338/d245fd53-7c84-48b3-ab76-29dfabc71e55)

I know this code is invalid Ruby, and I would like to ignore this error.

## Describe the solution you'd like

The ability to in some way disable `Lint/Syntax` from an extension, in the code of the extension, i.e. not building a local modified copy of rubocop with a gutted `Lint/Syntax`.
 
## Describe alternatives you've considered

- I have attempted to disable `Lint/Syntax` through configuration, which failed as expected.
- I've tried to undefine the `Lint/Syntax` cop in the extension, no luck.
- I've tried to create my own `Lint/Syntax` cop which does nothing, but it seems to have no effect.

**Comment by koic** [comment]
While a syntax error triggers the `Lint/Syntax`, no other cops can operate, making `Lint/Syntax` the only reliable resource:
https://docs.rubocop.org/rubocop/1.64/configuration.html#enabled

Although Crystal's syntax resembles that of Ruby, RuboCop is a linter designed for parsing Ruby syntax. Therefore, it would be inappropriate to provide an API to disable the fundamental `Lint/Syntax`.
