### ISSUE TITLE
CodeClimate coverage upload not working

### ISSUE THREAD

**Issue by Earlopain** [rubocop/rubocop#12949]
Ref #12946

> Something is messed up in CodeClimate as the old links to the repos are there (those from rubocop-hq) and they seem to be active, but their settings can't be changed. Also rubocop/rubocop is there twice for some reason... I've added some CC_TEST_REPORTER_ID from one of them, but I think we'll need to contact CC's support to clean up the legacy stuff and this duplication (when I try to delete one of the two RuboCop repos it blows up).

Sample job: https://github.com/rubocop/rubocop/actions/runs/9302007461/job/25601715895

@bquorning, maybe you have an idea?

I guess, if all fails contact support. The duplication above gives me an inkling that this just won't work regardless of what we try.

**Comment by bquorning** [comment]
I don’t recall which ENV variable we had to set in CircleCI, but maybe @bbatsov can check if he still has access. It was probably CC_TEST_REPORTER_ID which I see is also set in https://github.com/rubocop/rubocop/settings/secrets/actions, so it _should_ just work (if the value is correct).
