### ISSUE TITLE
improve compatibility with pre-commit when using inherit_gem in a project with git dependencies

### ISSUE THREAD

**Issue by Roguelazer** [rubocop/rubocop#12989]
## Is your feature request related to a problem? Please describe.

I would like to use rubocop with pre-commit (which seems to be supported, since you ship a `.pre-commit-hooks.yaml`). Unfortunately, rubocop attempts to load extensions by calling `Bundler.load`; this attempts to load the gems for the calling application (as opposed to the gems in the pre-commit / rubocop isolated environment), which is not desirable -- at best, it will pollute global gem state by installing all of the dependencies from the containing application's gemfile; if any of the dependencies are git dependencies, it'll just fail

I've been told that this has been addressed before, but whatever was done doesn't seem to be comprehensive.

## Describe the solution you'd like

My thought was that rubocop could add a way to signal that we don't want to load from bundler (perhaps a new command-line flag like `--no-i-really-dont-want-to-use-bundler`) and pass it in the `.pre-commit-hooks.yaml`. When that flag is passed, rubocop would skip the `Bundler.load` call entirely in `Rubocop::ConfigLoaderResolver#gem_config_path`.

## Describe alternatives you've considered

I sent `pre-commit` a patch (https://github.com/pre-commit/pre-commit/pull/3232) to disable loading the Gemfile from their side, but they are adamantly opposed to making that change. Their stance is "a linter blindly trying to access an unrelated environment is a poorly behaving linter" and that this is a rubocop bug. 

## Additional context

https://github.com/Roguelazer/rubocop-pre-commit-breakage-demo is a repository which has minimal reproduction steps to show that this is broken.

**Comment by Earlopain** [comment]
Can you check if #12991 solves the problem? I'm not familiar with the tool and am not sure how to tell it to use my local rubocop or the one from the PR

**Comment by Earlopain** [comment]
That's nice, thanks for confirming
