### ISSUE TITLE
Double negative fix is not good

### ISSUE THREAD

**Issue by PeterHickman** [rubocop/rubocop#12992]
## Is your feature request related to a problem? Please describe.

When encountering `array.thing.size > 0` the suggested solution is `!array_thing.empty?`

## Describe the solution you'd like

This double negative, the `!` and `empty?`, is less readable than `array_thing.any?`

## Describe alternatives you've considered

None

## Additional context

It is easier to read this way, besides (and this is a purely personal peeve) the `!` can sometimes be missed if, for example, the variable starts with an `l`. `!list_of_things` could easily misread as `list_of_things`

**Comment by koic** [comment]
RuboCop cannot distinguish between the types of receivers such as `ary.size > 0` and `str.size > 0`. This leads to different behaviors as follows:

```ruby
# When the receiver is an Array object
!ary.empty? # => OK
ary.any?    # => OK

# When the receiver is a String object
!str.empty? # => OK
str.any?    # => NoMethodError
```

To avoid this incompatibility during autocorrection, `Style/ZeroLengthPredicate` cop is necessary to use `!var.empty?`.

**Comment by PeterHickman** [comment]
Ah I fully understand, we do not want to break working code. Thanks for the
response. Can you close this or do I have to?

**Comment by koic** [comment]
It's already closed. Thank you for sharing your concern.
