### ISSUE TITLE
Calling `.[]` with wrongly indented args doesn't register violation

### ISSUE THREAD

**Issue by cllns** [rubocop/rubocop#13084]
### Example 1
```ruby
# frozen_string_literal: true

module Services
  module Internal
    # Publisher
    class PostPublisher
      def call(post)
        proc = ->(arg) { call(arg) }

        proc[
post
      ]
      end
    end
  end
end
```
I would expect this be a Rubocop violation, and autocorrect would align the `post` to one level deeper than the start of `proc` (And also make sure the ending bracket is the same level of indentation as `proc`.)

### Example 2

[`dry-auto_inject` & `dry-system` uses a special syntax](https://dry-rb.org/gems/dry-system/1.0/dependency-auto-injection/) to import dependencies: `include Import["my_service"]`. On a single line, this is no problem, but when separating onto several lines, Rubocop doesn't care about the indentation level of the args at all.

```ruby
# frozen_string_literal: true

require 'system/container'
Import = Application.injector

require 'import'
module Services
  module Internal
    # Publisher
    class PostPublisher
      include Import[
  'logger',  # indentation here is way off but rubocop doesn't complain
  'external_service', 
  repo: 'post_repository',
      ]
      # ...
    end
  end
end

```

I would expect this be a Rubocop violation, and autocorrect would align the `'logger'`, `'external_service'` and `repo: 'post_repository'` lines to one level deeper than where the `include` starts.

## Actual behavior

No violations. I can change the indentation level to 0 or 20 and Rubocop doesn't care. Rubocop does catch if they're not all the same, but it doesn't care about its indentation relative to what it's called on. It also doesn't care where the closing `]` is indented to.

```
For /Users/sean/oss/rubocop_demo: Default configuration from /Users/sean/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/rubocop-1.65.0/config/default.yml
Use parallel by default.
Skipping parallel inspection: only a single file needs inspection
Inspecting 1 file
Scanning /Users/sean/oss/rubocop_demo/demo.rb
.

1 file inspected, no offenses detected
```

## Notes
I guess this can be fixed by making the `Layout/*Indentation*` cops smarter, since the `[]` is a method call.

## Steps to reproduce the problem
`rubocop demo.rb` (if above is `demo.rb`)

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler.
If you see extension cop versions (e.g. `rubocop-performance`, `rubocop-rspec`, and others)
output by `rubocop -V`, include them as well. Here's an example:

```
> rubocop -V
1.65.0 (using Parser 3.3.4.0, rubocop-ast 1.31.3, running on ruby 3.3.3) [arm64-darwin23]
```

**Comment by cllns** [comment]
Updated this with a more generic example (as Example 1), which deals with procs being called with `[]`

**Comment by dvandersluis** [comment]
This seems to be working as expected (please see tests added in #13563).

If you are using `EnforcedStyle: with_first_argument` for `Layout/ArgumentAlignment`, all that is enforced is that all the arguments are aligned with each other, which is the case in your example. If you'd like them to be aligned relative to the method call, use `EnforcedStyle: with_fixed_indentation`.

I'm going to close this as I don't see any bugs, but feel free to comment or open a new issue if I'm overlooking something.
