### ISSUE TITLE
Sponsorship logo missing from README

### ISSUE THREAD

**Issue by seanlerner** [rubocop/rubocop#13122]
Wealthsimple has been sponsoring rubocop for a few years now. Initially our logo appeared on the README, but now no longer appears. Is there a way we can have it appear on the README again?

![image](https://github.com/user-attachments/assets/c6e9bc41-e5a5-4471-a6ea-ff61b0b333ff)

**Comment by Earlopain** [comment]
I openend #13138 which aims to make the readme section more accurate, though it won't help in your specific case. I do see your company has contributed quite a bit but looking at the contributing section on the OpenSearch website itself I don't see that at all, which to me seems like the main problem here.

Stupid question, but is it possible to make anonymous contributions and that is somehow accidentaly turned on? I have no experience with this website (and am also not affiliated with rubocop nor opensearch, so not much to say from me anyways)

**Comment by Earlopain** [comment]
I now see the logo in the readme, seems to have been fixed on the opencollective side sometime in the last 3 months.
