### ISSUE TITLE
 Style/SymbolProc auto fix brakes logic

### ISSUE THREAD

**Issue by bastikk** [rubocop/rubocop#13129]
```
  attribute :is_confirmed do |user|
    user.is_confirmed?
  end

```
 Style/SymbolProc: Pass &:is_confirmed? as an argument to attribute instead of a block.
  attribute :is_confirmed do |user| ...

after rubocop -a:

`  attribute :is_confirmed, &:is_confirmed?`
--------

## Expected behavior

It shouldn't break the logic (didn't think about possible solutions)

## Actual behavior

ArgumentError: wrong number of arguments (given 1, expected 0)
It passes extra parameter `{}` to ` is_confirmed?`

## Steps to reproduce the problem

Look at the desc

## RuboCop version
```
1.65.1 
```

**Comment by vlad-pisanov** [comment]
this very case is the reason why autocorrection is marked as unsafe:

https://docs.rubocop.org/rubocop/cops_style.html#safety-68

**Comment by koic** [comment]
Sure. Please consider using `rubocop:disable` directive or enabling `AllowComments: true` option to allow this:
https://docs.rubocop.org/rubocop/cops_style.html#allowmethodswitharguments-true

**Comment by Earlopain** [comment]
You probably mean `AllowMethodsWithArguments` :wink: (alternativly, adding this method to `AllowedMethods` should also work)
