### ISSUE TITLE
An ability to automatically put inline rubocop:disable in the code

### ISSUE THREAD

**Issue by zverok** [rubocop/rubocop#13205]
The use case is: there are many offenses that are impossible or undesirable to fix automatically. I would like to be able to automatically wrap them with `# rubocop:disable` / `# rubocop:enable`, or, when it is reasonable, cover with inline (just the same line) `# rubocop:disable`

Examples of situations:
* Rubocop gets updated and gets a useful new cop, which finds dozens of offenses in our codebase, or
* We decide to enable previously disabled cop, or lower its threshold (for metric-based cops), or change the preferred style, or expose to Rubocop the previously fully disabled legacy folder (or even a whole new app)

It is not always possible to fix them all at once. 

Inline disables might be preferable to ones in `.rubocop_todo.yml` (either put there with `--auto-gen-config` or manually) due to:
1. Visibility (a method with an inline disable for some metric stands out and implies it is “not the normal way for the rest of the codebase”)
2. A pressure on those who work with code (due to the visibility of the disable, they are forced to think whether it is necessary, and that maybe they require an explanation or fix)
3. Locality (in a big service, a couple of old/complex methods might have their metric cops disabled, while the rest should still comply—a simpler solution for [an old attempt](https://github.com/rubocop/rubocop/pull/8071) to “set metrics to a different value for a part of the code”)

Another kind of situation that can be helped by such a feature is when the disables are genuine: say, some new (or recently exposed to Rubocop) code has many `Rails/SafeHtml` offenses, I reviewed them and fixed those that were reasonable, and the rest is “how it should be” (no user-provided strings, just our internal helpers), and I just want a magic button to disable a dozen of them through several files :)

**Comment by Earlopain** [comment]
Would `rubocop --safe-auto-correct --disable-uncorrectable` help you out? This has some limitations: https://github.com/rubocop/rubocop/issues/7958. I think you are asking for the same/something similar as that issue?

**Comment by zverok** [comment]
@Earlopain Oh my. I should’ve checked the available options more thoroughly before asking. I had a suspicion it might be already present but brushed it off, thinking my demand was too exotic.

I’ll close this issue then. It seems that #7958 has already had a healthy discussion on extending the functionality.

Thank you!
