### ISSUE TITLE
`Style/MapIntoArray` autocorrection for `[].tap`

### ISSUE THREAD

**Issue by marocchino** [rubocop/rubocop#13229]
## Is your feature request related to a problem? Please describe.

I found the following abuse of tap and would like it to be auto-corrected to use map.
```rb
# bad
[].tap do |dest|
  src.each { |e| dest << e * 2 }
end

# good
src.map { |e| e * 2 }
```

## Describe the solution you'd like

-

## Describe alternatives you've considered

-

## Additional context

-

**Comment by vlad-pisanov** [comment]
Wow, this pattern seems to be ridiculously contrived, but a quick GitHub search proved me wrong. It's even used as an example in a "Ruby for Beginners" tutorial:

https://github.com/avsingh999/Ruby-for-Beginner/blob/72063113ffef3fc92f12b9d067c9af96e42a915d/Array_in_Ruby.md?plain=1#L58-L62
