### ISSUE TITLE
[Idea] rubocop to give speed-related hints, if the user / project wants this

### ISSUE THREAD

**Issue by rubyFeedback** [rubocop/rubocop#13240]
This is more of an idea; you guys are busy focusing on more important issues, such as bug
tracker, so I just keep this as an idea, and close it at once. That way people can read up on
past suggestions made and perhaps consider some of them in the long run.

I am not an expert in regards to rubocop, but I have used its autocorrect option to fix and
modernize old (ancient) ruby code in the past. For this it worked very well (some years ago),
and although not perfect, it did improve the code base automag(t)ically quite decently so.

So here I was thinking ... "what if rubocop ALSO gets a recommendation in regards to 
making ruby code faster?"

Now, this is difficult and I am not saying rubocop should be perfect. But simple things
such as:

     x = 'abc'
     d = x+'def'

versus

    x = 'abc'
    d = "#{x}def"

(Let's assume all Strings are not frozen, for the context of the above example.)

I believe the second variant is faster, as the + in the first example creates and allocates a new String
object, so that should be slower.

Rubocop could then give a warning such as:

    rubocop --give-speed-hints

"Line 345 contains an idiom that could possibly be made faster, via:
SHOW SYNTAX SUGGESTION HERE

So, extending rubocop a bit like the "did-you-mean" gem, but in regards
to speed and efficiency improvements.

The above is of course simple, but this could extend for a whole code base
eventually, where rubocop also extracts some more coordinated information
from that larger code base, and can then make some comments and
suggestions (this is the first step); but also then be used via autocorrect,
or perhaps let's call it autooptimise.

I am not suggesting this should be done all at once. I think it is best to
start SIMPLE, with simple, clear improvements; and then slowly build up
towards more optimisations, with more flexibility - a bit like the existing
cop rules work, just more in regards to optimisations.

I hope I could express the gist of my thought process here. Naturally this
may not be easy, but I think rubocop would really become more useful
if it also can optimise on speed-related issues - perhaps even on a C
code base or other languages, in regards to ruby.

**Comment by dvandersluis** [comment]
https://github.com/rubocop/rubocop-performance is what you are looking for here!
