### ISSUE TITLE
Fix Style/MethodCallWithArgsParentheses issue with return punning in guard

### ISSUE THREAD

**Issue by bkuhlmann** [rubocop/rubocop#13250]
## Expected behavior

Hello. :wave: I ran into an issue where, if using a `return` with punning within a guard statement, RuboCop will attempt to auto-correct the code which then leads to a Ruby 3.3.0 syntax error.

## Actual behavior

Here's the error I see:

``` 
snippet.rb:5:18: C: [Correctable] Style/MethodCallWithArgsParentheses: Omit parentheses for method calls with arguments. (https://rubystyle.guide#method-invocation-parens)
    return render("demo", users:) if users.any?
                 ^^^^^^^^^^^^^^^^
```

## Steps to reproduce the problem

Use the following configuration:

``` yaml
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
```

You can use the following code snippet to recreate the error:

``` ruby
# Save as `snippet.rb` and run as `rubocop snippet.rb`

module Demo
  def to_s
    return render("demo", users:) if users.any?

    "<p>None.</p>"
  end
end
```

If you were to remove the parenthesis from `render`, then you'd get a syntax error:

``` 
syntax error, unexpected end-of-input, expecting `end' or dummy end (SyntaxError)
```

If it helps, this is similar in nature to Issue [10317](https://github.com/rubocop/rubocop/issues/10317).

## RuboCop version

```
1.66.1 (using Parser 3.3.5.0, rubocop-ast 1.32.3, running on ruby 3.3.5) [arm64-darwin23.6.0]
  - rubocop-capybara 2.21.0
  - rubocop-packaging 0.5.2
  - rubocop-performance 1.22.1
  - rubocop-rake 0.6.0
  - rubocop-rspec 3.0.5
  - rubocop-thread_safety 0.5.1
```

**Comment by koic** [comment]
This bug has already been fixed in the latest development branch. Please wait for the next stable release. Thank you for your feedbak.

**Comment by bkuhlmann** [comment]
Ah, OK, thanks!
