### ISSUE TITLE
Don't warn about Layout/FirstMethodArgumentLineBreak for single-character method names

### ISSUE THREAD

**Issue by pdobb** [rubocop/rubocop#13286]
[Layout/FirstMethodArgumentLineBreak](https://docs.rubocop.org/rubocop/cops_layout.html#layoutfirstmethodargumentlinebreak) checks for a line break before the first argument in a multi-line method call. But, I argue that there should be exceptions. e.g.

```ruby
notice =
  t(   # <--- this line break is required by Layout/FirstMethodArgumentLineBreak
    "flash.successful_update_to",
    type: "username",
    to: current_user.display_name)
```
I often have to break my I18n.translate calls into multiple lines, but the `t(` having to be on its own line is just a waste of vertical space.

## Describe the solution you'd like

Either:
- Just always allow single-character methods
- Add an option to allow single-character methods
- Or, add an option to allow a list of method names, to which I can add `t`, `l`, and the like.

## Describe alternatives you've considered

Sometimes I'll try to disable Layout/FirstMethodArgumentLineBreak, but it makes for an extra long line (and I try to stick to 80 chars):

```ruby
notice =
  t("flash.successful_update_to", # rubocop:disable Layout/FirstMethodArgumentLineBreak
    type: "username",
    to: current_user.display_name)
```

And wrapping the method is just extra noisy:

```ruby
# rubocop:disable Layout/FirstMethodArgumentLineBreak
notice =
  t("flash.successful_update_to",
    type: "username",
    to: current_user.display_name)
# rubocop:enable Layout/FirstMethodArgumentLineBreak
```

So I usually just punt and obey the cop:

```ruby
notice =
  t(
    "flash.successful_update_to",
    type: "username",
    to: current_user.display_name)

```

**Comment by koic** [comment]
Considering cases like the one below, I have doubts about whether it makes sense to treat single-character names as a special case.

```ruby
t(
  'flash.successful_update_to',
  type: 'username',
  to: current_user.display_name
)
```

If it is written like the following, it loses the intent of keeping arguments on separate lines within parentheses, which affects the layout:

```ruby
t('flash.successful_update_to',
  type: 'username',
  to: current_user.display_name
)
```

This cop is disabled by default, and if intentionally enabled, I tend to think that, regardless of the length of the method name, we should respect consistency with "Checks for a line break before the first argument in a multi-line method call".

**Comment by pdobb** [comment]
I see. I think... I don't use that setting for keeping arguments on separate lines within parentheses. (I'm not sure what it's called.)

Note that Layout/FirstMethodArgumentLineBreak takes no sides on the final parentheses placement. From its documentation:

```ruby
# bad
method(foo, bar,
  baz)

# good
method(
  foo, bar,
  baz)
```

**Comment by pdobb** [comment]
Ok, so point taken that `Just always allow single-character methods` is a bad solution. That's what you're saying, yes?

**Comment by koic** [comment]
This is a concern about the design of the `Layout/FirstMethodArgumentLineBreak` cop (except other cops). 
If this were to be implemented, I think it should be a configuration option that is disabled by default. However, I’m not confident that treating single-character methods as special method names makes sense.

**Comment by dvandersluis** [comment]
IMO rather than adding a new configuration for this specific case, it'd make sense to use `AllowedMethods`/`AllowedPatterns` instead to make the cop ignore specified method names.

**Comment by pdobb** [comment]
@dvandersluis That's actually exactly what I was looking for! I didn't realize I could use `AllowedMethods` on any cop. I guess I thought it'd have to be listed in the ["Configurable attributes" section](https://docs.rubocop.org/rubocop/cops_layout.html#configurable-attributes-27) for the cop (which it isn't). Thanks! This does work (and was option number 3 in my list of possible solutions) so I'll close this ticket.

**Comment by dvandersluis** [comment]
@pdobb Each cop that uses `AllowedMethods` needs to be updated to do so, and `Layout/FirstMethodArgumentLineBreak` hasn't been, are you sure that you've fixed your issue? I was suggesting that we could add it to the cop instead of the more specific logic for single method names particularly.

**Comment by dvandersluis** [comment]
Looking at your config, you're not enabling the cop and it's not enabled by default.

**Comment by pdobb** [comment]
Oh, I see. I typoed the cop name so it broke rubocop and that's why the linter stopped showing the issue. Ok, thanks. Re-opeing :D
