### ISSUE TITLE
Autocorrect from `Layout/LineLength` can rewrite blocks into incompatible variants

### ISSUE THREAD

**Issue by Earlopain** [rubocop/rubocop#13299]
Reported in https://github.com/rubocop/rubocop/discussions/13294

## Expected behavior

```yml
AllCops:
  NewCops: enable

Style/FormatString:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Layout/LineLength:
  Max: 55
```

```rb
# frozen_string_literal: true

def foo(*, help:, **)
  pp help
end

foo :bar, :baaaaaaaaaaz, baaaaat: 'aaaaa',
                         help: 'Some text: %s' %
                               %w[foo bar].map { |v| v.upcase }.join(', ')
```

I expect the autocorrect to be safe.

## Actual behavior

`Layout/LineLength` triggers, rewriting the block to be multiline which somehow breaks things:

```rb
# frozen_string_literal: true

def foo(*, help:, **)
  pp help
end

foo :bar, :baaaaaaaaaaz, baaaaat: 'aaaaa',
                         help: 'Some text: %s' %
                               %w[foo bar].map do |v|
                                 v.upcase
                               end.join(', ')
# $ ruby test.rb
# "Some text: #<Enumerator:0x00007edb3df00518>"
# test.rb:11:in `<main>': undefined method `join' for an instance of String (NoMethodError)
#
#                                end.join(', ')
#                                   ^^^^^
```

Probably the ast has some different nesting levels. I am not quite sure.

## RuboCop version

```
$ [bundle exec] rubocop -V
1.66.1 (using Parser 3.3.5.0, rubocop-ast 1.32.3, running on ruby 3.3.5) [x86_64-linux]
```

**Comment by stdedos** [comment]
Even though it might be exactly the same thing, this is also an issue when not chaining:

```ruby
...
    empty = [[nil, nil]]
...
                                                  options: empty + Arr.all.map do |t|
                                                    [t.code, t.id.to_s]
                                                  end
...

# org.jruby.exceptions.TypeError: (TypeError) no implicit conversion of Enumerator into Array
```

PS: I tried with

```yaml
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
```

**Comment by dvandersluis** [comment]
Similar to #13096, this actually a bug in `Style/BlockDelimiters`, not `Layout/LineLength`. I opened #13544 to fix.

**Comment by stdedos** [comment]
I'll check it against the codebase in-question also, after https://github.com/rubocop/rubocop/discussions/13514 is figured out.

Those two I guess are the most critical issues "outside of one's control" (as in altering code logic, and making CI unstable) between https://github.com/rubocop/rubocop/issues/stdedos and https://github.com/rubocop/rubocop/discussions?discussions_q=is%3Aopen+author%3Astdedos+is%3Aunanswered+ (which are "still issues", but of a little-to-a-lot-more "fluid nature").
