### ISSUE TITLE
GuardClause / LineLength issue

### ISSUE THREAD

**Issue by theckman** [rubocop/rubocop#1332]
Considering the following Ruby snippet (which has already been indented a few levels):

``` Ruby
unless repo_has_team?(full_name, team[:id])
  return response.reply(t('repo_team_rm.exists', repo: full_name, team: team[:name]))
end
```

I get this while running Rubocop:

```
$ bx ruby --version
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
$ bx rubocop --version
0.26.0
$ bx rubocop -D
Inspecting 25 files
...C.....................

Offenses:

lib/lita/handlers/github_repo.rb:182:9: C: Style/GuardClause: Use a guard clause instead of wrapping the code inside a conditional expression.
        unless repo_has_team?(full_name, team[:id])
        ^^^^^^

25 files inspected, 1 offense detected
```

Trying to change it yields this code and then this error:

``` Ruby
return response.reply(t('repo_team_rm.exists', repo: full_name, team: team[:name])) unless repo_has_team?(full_name, team[:id])
```

```
lib/lita/handlers/github_repo.rb:182:121: C: Metrics/LineLength: Line is too long. [135/120]
        return response.reply(t('repo_team_rm.exists', repo: full_name, team: team[:name])) unless repo_has_team?(full_name, team[:id])
                                                                                                                        ^^^^^^^^^^^^^^^
```

Is this a known bug with the `GuardClause` cop? I saw another issue indicating that `GuardClause` should probably be disabled due to some quirks. Is this still recommended?

**Edit:** [.rubocop.yml](https://github.com/PagerDuty/lita-github/blob/0b18c2a5999695858cc218fbca7269be93d0fb25/.rubocop.yml)

**Comment by thomthom** [comment]
I'm running into this a few places in my source code when I raise errors:

```
    unless File.directory?(template_path)
      raise Skippy::Error, %(Template "#{options[:template]}" not found)
    end
```

Here `Style/GuardClause` clashes with `Metrics/LineLength:`. If I add a guard clause and make it all one line as Rubocop wants then I exceed the max line length.

It seems to me that `GuardClause` could benefit from a check to make sure it won't cause a violation of `LineLength` if enabled.

**Comment by theckman** [comment]
Hm. I'm not sure if I agree with `rubocop` making that assumption. Might the cleanest option be to disable either the `LineLength` or `GuardClause` linter inline in the impacted codebase?

* https://github.com/bbatsov/rubocop/blob/d5aa4db2e9fef64e3d78eabd727bfd5d998841a3/manual/configuration.md#disabling-cops-within-source-code

**Comment by thomthom** [comment]
For my projects I ended up disabling GuardClause all together. I didn't want to add too much Rubocop comments. From what I gather, to diable a cop for a single line it have to be at then end of the line - which in my case is already close to line length. I'd then have to disable on the line before and then enable on the line after - felt it quickly got messy.

Disabling GuardClause works fine by me, I typically have that worked into who I code any way. It just seemed to me that this particular cop conflicted too often with other rules.

**Comment by mikegee** [comment]
@thomthom `Metrics/LineLength` [has a configuration option](https://github.com/bbatsov/rubocop/blob/c820b4f181566b5f0f656edf17d5a6977ab0e94f/config/default.yml#L1227-L1229) to ignore those `# rubocop:disable` comments when calculating line length.
