### ISSUE TITLE
`Layout/LineContinuationLeadingSpace` has a autofix logic error

### ISSUE THREAD

**Issue by stdedos** [rubocop/rubocop#13320]
## Expected behavior

Describe here how you expected RuboCop to behave in this particular situation.

_Nothing_ - string-splitting is "well defined" at the `\n`, or

```ruby
eq(
  "    0:    1    2    3    4         5    6    7    8      \n    " \
  "8:    9   10   11   12        13   14   15   16      \n   " \
  '16:   17   18   19   20',
)
```

I would also **not force** changing the quotes here. "It doesn't look as pretty here".

## Actual behavior

Describe here what actually happened.
Please use `rubocop --debug` when pasting rubocop output as it contains additional information.

```ruby
eq(
  "    0:    1    2    3    4         5    6    7    8      \n    " \
  "8:    9   10   11   12        13   14   15   16      \n      " \
  '16:   17   18   19   20',
)
```

## Steps to reproduce the problem

This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.

```ruby
eq(
  "    0:    1    2    3    4         5    6    7    8      \n"\
  "    8:    9   10   11   12        13   14   15   16      \n"\
  "   16:   17   18   19   20"
)
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler.
If you see extension cop versions (e.g. `rubocop-performance`, `rubocop-rspec`, and others)
output by `rubocop -V`, include them as well. Here's an example:

```
$ [bundle exec] rubocop -V
1.66.1 (using Parser 3.3.5.0, rubocop-ast 1.32.3, analyzing as Ruby 3.3, running on ruby 3.3.5) [x86_64-linux]
  - rubocop-performance 1.22.1
  - rubocop-rspec 3.1.0
```

**Comment by stdedos** [comment]
The

> _Nothing_ - string-splitting is "well defined" at the `\n`,

is "a personal preference of mine". Call it a feature if you want.

I didn't get the exact intrinsics of `Layout` vs `Style` - maybe it is a feature too (and breaking change)

However, autofix **is wrong**:

![image](https://github.com/user-attachments/assets/3596f7e3-34e8-442a-965d-37ab064c4905)

That is a clear bug

**Comment by Earlopain** [comment]
If you want this to be understood as a clear bug, you need to change how you report these. Git diffs and unrunnable code snippets are not optimal. Instead show how it changes meaning:

```rb
puts "    0:    1    2    3    4         5    6    7    8      \n    " \
  "8:    9   10   11   12        13   14   15   16      \n      " \
  '16:   17   18   19   20'

    0:    1    2    3    4         5    6    7    8
    8:    9   10   11   12        13   14   15   16
      16:   17   18   19   20

========================================================================

puts   "    0:    1    2    3    4         5    6    7    8      \n"\
  "    8:    9   10   11   12        13   14   15   16      \n"\
  "   16:   17   18   19   20"

    0:    1    2    3    4         5    6    7    8
    8:    9   10   11   12        13   14   15   16
   16:   17   18   19   20
```

Indentation output changes.

**Comment by stdedos** [comment]
If I had just reported the string, then the indentation, given the `\` would've already disoriented the reader.

And if I wrote a whole `rspec` for it (hence the `eq`), it would not have been a _MWE_ from a repro standpoint.
I didn't know that there was a **requirement** for the code to be _executable_ - just valid Ruby

**Comment by stdedos** [comment]
All of the autofix bugs I have opened so far have been dealt in about 1d-2d time.

Is this perhaps forgotten @koic? 🙏

**Comment by dvandersluis** [comment]
FYI, the following configuration would probably give you the behaviour you're looking for here (keep string quotes consistent in a multiline string, and put spaces at the beginning of a string instead of the end in a continuation):

```yaml
Style/StringLiterals:
  ConsistentQuotesInMultiline: true

Layout/LineContinuationLeadingSpace:
  EnforcedStyle: leading
```

**Comment by stdedos** [comment]
> FYI, the following configuration would probably give you the behaviour you're looking for here (keep string quotes consistent in a multiline string, and put spaces at the beginning of a string instead of the end in a continuation):
> 
> ```yaml
> Style/StringLiterals:
>   ConsistentQuotesInMultiline: true
> 
> Layout/LineContinuationLeadingSpace:
>   EnforcedStyle: leading
> ```

Eeeh ... I'd have to evaluate what changes either does, if I really get into it.

Yes, in this case leading spaces would be best (and assuming `\n` is **not** considered space). But maybe the default looks better in other places.

This will probably be one disable I won't remove (if I was going to merge rubocop, which won't be happening apparently) - unless the block-style disable gets flagged as useless.
