### ISSUE TITLE
Improve CLI performance to be usable as autoformatter

### ISSUE THREAD

**Issue by thisismydesign** [rubocop/rubocop#13326]
## Is your feature request related to a problem? Please describe.

I want to use rubocop as an autoformatter such as prettier + eslint for JS which is super convenient. But the rubocop CLI is just too slow. Even on an M2 mac it's so significantly slow that it's a net distraction.

I did a bit of testing, trying to only run it w/o extensions, only enabling style & layout rules, etc. But essentially even in a simplest setup, literally ignoring every rule and every file the rubocop CLI takes ~1s to run vs 0.2s for ruby to run. Might be faster without docker but IMO the issue is the comparable slowness.

```sh
time docker-compose exec -T web echo hi
0.192 total

time docker-compose exec -T web ruby -e 'puts "Hello, world!"'
0.226 total

time docker-compose exec -T web bundle exec rubocop -c .rubocop.yml app/admin/clicks.rb
1.015 total
```

Where my rubocop.yml is:

```yml
AllCops:
  DisabledByDefault: true
  SuggestExtensions: false
  Exclude:
    - "**/*"
```

## Describe the solution you'd like

Would like a faster CLI, around 0.3s would be a good experience IMO. If that helps I would also be happy with a different "formatter-version" of the CLI that perhaps doesn't load all dependencies and just works for a subset of rules.

## Describe alternatives you've considered

Waiting 1s for a file to be saved in VSCode.

**Comment by Earlopain** [comment]
If you benchmark this, you will find that most of the time is spend `require`ing files, mostly all the various cops. RuboCop supports [Server Mode](https://docs.rubocop.org/rubocop/usage/server.html) which spawns a persistent process where most of that overhead disappears.

How you would integrate that into docker/compose, I am not sure. There will be a nice performance boost when Ruby 3.4 switches to the improved prism parser (I saw ~250ms better startup time on my machine) but other than that server mode is the solution.

**Comment by koic** [comment]
To speed up the execution of `rubocop` command from the terminal, you can use the `--server` option.
https://docs.rubocop.org/rubocop/1.66/usage/server.html

For running RuboCop via LSP in VS Code, you can use the built-in vscode-rubocop or shopify/ruby-lsp. 

- https://github.com/rubocop/vscode-rubocop
- https://github.com/Shopify/ruby-lsp

Please make use of these options.

**Comment by thisismydesign** [comment]
Thanks for the quick reply! Will try server mode. But looking at the config I provided isn't it an option to only require cops if they are enabled?

**Comment by Earlopain** [comment]
I'd like to look into this some day, but for now server mode will have to do. Loading code takes up the majority of boot time so there is not much else to optimize with a noticable impact (in regards to pure boot time that is). There are a few cops that are disabled by default that everyone pays the price for, or users that have a config similar to what you provided as an example where nothing is enabled.
