### ISSUE TITLE
Rails - rubocop doesn't like syntax for model scopes

### ISSUE THREAD

**Issue by kaldrenon** [rubocop/rubocop#373]
In my rails app, I have scopes that use the following syntax:

```
scope :foo, lambda { |f|
  where(condition: "value")
}
```

And when I rubocop my models, I get `C: Avoid using {...} for multi-line blocks.`

When I replace the `{...}` form with a `do..end` form, my scopes don't work.

**Comment by bishisht** [comment]
@jonas054 I am still experiencing this. I ran this through the code for https://github.com/VisitMeet/visitmeet and it showed me the error everyone is having here.

**Comment by jonas054** [comment]
@bishisht Please open a new issue with the details of your problem.
