### ISSUE TITLE
Generate Style Guide from .rubocop.yml

### ISSUE THREAD

**Issue by kmarsh** [rubocop/rubocop#379]
As our team is customizing rubocop to our tastes, we're essentially creating our own fork of the style guide. Wouldn't it be cool if we could generate a custom style guide document from the rules we've defined in `.rubocop.yml`?

This would probably require the `MSG`s in cops to be more verbose, with the relevant section of https://github.com/bbatsov/ruby-style-guide

**Comment by Supernats** [comment]
@bbatsov it's been a while since this was first brought up. Does it seem worthwhile to revisit for discussion?

**Comment by drn** [comment]
I'd love to see this happen + help start building this out. @bbatsov - if I start working on this, would you consider accepting the feature once it is ready?
