### ISSUE TITLE
Auto-linting bug on $? and $CHILD_STATUS

### ISSUE THREAD

**Issue by helloworlddan** [rubocop/rubocop#4097]
The autolinter currently changes $? to $CHILD_STATUS, which breaks on ruby-2.4.0. Maybe $CHILD_STATUS has been removed and/or is deprecated.

**Comment by bbatsov** [comment]
I'm guessing you failed to add `require 'English'` to your project.

**Comment by VivaLosDoyers** [comment]
I would argue that this shouldn't be an auto-corrected change.

This project should *strive* to cause zero breakage when auto-correcting.

**Comment by OddballGreg** [comment]
Just experienced this same issue in an automation script which sent out incorrect notifications as a result of this auto-corrected change.

As a longtime user of rubocop I've come to feel very safe in using the -a flag to resolve issues without breaking the code; so it came as very large surprise that the automatic change actively broke my script rather than just telling me what I'd need to fix the issue like other cops that have the potential of breaking functionality.

**Comment by marcandre** [comment]
Could we mark `Style/GlobalVars` as unsafe, or ideally add a `require 'english'` near the top of the file if it isn't there (or present in the Gemfile)? We should err on the side of caution.

**Comment by bbatsov** [comment]
I think we should aim for `require 'english'`. If I recall correctly we didn't do in the past, as typically projects tend to just require this once somewhere high up the load sequence, so it's available everywhere. Definitely the cop is unsafe for the vars in `English` in its current form.

**Comment by isaiahfrantz** [comment]
This is an incredibly annoying issue.
I love the auto refactoring that I get for free from rubocop but to modify code to depend on a gem and then not add the include is insane.
We are in the process of fixing up a bunch of puppet modules with the "pdk validate -a" command to auto correct a lot of simple formatting issues. It also refactors a bunch of ruby code in puppet facts and functions in real nice ways. We are left having to do extra manual work after we hit a puppet module that uses $? to check shell out exit codes or our code is broken :(
Seems like the proper thing to do is either auto add the include or dont do the refactor.

**Comment by marcandre** [comment]
PR welcome to add the `require`. It's [`require 'English'` with a capital 'E'](https://stackoverflow.com/questions/62648773/what-is-the-best-exit-status-check-command-that-works-in-rubocop-linux-and-wind?noredirect=1#comment111225673_62648773) btw.

**Comment by marcandre** [comment]
Note: cop has been marked as unsafe, so current RuboCop will not autocorrect it with `-a`, only with `-A`

**Comment by biinari** [comment]
I have a branch in the works to add the `require 'English'` on corrections for these global variables, just going to tidy it up before submitting a PR.
