### ISSUE TITLE
Cop for raise/fail arguments is too restrictive.

### ISSUE THREAD

**Issue by famished-tiger** [rubocop/rubocop#552]
For an expression like:
`fail(MyExceptionClass.new(some_exception_arg1,some_exception_arg1))`
Where:
- MyExceptionClass is a custom exception class.
- `some_exception_argX` are arguments of that exception class constructor.

Rubocop will report an offence like:
... C: Provide an exception class and message as arguments to fail.
`fail(UnreachableSubstepArgument.new(substep_arg))`

This is problematic because:
-When one raises an Exception it is a good programming practice to provide as much context data as needed for a proper understanding. Restricting the calls to  `fail/raise`  to an exception class plus a message argument limits the kind of  feedback you can provide upon raising an exception.
-Furthermore, calling fail/raise with an exception object is perfectly legal Ruby:
"if raise is called with a single Exception object as its argument, it raises that exception". Sentence taken from: page 157 of  "The Ruby Programming Language" of D. Flanagan & Yukihiro Matsumoto, O'Reilly 2008 ISBN 978-0-596-51617-8.

**Comment by AlexCppns** [comment]
I don't understand why rubocop finds an offense there:

```
Provide an exception class and message as arguments to raise.
    raise ActionController::RoutingError.new('Not Found')
```

**Comment by jonas054** [comment]
@AlexCppns It wants it to be
```ruby
raise ActionController::RoutingError, 'Not Found'
```
This is the `exploded` style. Your example would be allowed with the setting
```yaml
Style/RaiseArgs:
  EnforcedStyle: compact
```

**Comment by mattdowdell** [comment]
@bbatsov A bit of an edge case, but rubocop finds an offence with something like the following as well:

```ruby
args = [message, other_arg_1, other_arg_2]
raise MyError.new(*args)
```

**Comment by jonas054** [comment]
@mattdowdell An edge case, yes. But still a bug since `raise MyError, *args` doesn't work if `args` has multiple elements. Can you open a separate issue for it?

**Comment by mattdowdell** [comment]
@jonas054 Opened at #3577. I'm not entirely sure what the expected behavior of `raise MyError, *args` should be as I'm relatively new to ruby. Would you be able to clarify what you meant in the new issue?
