### ISSUE TITLE
Rubocop runs very slowly

### ISSUE THREAD

**Issue by osdiab** [rubocop/rubocop#584]
Hi,

I'm using JRuby v 1.7.5 and the latest version of rubocop. I have a very simple Ruby file, less than 30 lines. The only complaints rubocop has are ~8 non-snake cased symbols.

But running rubocop consistently takes me on the order of 6-7 seconds just to scan that file - `rubocop app.rb`. After ~4-5 seconds running it from terminal, it tells me that it's inspecting 1 file; and then it spends another 2-3 seconds before showing me the results.

Since I use Syntastic in vim, it causes vim to lock up every time I save the file.

Am I doing something wrong? I literally just installed the gem and executed it on the file, nothing else. Thanks!

**Comment by kazhian** [comment]
Any suggesion for Ruby? I face the slowness.
