### ISSUE TITLE
--no-parallel (-P/--parallel can not be combined with --auto-correct.)

### ISSUE THREAD

**Issue by kwerle** [rubocop/rubocop#7544]
We just discovered --parallel and added it to our .rubocop file.  Turns out you can't use it with -a.

We would like to leave --parallel in our .rubocop file but would occasionally like to use -a.  So we would like a --no-parallel flag to override our default - so we can do
`rubocop --no-parallel -a`

**Comment by marcandre** [comment]
That, or CLI switches automatically override config settings in those cases.

**Comment by kwerle** [comment]
PR soon

**Comment by marcandre** [comment]
Is there a good reason for --parallel to not work with -a?
