### ISSUE TITLE
Autocorrect renamed cops

### ISSUE THREAD

**Issue by micahbf** [rubocop/rubocop#8015]
## Is your feature request related to a problem? Please describe.

I recently updated rubocop in a project for the first time in awhile, and got a bunch of renamed cop errors. It was a pain to go through and fix these. I ended up parsing the rubocop error output and turning that into a `sed` script, and then running that script against the codebase.

## Describe the solution you'd like

A rubocop command to autofix renamed cops. (Or include it in `--safe-auto-correct`).

As auto-correctable things go, this one (from a naive perspective) seems easy.

Additionally, this error is one that is "rubocop's fault," not the user's, so it would be especially nice to have an easy fix and reduce the friction of updating rubocop.

## Describe alternatives you've considered

Aforementioned sed-script-that-generates-a-sed-script

## Additional context

**Comment by koic** [comment]
JFYI, there is Mry as a third party cop name migration tool.
https://github.com/pocke/mry

**Comment by micahbf** [comment]
Thank you for the tip, I'll definitely use that next time!

Is there any interest in integrating this, or similar functionality, into core rubocop?

**Comment by koic** [comment]
The upcoming RuboCop 1.0 is expected to be more stable than it is now. Therefore, there are no plans to include this migration feature to the core feature now. So, the migration is supposed to be transient and relies on Mry gem.
