### ISSUE TITLE
Layout/ArgumentAlignment vs Layout/HashAlignment

### ISSUE THREAD

**Issue by zverok** [rubocop/rubocop#8032]
I am not sure it is a bug per se, but it is sure perceived as one.

In our codebase, we have `Layout/ArgumentAlignment` turned on, and `Layout/HashAlignment` turned **off** (the reason of the latter is like I describe in #7880: our preferred style is `EnforcedColonStyle: key`, but from time to time it is necessary to have a hash with `EnforcedColonStyle: table` or `EnforcedColonStyle: separator` -- especially in constants, where "how the constant looks" is important for grasping the meaning).

Now, (after autofixing `Layout/LineLength`, but the same could've happened on manual editing) I have code elements looking like this:
```ruby
            create(:edit_rating, transcription_job: transcription_job, work_type: 'review', user: reviewer, stars: 5,
created_at: 1.month.ago)
```
(note the second line).

Maybe it is just me, but I honestly expected `Layout/ArgumentAlignment` to fix this, and only after debugging into Rubocop's sources I understood why it does not (because all arguments to the method except `:edit_rating` considered one hash by the parser, and their alignment to be `HashAlignment`'s responsibility).

But even if I turn `HashAlignment` on, the proposed alignment would be this:
```ruby
            create(:edit_rating, transcription_job: transcription_job, work_type: 'review', user: reviewer, stars: 5,
                                 created_at: 1.month.ago)
```
...while looking at them as a separate arguments, one might expect those (depending on `ArgumentAlignment` settings):

```ruby
            create(:edit_rating, transcription_job: transcription_job, work_type: 'review', user: reviewer, stars: 5,
                   created_at: 1.month.ago)
# or
            create(:edit_rating, transcription_job: transcription_job, work_type: 'review', user: reviewer, stars: 5,
              created_at: 1.month.ago)
```

Could it be reasonable to complicate `ArgumentAlignment` a bit to treat no-braces hash as a separate arguments?

```
$ [bundle exec] rubocop -V
0.84.0 (using Parser 2.7.1.2, rubocop-ast 0.0.3, running on ruby 2.6.3 x86_64-linux)
```

**Comment by ioquatix** [comment]
I agree this is a good idea and I ran into the same problem.

This is my current configuration:

```
Layout/HashAlignment:
  Enabled: true
  EnforcedLastArgumentHashStyle: ignore_implicit
Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation
```

My test case looks like this:

``` ruby
foo(10, foo: 0,
        bar: 10,
        baz: 20
)
```

Given my configuration, I expected this:

``` ruby
foo(10, foo: 0,
  bar: 10,
  baz: 20
)
```

However, it doesn't matter, in all cases, the alignment is untouched... even if the input was:

```ruby
foo(10, foo: 0,
                      bar: 10,
        baz: 20
)
```

It is not fixed.

**Comment by mainameiz** [comment]
+1
