### ISSUE TITLE
Old specs need love

### ISSUE THREAD

**Issue by marcandre** [rubocop/rubocop#8127]
Many cop specs still use `inspect_source` or `autocorrect_source`. We'll like to deprecated this (see #8003), so they should be refactored to use `expect_offense` + `expect_correction` instead (I'd love to have an even nicer API for this).

**Comment by rrosenblum** [comment]
Some of these are much easier to convert than others. Some of the tests are as easy as merging an inspect test with and autocorrect test and rewriting a couple of lines. 

The tests that make use of `shared_examples` will likely need to be rewritten to not use example groups. Since the code is dynamic, you likely won't be able to get the highlighting to work in a clean way.

I haven't found a way to use `expect_offense` on any test that points to blank line. `expect_offense` doesn't have a way to process highlight that doesn't really point to anything https://github.com/rubocop-hq/rubocop/blob/3b0552b9989db97104cfe0fc30515e9b6ae549f2/spec/rubocop/cop/layout/empty_lines_around_method_body_spec.rb#L42-L51

```ruby
  it 'registers an offense for class method body starting with a blank' do
    expect_offense(<<~RUBY)
      def Test.some_method

      ^ Extra empty line detected at method body beginning.
        do_something
      end
    RUBY
  end
```
```shell
Failures:

  1) RuboCop::Cop::Layout::EmptyLinesAroundMethodBody registers an offense for class method body starting with a blank
     Failure/Error: expect(actual_annotations.to_s).to eq(expected_annotations.to_s)

       expected: "def Test.some_method\n\n^ Extra empty line detected at method body beginning.\n  do_something\nend\n"
            got: "def Test.some_method\n\n Extra empty line detected at method body beginning.\n  do_something\nend\n"

       (compared using ==)

       Diff:
       @@ -1,6 +1,6 @@
        def Test.some_method

       -^ Extra empty line detected at method body beginning.
       + Extra empty line detected at method body beginning.
          do_something
        end

     # ./lib/rubocop/rspec/expect_offense.rb:125:in `expect_offense'
     # ./spec/rubocop/cop/layout/empty_lines_around_method_body_spec.rb:43:in `block (2 levels) in <top (required)>'

Finished in 0.04196 seconds (files took 1.03 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/rubocop/cop/layout/empty_lines_around_method_body_spec.rb:42 # RuboCop::Cop::Layout::EmptyLinesAroundMethodBody registers an offense for class method body starting with a blank
```

I think there might be a couple of other oddities to work through in order to convert everything. It's been a while since I worked on converting tests. 

It might be worth while to document some of the tricks to handling white space and interpolation with different types of HEREDOCS. For instance, 

```ruby

    <<~RUBY
      puts 'foo' +
           "#{bar}"
      puts 'a' +
        'b'
      "#{c}"
    RUBY

# vs

    # The markdown syntax highlighting is incorrect here. 
    # This does not actually perform string interpolation
    <<~'RUBY'
      puts 'foo' +
           "#{bar}"
      puts 'a' +
        'b'
      "#{c}"
    RUBY
```

**Comment by marcandre** [comment]
> The tests that make use of `shared_examples` will likely need to be rewritten to not use example groups. Since the code is dynamic, you likely won't be able to get the highlighting to work in a clean way.

Like which one?

We introduced `^{label}` and `_{label}` to ease variable length matchers

**Comment by tejasbubane** [comment]
@marcandre I am willing to take some of this refactoring work. What would you prefer of the following?

1. Separate PRs each with 2-3 cops' specs refactored - easy to review - don't worry about git history.

2. Club all `Style` cops into one PR, `Lint` in another, so on.. - pain to review - will keep git history clean.

Or anything else?

**Comment by marcandre** [comment]
Either work, I'd say group them as you like.

**Comment by koic** [comment]
I'm not sure if it could be a hint,  the following is an examples that PRs were split into A-Z and opened in the past.
#5134, #5132, #5131, #5130, and #5129.

**Comment by biinari** [comment]
Some new syntax of use here:

* `^{}` to mark an offense on an empty line (added in #8255)
* `[...]` to abbreviate offense messages (added in #8297)

**Comment by biinari** [comment]
I'm planning to pick up some more of these this weekend, to pick up the ones I missed in the `Lint` namespace and make a start on the `Style` namespace (probably A-M split over 2 or 3 PRs).

**Comment by mechos3d** [comment]
Hi all! 
I'm planning to refactor all the `Layout` namespace specs if it's OK :)

**Comment by biinari** [comment]
I'm picking up the rest of the `Style` namespace cops this week as I have a bit of free time.

**Comment by AndreiEres** [comment]
I ran into a problem while I was working on the task. I can't understand how to implement `expect_offense` for missing final newline.

To throw an error I've written a wrong spec
```
expect_no_offenses(<<~RUBY.chomp)
  puts 'testing rubocop when final new line is missing
                            after block comments'

  =begin
  first line
  second line
  third line
  =end
RUBY
```

The error was
```
-=end
+=end    ^{} Final newline missing.
```

So if I'll write `=end    ^{} Final newline missing.` in spec it won't caught. If I move error message to next line error will disappeared because we will have the newline. 

Have anybody already met the problem? Is there a solution or do we have to enhance parser?

**Comment by marcandre** [comment]
@AndreiEres  Good point. You are right, I don't think there's a way around this one. We could add some functionality to `expect_offense` but since this case is very rare, probably best to leave it as is.

**Comment by mechos3d** [comment]
I have a solution for it, but life happened and didn't create a PR with it yet.            
I created a separate matcher `expect_newline_offense` that works like this:
```
expect_newline_offense("#{str}=end", <<~RUBY)
  #{str}=end
      ^{} Final newline missing.
RUBY
```
But @marcandre is right in that it's a very rare case - so I was hesitant wether this matcher is worth adding or not.

**Comment by marcandre** [comment]
If you have something that works @mechos3d, we can definitely include it.
Another "sneaky way" might be to check if the string we're being passed is missing a newline at the end, and if so reproduce that when we extract the failure messages. That might even be simpler.

**Comment by AndreiEres** [comment]
So I've used error raising in https://github.com/rubocop-hq/rubocop/pull/9263 because that is built-in and needn't additional helpers. Thus we've completed with using `inspect_source` (if you accept PR of course).

**Comment by AndreiEres** [comment]
Could you tell me, please? What can we do with old syntax in that files?
spec/support/alignment_examples.rb
spec/support/multiline_literal_brace_layout_trailing_comma_examples.rb

**Comment by AndreiEres** [comment]
> Could you tell me, please? What can we do with old syntax in that files?
> spec/support/alignment_examples.rb
> spec/support/multiline_literal_brace_layout_trailing_comma_examples.rb

@marcandre

**Comment by marcandre** [comment]
> spec/support/multiline_literal_brace_layout_trailing_comma_examples.rb

I don't see an issue. If the failure message is different, ` ^{foo} [...]` should match any failure with indent with the length of `foo`.

> spec/support/alignment_examples.rb

I don't see an issue, the two cases should be combined and `expect_correction` used instead of `autocorrect_source`.

Or am I missing something?

**Comment by AndreiEres** [comment]
> Or am I missing something?

I mean if there are no issues could we close the issue?

**Comment by marcandre** [comment]
There are still 4 uses of `autocorrect_source` and 1 of `inspect_source` in the specs that would ideally be removed

**Comment by biinari** [comment]
I'll tackle these last ones if no objections, I think they should pretty reasonable to finish off. Sorry I've been absent from this for a long while, life happened.

```
spec/support/alignment_examples.rb
spec/support/multiline_literal_brace_layout_trailing_comma_examples.rb
```

**Comment by rrosenblum** [comment]
This is amazing that we finally get to close this out! This spec conversion has been years in the making. Great job everyone that helped out!
