### ISSUE TITLE
No such file

### ISSUE THREAD

**Issue by Nostlagia** [rubocop/rubocop#8219]
Hi !
When I use the command `rubocop '#{repository}' --format json`, I find it reports " Errno::ENOENT - No such file or directory - rubocop 'TestThirdGithubApp' --format json" error. How could I fix it? 
Best wishes

**Comment by jonas054** [comment]
This looks like a problem that arises in the environment where the command is called, not inside RuboCop. So it doesn't really belong here. Closing.
