### ISSUE TITLE
Spell checking of Rubocop

### ISSUE THREAD

**Issue by agrimm** [rubocop/rubocop#846]
I'm tempted to add some sort of automated spell checking of Rubocop. Ideally, something that could check the spelling of comments, variable names, class names, and documentation. I'd only use off-the-shelf tools, not try to build my own tool.

Before looking into it any further, do you (the core team) have any spell checking tools that you're already using for Ruby projects that you'd prefer to be used in this project?

**Comment by JelF** [comment]
Was it done?

**Comment by bbatsov** [comment]
Nope.

**Comment by agrimm** [comment]
I haven't done any work on this since my last comment in October 2014, and I don't foresee working on it in the future.
