### ISSUE TITLE
New cop: Layout/SpaceAroundSingletonInheritence

### ISSUE THREAD

**Issue by alex-damian-negru** [rubocop/rubocop#8469]
## Is your feature request related to a problem? Please describe.

One could write

```ruby
class<<self
```

which isn't as readable as adding spaces around the `<<` operator:

```ruby
class << self
```

## Describe the solution you'd like

There should be a layout cop that checks whether there are spaces around the `<<` operator for singleton class inheritence.

## Describe alternatives you've considered

-

## Additional context

-

**Comment by jonas054** [comment]
As per the discussion in #9906 we view the missing inspection as a bug.
