### ISSUE TITLE
Ignore Rubocop Errors

### ISSUE THREAD

**Issue by nayefc** [rubocop/rubocop#849]
How can I ignore certain Rubocop errors? I am trying to ignore this one for example:

```
Method has too many lines. [11/10]
```

Is there a way to reference that error in some dot file? Note that I am running it in Emacs using Flycheck.

Thanks,

**Comment by georgemillo** [comment]
For further reference, the new link for "Disabling Cops Within Source Code" in @jonas054's post is [here](https://rubocop.readthedocs.io/en/latest/configuration/#disabling-cops-within-source-code)

**Comment by natakina** [comment]
> For reference, if anyone else stumbles upon this, the name of the cop is `MethodLength`.
> 
> You can disable it in the code with:
> 
> ```ruby
> # rubocop:disable MethodLength
> def foo
>   # ...
> end
> ```

In the end of method we also need to add comment # rubocop:enable MethodLength
