### ISSUE TITLE
String ConcatenationCop failed while inspecting file

### ISSUE THREAD

**Issue by fynsta** [rubocop/rubocop#8647]
I upgraded to RuboCop 0.90 and had it inspect my files. In one of them it raised an error: 
I think it is because of a double string interpolation.

The code in question:
`header = { 'Authorization': "Basic #{Base64.encode64("appname:#{api_user_password}").delete("\n")}" }`

Since this code is working the way it should, I am suspecting a bug in RuboCop.
The error was raised on the quotation mark in the column where the string "appname..." begins.

Important information
> 0.90.0 (using Parser 2.7.1.4, rubocop-ast 0.3.0, running on ruby 2.6.1 x86_64-darwin18)

**Comment by dvandersluis** [comment]
What was the error you got?

**Comment by fynsta** [comment]
It said

> An error occured while inspecting '...'

When I ran `rubocop -d` to investigate, the error did not occur again. Neither did it on subsequent runs.

**Comment by dvandersluis** [comment]
I can't replicate this (either with autocorrect on or off). Can you try running rubocop without the cache enabled and see if the error returns? (`rubocop -C false`)

**Comment by fynsta** [comment]
Interestingly, it still did not show up. Weird...
Also, I should mention that the error occured when running `rubocop -A`

**Comment by dvandersluis** [comment]
Not sure what can be done without more details. Maybe close this issue and reopen with a backtrace if it happens again?

**Comment by fynsta** [comment]
Okay I'll do that. It's not that bad of a bug, just wanted to let you know!
