### ISSUE TITLE
Rainbow + warn method exception in jRuby

### ISSUE THREAD

**Issue by AquisTech** [rubocop/rubocop#8689]
Rubocop throws error when executed on jRuby environment.
```
$ rubocop
wrong argument type Rainbow::NullPresenter (expected String)
org/jruby/common/RubyWarnings.java:224:in `warn'
org/jruby/RubyKernel.java:1247:in `warn'
org/jruby/RubyKernel.java:1234:in `warn'
C:/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rubocop-0.90.0/lib/rubocop/config_loader.rb:154:in `warn_on_pending_cops'
C:/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rubocop-0.90.0/lib/rubocop/config_loader.rb:111:in `block in configuration_from_file'
org/jruby/RubyKernel.java:1871:in `tap'
C:/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rubocop-0.90.0/lib/rubocop/config_loader.rb:110:in `configuration_from_file'
C:/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rubocop-0.90.0/lib/rubocop/config_store.rb:58:in `for_dir'
C:/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rubocop-0.90.0/lib/rubocop/config_store.rb:37:in `for_pwd'
C:/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rubocop-0.90.0/lib/rubocop/cli.rb:124:in `apply_default_formatter'
C:/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rubocop-0.90.0/lib/rubocop/cli.rb:40:in `run'
C:/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rubocop-0.90.0/exe/rubocop:13:in `block in <main>'
C:/jruby-9.2.6.0/lib/ruby/stdlib/benchmark.rb:308:in `realtime'
C:/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rubocop-0.90.0/exe/rubocop:12:in `<main>'
org/jruby/RubyKernel.java:1008:in `load'
C:\jruby-9.2.6.0\bin\rubocop:23:in `<main>'
```

--------

## Expected behavior

Rubocop should inspect files

## Actual behavior

Rubocop fails with exception trace

## Steps to reproduce the problem

Execute `rubocop` from terminal on jRuby environment.

## RuboCop version

```
$ rubocop -V
0.90.0 (using Parser 2.7.1.4, rubocop-ast 0.3.0, running on jruby 2.5.3 java)
```
## jRuby version
```
$ jruby -v
jruby 9.2.6.0 (2.5.3) 2019-02-11 15ba00b Java HotSpot(TM) 64-Bit Server VM 25.251-b08 on 1.8.0_251-b08 +jit [mswin32-x86_64]
```

-----------------

## Debugging information

Following is the code that breaks
```
warn Rainbow(PENDING_BANNER).yellow
```
My analysis is, `warn` method is not able to handle `Rainbow::NullPresenter` instance which is returned by `Rainbow(PENDING_BANNER).yellow` 

I read one comment [here](https://github.com/rubocop-hq/rubocop/pull/6845/files#r266835554) where @koic applied `to_s` to handle this error.

Similar code is present in many places in Rubocop. Should I go ahead and fix those places using `to_s` and give a pull-request? Or please suggest some elegant way to handle it?

**Comment by marcandre** [comment]
Has an issue been opened with JRuby?

**Comment by AquisTech** [comment]
> Has an issue been opened with JRuby?

Nope.
I will do it too.

**Comment by koic** [comment]
I'm going to close this issue because JRuby 9.2 is no longer runtime supported.
