### ISSUE TITLE
Style/RedundantFreeze and string literals

### ISSUE THREAD

**Issue by marcandre** [rubocop/rubocop#8703]
Interpolated string literals will no longer be frozen in Ruby 3.0: https://bugs.ruby-lang.org/issues/17104#note-16

The cop `Style/RedundantFreeze` will need to exclude those.

**Comment by FnControlOption** [comment]
https://github.com/rubocop/rubocop/pull/10006 replaced https://github.com/rubocop/rubocop/pull/8743 and is merged, so this can be closed now, I think.
