### ISSUE TITLE
Symlink from Yarn Link causes infinite loop or recursion in processing exclude files

### ISSUE THREAD

**Issue by justin808** [rubocop/rubocop#9048]
On the current rubocop (not in some older versions), the exclude pattern of `node_modules` or `node_modules would prevent the digging into that directory. With a yarn link to a parent folder (see https://github.com/shakacode/react_on_rails/tree/master/spec/dummy), rubocop post v1 just hangs.

--------

## Expected behavior

Not hang!

## Actual behavior

This hangs when rubocop is run from the spec/dummy folder of the gem react_on_rails.

The reason is the symlink from running yarn link react-on-rails.

I'd like to just exclude the node_modules directory, but there seems no way to prevent the current rubocop from digging into it.

```
rubocop --debug .                                                                   ✖ ✹ [23:10:54]
For /Users/justin/shakacode/react-on-rails/react_on_rails/spec/dummy: configuration from /Users/justin/shakacode/react-on-rails/react_on_rails/spec/dummy/.rubocop.yml
Inheriting configuration from /Users/justin/shakacode/react-on-rails/react_on_rails/.rubocop.yml
Default configuration from /Users/justin/.rvm/gems/ruby-2.7.2@rails6/gems/rubocop-1.2.0/config/default.yml
AllCops/Exclude configuration from /Users/justin/shakacode/react-on-rails/react_on_rails/.rubocop.yml
```

## Steps to reproduce the problem

```
react_on_rails/spec/dummy (justin808/fix-tests u+1) ✗ yarn link react-on-rails
success Using linked package for "react-on-rails".
✨  Done in 0.07s.
react_on_rails/spec/dummy (justin808/fix-tests u+1) ✗ ls -l node_modules/react-on-rails
lrwxr-xr-x  1 justin  staff  50 Nov 13 23:07 node_modules/react-on-rails -> ../../../../../../.config/yarn/link/react-on-rails

 ✗ ls -l ~/.config/yarn/link/react-on-rails
lrwxr-xr-x  1 justin  staff  48 Jul  4  2017 /Users/justin/.config/yarn/link/react-on-rails -> ../../../shakacode/react-on-rails/react_on_rails
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ [bundle exec] rubocop -V
1.2.0 (using Parser 2.7.2.0, rubocop-ast 1.1.1, running on ruby 2.7.2 x86_64-darwin19)
```

## Workaround

Run `yarn unlink react-on-rails` in the `spec/dummy` directory of https://github.com/shakacode/react_on_rails before running rubocop.

**Comment by jonas054** [comment]
I cannot reproduce the problem on the current RuboCop (1.25.1) and the current react-on-rails (13.0.1).

**Comment by koic** [comment]
Due to a lack of activity, I'll close this issue. If the problem continues with the latest RuboCop, please feel free to reopen it with additional information.
