### ISSUE TITLE
Autocorrect bug: Move include to the class declaration line

### ISSUE THREAD

**Issue by effetmonstre** [rubocop/rubocop#9203]
<img width="700" alt="Screen Shot 2020-12-09 at 9 40 45 AM" src="https://user-images.githubusercontent.com/60717156/101644218-ef0ec400-3a02-11eb-811d-a40e98fa72f5.png">

The auto correction moves the 'include ConcernName' to the same line as the class declaration.

In this case, the correction was 

```
# rubocop:disable Metrics/ClassLength
Unnecessary disabling of Metrics/ClassLength
```

## RuboCop version

```
$ [bundle exec] rubocop -V
0.93.1 (using Parser 2.7.2.0, rubocop-ast 0.7.1, running on ruby 2.7.1 x86_64-darwin20)
```

**Comment by koic** [comment]
I cannot reproduce this issue. Can you update to the latest RuboCop (1.6.1) and please provide reproduction step if you reproduce this issue with the latest version of RuboCop?

**Comment by Darhazer** [comment]
I confirm that this was happening with 0.93.1 indeed (the inheritance was necessary condition), but it doesn't happen on the current version 1.31. While it's hard to tell in which exact version this was fixed, this can now be closed
