### ISSUE TITLE
Ability to disable cop for next line

### ISSUE THREAD

**Issue by difernandez** [rubocop/rubocop#9505]
## Problem

When disabling a cop, we have two options, each with something I consider a problem:
- Disabling a cop for a line with a comment at the end of it. Sometimes this results in a line that is too long and it's uncomfortable to read
- Disabling a rule in a block using `rubocop:disable` and `rubocop:enable`. This could be cumbersome if I want to disable for a single line

## Solution

I think a directive to disable the next line would be good, similar to what [eslint has](https://eslint.org/docs/2.13.1/user-guide/configuring#disabling-rules-with-inline-comments). It could be `rubocop:disable:next-line` or `rubocop:disable-next-line` for example

## Additional context

There's already [an old closed issue](https://github.com/rubocop-hq/rubocop/issues/4569) regarding this topic, sorry for the duplicate. I would like to know if there's support for a feature like this and/or if the rubocop team would still be willing to review a PR for this.

**Comment by rrosenblum** [comment]
Thanks for linking to the old topic on this. Eslint uses a disable next line syntax, `// eslint-disable-next-line`, https://eslint.org/docs/user-guide/command-line-interface#-no-inline-config. We would also need to support todo next line.

**Comment by AndreiEres** [comment]
So, I try to implement it in direct way https://github.com/rubocop/rubocop/pull/9559

_Direct_ means I just add new lines to code. And now it seems to be too big class.

**Comment by difernandez** [comment]
wow thanks a lot for submitting a PR for this, great work! Hope it gets reviewed by someone on the rubocop team

**Comment by AndreiEres** [comment]
Guys, please, don't review my PR until I've done with refactoring at https://github.com/rubocop/rubocop/issues/9563. This PR depends of a class I refactor.

**Comment by AndreiEres** [comment]
Looks like we are able to introduce that feature with https://github.com/rubocop/rubocop/pull/9559

- Added checking for disable-next-line to DirectiveComment
- Added ability to disable cops on next line with directive comment to CommentConfig
- Added notes about feature to docs

@bbatsov and other, could you have a look?

**Comment by bbatsov** [comment]
Closing because the proposed solution seems too specific to me, and I'd prefer some more generic approach to the problem. See my comments on #9559 for details.

**Comment by DeflateAwning** [comment]
Was there ever a solution accepted for this problem?

**Comment by celsoMartins** [comment]
Was the issue closed and no capacity was added?

The code would look much cleaner and clever than this:

```
module DeviseCustom
  class SessionsController < Devise::SessionsController
    # rubocop:disable Rails/LexicallyScopedActionFilter
    skip_before_action :verify_authenticity_token, only: %i[create new]
    # rubocop:enable Rails/LexicallyScopedActionFilter

    def destroy
      signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
      set_flash_message! :notice, :signed_out if signed_out
      yield if block_given?
      respond_to_on_destroy
    end

    private

    def respond_to_on_destroy
      respond_to do |format|
        format.all { redirect_to root_path(format: :html) }
      end
    end
  end
end
```

**Comment by stdedos** [comment]
Even if an inline-disable comment is an acceptable solution for one-line disables, it still has the following limitations:

There is no way to add a comment:
I cannot explain the `# rubocop:disable Layout/SpaceBeforeBrackets` disable like
"`# rubocop:disable Layout/SpaceBeforeBrackets # RuboCop sees ghosts which don't exist`
(see: last line of https://docs.rubocop.org/rubocop/configuration.html#disabling-cops-within-source-code)

I cannot track when this disable is not valuable anymore (i.e. https://github.com/rubocop/rubocop/issues/13037)

I cannot leave a comment like:
`# rubocop:disable Layout/SpaceBeforeBrackets # ToDo: Remove this when https://github.com/rubocop/rubocop/issues/13356 is released`
(_see above_)

Sorry for the necro-post - but OTOH opening a "new" issue about this is going to be futile :pray:
