### ISSUE TITLE
Ability to use wildcards when disabling cops

### ISSUE THREAD

**Issue by unikitty37** [rubocop/rubocop#9519]
## Is your feature request related to a problem? Please describe.

When it is necessary to write a method that RuboCop decides is too complex, it tends to trigger multiple cops. If there is no easy way to rewrite the method in a reasonable amount of time, it is necessary to disable multiple cops on one line:

```
def complex_method # rubocop:disable Metrics/AbcSize, Metrics/CyclomaticComplexity, Metrics/MethodLength, Metrics/PerceivedComplexity
```

This is a lot of typing! However, disabling *all* cops for the method with a simple `rubocop:disable` is overkill.

## Describe the solution you'd like

It would be useful to have wildcard support:

```
def complex_method # rubocop:disable Metrics/*
```

or

```
def complex_method # rubocop:disable Metrics
```

(arguably, the first is more explicit and guards against typos better)

## Describe alternatives you've considered

Obviously, I considered breaking the method down into simpler code 😁 , but it doesn't seem to be particularly easy in this case, and the required dev time is a factor.

Supporting bash-style globbing would be nice, but would probably be a lot more hassle to implement for something that only makes the line slightly shorter:

```
def complex_method # rubocop:disable Metrics/{AbcSize,CyclomaticComplexity,MethodLength,PerceivedComplexity}
```

Ideally, it would be possible to define groups in `rubocop.yml`, and then disable those:

```
Groups:
  ComplexityChecks:
    - Metrics/AbcSize
    - Metrics/CyclomaticComplexity
    - Metrics/MethodLength
    - Metrics/PerceivedComplexity
```

```
def complex_method # rubocop:disable Groups/ComplexityChecks
```

but I suspect that will be a lot of work to implement, and I'm not sure if there's enough demand for this feature to justify it.

## Additional context

none

**Comment by koic** [comment]
> `def complex_method # rubocop:disable Metrics`

It seems good to me that it can be specified by department. because there are similar specification options such as `rubocop --only department` and enabling/disabling by department in .rubocop.yml. It does not bring in new complexity.

The only concern is that the specified department's cops hidden in the department may not be able to detect an offense. However, it shouldn't be the issue as user will accept the risk and specify it.

**Comment by AndreiEres** [comment]
I'm working on the class that's responsible for this thing. So further I can implement that. @koic could you assign this issue to me?

**Comment by bbatsov** [comment]
@AndreiEres Done.

**Comment by AndreiEres** [comment]
https://github.com/rubocop/rubocop/pull/9630

- Added department checking to Registry
- Added list of names for department to Registry

**Comment by AndreiEres** [comment]
I think it can be done with https://github.com/rubocop/rubocop/pull/9626
- Added checking for department only to directive comment.
- Added note about new feature to documentation.

@bbatsov or other, could you take a look?

**Comment by AndreiEres** [comment]
Guys, I discovered that disabling of all department has consequences. How we can deal with redundant department disabling? I realised that the best way — do not use RedundantCopDisabling, but create another cop — RedundantDepartmentDisabling. So we will ignore department disabling in RedundantCop processing and check it only for RedundantDepartment.

What do you think?

**Comment by dvandersluis** [comment]
Don't they have to work together? As I mentioned in #9563, if a department is disabled, disabling a specific cop below it is redundant. 

```ruby
# rubocop:disable Metrics
...
# rubocop:disable Metrics/Foo <-- redundant
```

**Comment by AndreiEres** [comment]
Oh, it's true. If we split that cops we can't catch that interference. Hard thing :-)
