### ISSUE TITLE
Documentation site broken for Lint

### ISSUE THREAD

**Issue by unikitty37** [rubocop/rubocop#9530]
The documentation page for Lint cops is broken past [Lint/Debugger](https://docs.rubocop.org/rubocop/1.10/cops_lint.html#lintdebugger):

![image](https://user-images.githubusercontent.com/139183/108989430-7b896400-768d-11eb-91bc-72a67fb02a01.png)

174bda38 looks like it should already fix this, but it's not live — could somebody please deploy it?

**Comment by koic** [comment]
The doc for the master branch has been synced. On the other hand, there is no backporting to released docs, so please refer master or the doc to be next released. Thank you.
https://docs.rubocop.org/rubocop/cops_lint.html#lintdebugger
