### ISSUE TITLE
AllCops::SuggestExtensions provides links to repositories that do not exist

### ISSUE THREAD

**Issue by zfletch** [rubocop/rubocop#9556]
When I run RuboCop on a project that has `rspec` as a dependency, it triggers `RuboCop::CLI::Command::SuggestExtensions` (as expected). However, the URL it provides (http://github.com/rubocop/rubocop-rspec) is for a repository that doesn't exist. I believe that the URL should be https://github.com/rubocop-hq/rubocop-rspec. The same problem occurs with `rubocop-sequel` but not with the other suggested extensions.

This is happening because `http://github.com/rubocop/` is [hard coded](https://github.com/rubocop/rubocop/blob/930c812d3706a2cd647bdb20cb9c4a6d7a7ae35d/lib/rubocop/cli/command/suggest_extensions.rb#L25) and used for every suggested extension. If I'm understanding the code correctly, the second part of the URL is coming from [config/default.yml](https://github.com/rubocop/rubocop/blob/930c812d3706a2cd647bdb20cb9c4a6d7a7ae35d/config/default.yml#L147).

(If this code gets changed, it might also be an opportunity to update to `https`.)

--------

## Expected behavior

```
Inspecting 8 files
........

8 files inspected, no offenses detected

Tip: Based on detected gems, the following RuboCop extension libraries might be helpful:
  * rubocop-rspec (http://github.com/rubocop-hq/rubocop-rspec)

You can opt out of this message by adding the following to your config (see https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
  AllCops:
    SuggestExtensions: false
```

## Actual behavior

```
Inspecting 8 files
........

8 files inspected, no offenses detected

Tip: Based on detected gems, the following RuboCop extension libraries might be helpful:
  * rubocop-rspec (http://github.com/rubocop/rubocop-rspec)

You can opt out of this message by adding the following to your config (see https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
  AllCops:
    SuggestExtensions: false
```

## Steps to reproduce the problem

1. Create a new project
2. Add RuboCop (`gem 'rubocop'`)
3. Add Rspec (`gem 'rspec'`)
4. Run RuboCop

## RuboCop version

1.11.0

**Comment by dvandersluis** [comment]
It was updated with the expectation that the remaining repos would be moved from the rubocop-hq org to this one, but that hasn't happened yet. @bbatsov?

I will fix the `http`->`https` issue.

**Comment by bbatsov** [comment]
> It was updated with the expectation that the remaining repos would be moved from the rubocop-hq org to this one, but that hasn't happened yet. @bbatsov?

Because I forgot to do it. 😆 I'll move the rest of the repos over later today.

**Comment by bbatsov** [comment]
That's fixed already. All repos are now moved to the new `rubocop` org.

**Comment by zfletch** [comment]
Thanks @dvandersluis and @bbatsov!
