### ISSUE TITLE
CommentConfig needs ♥️

### ISSUE THREAD

**Issue by AndreiEres** [rubocop/rubocop#9563]
This class parses the special `rubocop:disable` comments in a source and provides a way to check if each cop is enabled at arbitrary line.
`lib/rubocop/comment_config.rb`

## Problem

1. First of all it looks like a huge class. Over 200 lines.

2. Class has many public methods, but tested only `cop_enabled_at_line?`.

3. There are many cases with direct using private constant:

```
lib/rubocop/directive_comment.rb:
  16:       match = comment.text.match(CommentConfig::COMMENT_DIRECTIVE_REGEXP)

lib/rubocop/cop/lint/redundant_cop_disable_directive.rb:
  177:           match = comment.text.match(CommentConfig::COMMENT_DIRECTIVE_REGEXP)

lib/rubocop/cop/mixin/documentation_comment.rb:
  48:         CommentConfig::COMMENT_DIRECTIVE_REGEXP.match?(comment.text)

lib/rubocop/cop/mixin/line_length_help.rb:
  19:         comment.text.match?(CommentConfig::COMMENT_DIRECTIVE_REGEXP)
  82:         before_comment, = line.split(CommentConfig::COMMENT_DIRECTIVE_REGEXP)

lib/rubocop/cop/style/disable_cops_within_source_code_directive.rb:
  73:           match = CommentConfig::COMMENT_DIRECTIVE_REGEXP.match(comment.text)

lib/rubocop/ext/processed_source.rb:
  8:         @comment_config ||= CommentConfig.new(self)
```

## Soluttion

Refactor class. We have `DirectiveComment` that can get part of functionality. Add additional specs.

## One more thing

Later we can add `disable-next-line` feature. See: https://github.com/rubocop/rubocop/issues/9505

**Comment by AndreiEres** [comment]
Here is first suggestion https://github.com/rubocop/rubocop/pull/9567

**Comment by AndreiEres** [comment]
Related PR https://github.com/rubocop/rubocop/pull/9567

**Comment by AndreiEres** [comment]
For third item I moved directive comment matching to DirectiveComment. 
https://github.com/rubocop/rubocop/pull/9569

Comments welcome :-)

**Comment by AndreiEres** [comment]
Added readability to CommentConfig spec source by replacing string joining with heredoc.
https://github.com/rubocop/rubocop/pull/9577

Also comments welcome :-)

**Comment by AndreiEres** [comment]
And added missing spec for CommentConfig#cop_disabled_line_ranges
https://github.com/rubocop/rubocop/pull/9578

**Comment by AndreiEres** [comment]
CommentConfig#directive_parts replaced with DirectiveComment instance.
Further I'm going to continue move moving part of responsibility to DirectiveComment
https://github.com/rubocop/rubocop/pull/9589

**Comment by AndreiEres** [comment]
Closing PR https://github.com/rubocop/rubocop/pull/9610

- Refactored CommentConfig
- Extra logic moved to DirectiveComment

**Comment by dvandersluis** [comment]
@AndreiEres thanks for your work on this! The code changes are looking great. :heart:

I think we need to consider some edge cases that might be introduced by the changes:

```ruby
# rubocop:disable Foo/Bar
...
# rubocop:enable Foo <-- is this valid?
```

```ruby
# rubocop:disable Foo
...
# rubocop:enable Foo/Bar <-- are the other Foo department cops still disabled?
#                        <-- how will disable Foo be switched off at this point? 
```

```ruby
# rubocop:disable-next-line Foo/Bar
do_something
# rubocop:enable Foo/Bar <-- is Lint/RedundantCopEnableDirective registered?
```

```ruby
# rubocop:disable-next-line Foo/Bar
do_something # rubocop:disable Foo/Bar <-- is Lint/RedundantCopDisableDirective registered?

```ruby
# rubocop:disable Foo
do_something # rubocop:disable Foo/Bar <-- is Lint/RedundantCopDisableDirective registered?
```

There are probably more edge cases to consider but these are some I thought of 😅

**Comment by AndreiEres** [comment]
```ruby
# rubocop:disable Metrics/MethodLength
def some_method
  puts 'foo'
end
# rubocop:enable Metrics
```

It works, but adds extra keys to `CommentConfig#cop_disabled_line_ranges`.

```ruby
{
  "Metrics/MethodLength" => [1..5], 
  "Metrics/CyclomaticComplexity" => [], 
  "Metrics/AbcSize" => [], 
  "Metrics/BlockLength" => [], 
  "Metrics/BlockNesting" => [], 
  "Metrics/ClassLength" => [], 
  "Metrics/ModuleLength" => [], 
  "Metrics/ParameterLists" => [], 
  "Metrics/PerceivedComplexity" => []
}
```

**Comment by AndreiEres** [comment]
```ruby
# rubocop:disable Metrics
def some_method
  puts 'foo'
end
# rubocop:enable Metrics/MethodLength
```

It also works as expected. We've enabled only one cop.

```ruby
{
  "Metrics/CyclomaticComplexity" => [1..Infinity], 
  "Metrics/AbcSize" => [1..Infinity], 
  "Metrics/BlockLength" => [1..Infinity], 
  "Metrics/BlockNesting" => [1..Infinity], 
  "Metrics/ClassLength" => [1..Infinity], 
  "Metrics/MethodLength" => [1..5], 
  "Metrics/ModuleLength" => [1..Infinity], 
  "Metrics/ParameterLists" => [1..Infinity], 
  "Metrics/PerceivedComplexity" => [1..Infinity]
}
```

**Comment by AndreiEres** [comment]
I think we can close the issue but keep in the head this recommendation https://github.com/rubocop/rubocop/issues/9563#issuecomment-804999841

**Comment by AndreiEres** [comment]
@dvandersluis Could we close the issue?
