### ISSUE TITLE
👉 More semantic offense expectation matchers

### ISSUE THREAD

**Issue by Drenmi** [rubocop/rubocop#9654]
## Background

While the current test matchers are super convenient, I think we can always do better. In particular, we could be a bit more semantic in our choice of character to use to highlight the location of the offense.

## Proposal

Exchange the existing `^` style for a more semantic emoji version: 👆.

**Before:**

```ruby
expect_offense(<<~RUBY)
  something { |number_One| do_stuff }
               ^^^^^^^^^^ Only use lowercase characters for block parameter.
RUBY
```

**After:**

```ruby
expect_offense(<<~RUBY)
  something { |number_One| do_stuff }
               👆👆👆👆👆👆 Only use lowercase characters for block parameter.
RUBY
```

This would unlock some additional possibilities, like putting the expectation on top when that clarifies the surrounding code by running less interference:

```ruby
expect_offense(<<~RUBY)
               👇👇👇👇👇👇 Only use lowercase characters for block parameter.
  something { |number_One| do_stuff }
RUBY
```

We could even do something like introduce a new, explicit syntax for no offenses:

```ruby
expect_no_offenses(<<~RUBY)
  something { |number_one| do_stuff }
               👍
RUBY
```

The possibilities are endless!

**Comment by koic** [comment]
It's an interesting idea, but it's a better approach to keep the same `^` as the default formatter that RuboCop uses by default. This is an arrangement of the idea, it may be provided as an alternative formatter (Like a pacman formatter) 😃

**Comment by dvandersluis** [comment]
@Drenmi that's a good idea but one could argue that it could be taken even further. Instead of `expect_offense` and `expect_no_offenses` we could use ❌ and ✅. And instead of `<<~RUBY`, how about `<<~💎`?

```ruby
❌(<<~💎)
  something { |number_One| do_stuff }
               👆👆👆👆👆👆 Only use lowercase characters for block parameter.
💎

✅(<<~💎)
  something { |number_one| do_stuff }
               👍
💎
```

**Comment by Drenmi** [comment]
@dvandersluis Now you’re cooking with mayonnaise! 🙃
