### ISSUE TITLE
Style/RedundantBegin should be marked as unsafe for auto-correction

### ISSUE THREAD

**Issue by gPrado** [rubocop/rubocop#9681]
Style/RedundantBegin cop might auto-correct code incorrectly, leading to a performance issue or even a broken build. See example below:

--------

## Precondition

Given the following example class

```ruby
class Test
  def initialize
    @first_run = false
  end

  def memoized
    @memoized ||= begin
      'memoized' if first_run
    end
  end

  def first_run
    # this might be an expensive operation
    fail 'already run!' if @first_run

    @first_run = true
  end
end
```

and the following test code:
```ruby
test = Test.new
2.times { test.memoized }
```

## Expected behavior

The code should not be auto-corrected, or maybe auto-corrected as the following:

```ruby
class Test
  def initialize
    @first_run = false
  end

  def memoized
    @memoized ||= ('memoized' if first_run)
  end

  def first_run
    # this might be an expensive operation
    fail 'already run!' if @first_run

    @first_run = true
  end
end
```

## Actual behavior

The code is auto-corrected as follows:

```ruby
class Test
  def initialize
    @first_run = false
  end

  def memoized
    @memoized ||= 'memoized' if first_run
  end

  def first_run
    # this might be an expensive operation
    fail 'already run!' if @first_run

    @first_run = true
  end
end
```

which makes the test code raise an exception.

## RuboCop version

1.12.1 (using Parser 3.0.1.0, rubocop-ast 1.4.1, running on ruby 2.6.6 x86_64-linux)

**Comment by koic** [comment]
Thank you for the feedback. This is an auto-correction bug, so I opened #9682 that it will be safe auto-corrected code.
