### ISSUE TITLE
Parser issue

### ISSUE THREAD

**Issue by RCarteri** [rubocop/rubocop#9700]
Hello, I'm using VS code and every time I open a warning appears with the following message:
```
warning: parser/current is loading parser/ruby27, which recognizes warning: 2.7.3-compliant syntax, but you are running 2.7.2. 

warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```

Could you help me to solve this problem? I need to use the 2.7.2 version of Ruby.
```
PS C:\Users\ricardo.uehlein\Documents\capacitacao-qualidade-de-software> rubocop -V
warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.3-compliant syntax, but you are running 2.7.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
1.12.1 (using Parser 3.0.1.0, rubocop-ast 1.4.1, running on ruby 2.7.2 x64-mingw32)
```
```
PS C:\Users\ricardo.uehlein\Documents\capacitacao-qualidade-de-software> gem install parser
Successfully installed parser-3.0.1.0
Parsing documentation for parser-3.0.1.0
Done installing documentation for parser after 10 seconds
1 gem installed
```
```
PS C:\Users\ricardo.uehlein\Documents\capacitacao-qualidade-de-software> rubocop -V        
warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.3-compliant syntax, but you are running 2.7.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
1.12.1 (using Parser 3.0.1.0, rubocop-ast 1.4.1, running on ruby 2.7.2 x64-mingw32)
```

**Comment by bbatsov** [comment]
You can ignore this warning, as it's harmless most of the time. That's outside of our team's control, so we can don't anything about the warning.

**Comment by koic** [comment]
Parse 3.0.0.1 is compatible with Ruby 2.7.3.
https://github.com/whitequark/parser/blob/master/CHANGELOG.md#v3010-2021-04-06

Parser 3.0.0.0 is compatible with Ruby 2.7.2 and you can suppresses the warning by downgrading to Parser 3.0.0.0 in your environment. But I don't recommend it as you can ignore the warning..

**Comment by RCarteri** [comment]
Thanks for the answers.
koic, how can I downgrade the parser to 3.0.0.0?

**Comment by koic** [comment]
You may be able to downgrade below.

```console
% gem uninstall parser -v 3.0.1.0 && gem i parser:3.0.0.0
```

**Comment by RCarteri** [comment]
Thanks

**Comment by marcandre** [comment]
We actually could do something about it and just silence that warning. Let me put up a PR.

**Comment by marcandre** [comment]
Next version of RuboCop will not issue such warnings 👍
