### ISSUE TITLE
Add a cop for Ruby 3 deprecated methods in Socket

### ISSUE THREAD

**Issue by tas50** [rubocop/rubocop#9716]
## Is your feature request related to a problem? Please describe.

Ruby 3 deprecates  Socket.gethostbyaddr and Socket.gethostbyname. See https://bugs.ruby-lang.org/issues/13097. It would be really great if RuboCop would detect these deprecated methods to cleanup codebases automatically.

## Describe the solution you'd like

Detection and correction of the legacy methods.

**Comment by AndreiEres** [comment]
I can't imagine how we can autocorrect that. Could you explain it? Or we can do it without autocorrection.

**Comment by tas50** [comment]
It should get flagged even if it can't be autocorrected, but the error message gives a pretty clear update for most use cases.

**Comment by bbatsov** [comment]
Agreed.
