### ISSUE TITLE
Add Layout/RedundantLineBreak EnforcedStyle

### ISSUE THREAD

**Issue by bkuhlmann** [rubocop/rubocop#9733]
## Is your feature request related to a problem? Please describe.

By the way, thanks for adding this cop. Looking forward to making more use of it. :tada:

Would it be possible to add an `EnforcedStyle` to this cop so one could configure the cop to *avoid nested blocks*? Example:

``` yaml
Layout/RedundantLineBreak:
  Enabled: true
  EnforcedStyle: suffixed_blocks_only
```

Not married to my choice of words so if there is a better way to describe this, go for it. Mostly trying to identify a way in which to define this.

## Describe the solution you'd like

For example, default behavior will reformat code as follows:

``` ruby
# No
example.select { |item| item.cond? }.join('-')
```

However, I'd like to ensure this remains untouched as follows:

``` ruby
# Yes
example.select { |item| item.cond? }
       .join('-')
```

The reason is due to the block syntax since I'd like to avoid chaining blocks unless they are at the end. For example this, would be acceptable:

``` ruby
# Yes
example.split.each { |item| put item }
```

Notice the block is only at the end of the chain. This reads well because the eye can quickly scan a series of chained messages ending with a block. By slipping the block in the middle, reading the code becomes jarring, especially if multiple blocks are chained together (as multi-chained blocks can get out of hand quickly and would like to discourage that use).

## Describe alternatives you've considered

I don't know if any other alternative solutions to this problem at the moment.

## Additional context

If it helps, I do consider message chaining with blocks to be an antipattern and have written up a more detailed reason for avoiding this usage in this [article](https://www.alchemists.io/articles/ruby_antipatterns/#_message_chains) in case it's of help.

**Comment by bbatsov** [comment]
I don't think this fits the typical use case for an enforced style, but it can potentially be some flag. On the other hand I'm a bit wary of the going over the top with configuration for the cop - there's already a setting to ignore blocks and if we start all the different ways in which blocks should or not be reformatted it can get pretty complex for a small ROI. Anyways, I'll defer to @jonas054 on this topic.

**Comment by bkuhlmann** [comment]
:bow: **Bozhidar**. True...couldn't think of a better way to categorize this, initially. Maybe `AllowSuffixedBlocksOnly: true` would be a way to better describe this option? Anyway, you are correct that this introduces a bit more complexity. If it helps -- and what I like about this style the most -- is that it forces one to pause and resolve potentially complex multi-block code with further abstraction/refactoring so one doesn't have to sift through a quagmire of chained brackets (`{}`) or even `do..end`'s for that matter. 😅

**Comment by jonas054** [comment]
In my option, the thing we're talking about here (not chaining a method call onto a block on the same line), is a separate concern not directly related to the `Layout/RedundantLineBreak` cop. I'd like to add a new cop, `Layout/SingleLineBlockChain` to enforce this style. I don't expect the enforced style of this new cop to be main stream, exactly. So `Enabled: false` should be the default setting.

Then I just need to make `Layout/RedundantLineBreak` aware of the new cop so they don't get into an infinite auto-correct loop.

**Comment by bkuhlmann** [comment]
:bow: **Jonas**. Yeah, the distinction of having a new cop for this makes sense to me and is probably a better way to break this out and describe this style better.
