### ISSUE TITLE
Make `RangeHelp` consistent

### ISSUE THREAD

**Issue by dvandersluis** [rubocop/rubocop#9760]
All methods in `RangeHelp` that take a range do so with a positional argument, other than `range_with_surrounding_space` which uses a kwarg. For consistency, `range_with_surrounding_space` should also use a positional argument.

Changing the signature of this method will impact other RuboCop extensions which will have to be updated, so 2.0 may be a good time to do this.

**Comment by pirj** [comment]
`RangeHelp` is [now](https://github.com/rubocop/rubocop/pull/10748) pretty consistent. We may eventually want to deprecate the old kwarg, but it's not for 2.0.
Should we keep this to remember of would willingness to deprecate kwarg, or close this ticket?

**Comment by pirj** [comment]
Can we consider this done?

**Comment by dvandersluis** [comment]
Seems done to me! Thanks @pirj
