### ISSUE TITLE
RuboCop suggests extension libraries although loaded

### ISSUE THREAD

**Issue by fnordfish** [rubocop/rubocop#9810]
I'm using rubocop by wrapping it in an inline bundler script like this:

```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler"
require "bundler/inline"

Bundler.settings.temporary(frozen: false, deployment: false) do
  gemfile do
    source "https://rubygems.org"
    platform "ruby" do
      gem 'rubocop', '1.15.0'
      gem 'rubocop-rails'
      gem 'rubocop-rspec'
    end
  end
end
load Gem.bin_path("rubocop", "rubocop")
```

I see the `rubocop-rails` and `rubocop-rspec` extensions doing their job, when I (purposefully) add some errors. Also, `bin/rubocop -V` lists them as well (see below).
I find the suggestions helpful, and don't want to just disable them via `SuggestExtensions: false`.

--------

## Expected behavior

RuboCop does not show the tip to add the extensions I already have added.

## Actual behavior

```console
$ bin/rubocop
[...]
Tip: Based on detected gems, the following RuboCop extension libraries might be helpful:
  * rubocop-rails (https://github.com/rubocop/rubocop-rails)
  * rubocop-rspec (https://github.com/rubocop/rubocop-rspec)

You can opt out of this message by adding the following to your config (see https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
  AllCops:
    SuggestExtensions: false
```

## Steps to reproduce the problem

Setup an empty Rails project with rspec as testing framework. Copy the above script into `bin/rubocop` and `chmod +x bin/rubocop`.  Run it like usual.

## RuboCop version

```
$ bin/rubocop -V
1.15.0 (using Parser 3.0.1.1, rubocop-ast 1.5.0, running on ruby 3.0.1 x86_64-linux)
  - rubocop-rails 2.10.1
  - rubocop-rspec 2.3.0
```

**Comment by dvandersluis** [comment]
Hi @fnordfish, RuboCop currently looks at your `Gemfile.lock` to determine what extensions are loaded. I've never seen an inline bundler call like that.

You can explicitly disable the suggestions for those extensions:

```
AllCops:
  SuggestExtensions:
    rubocop-rails: false
    rubocop-rspec: false
```

Or for all extensions:

```yml
AllCops:
  SuggestExtensions: false
```

**Comment by fnordfish** [comment]
> RuboCop currently looks at your Gemfile.lock to determine what extensions are loaded

This was my guess, but weirdly `rubocop -V` seems to something different.

> Is there any reason you can't add the gems to your gemfile?

Well, I probably could, but I don't like to, here's why:
1. I try to keep my application dependencies to a minimum, so everything that does not need to be loaded along with my applications code, I put into an inline-bundler scipts.
2. This way RuboCop (for example) can have it's own dependencies while other tools, and my app, can have their own even conflicting dependencies.

I haven't run into dependency-conflict issues with rubocop lately, but I did some time ago, and this is just a preemptive measure.

Thanks for your suggestion, disabling only extensions I know I already have. That sounds like a feasible workaround.

**Comment by dvandersluis** [comment]
Yeah unfortunately the mechanism is different between suggested extensions and the loaded extensions.

I'm going to close this for right now because I don't think there'll be an easy fix here and there is a workaround.
