### ISSUE TITLE
[Doc] "GitHub Org" guides us to old "rubocop-hq" org

### ISSUE THREAD

**Issue by okuramasafumi** [rubocop/rubocop#9860]
## Expected behavior

The link "GitHub Org" in the doc should guides us to "rubocop" org.

## Actual behavior

The link "GitHub Org" in the doc should guides us to "rubocop-hq" org.

## Steps to reproduce the problem

Go to https://docs.rubocop.org/rubocop/1.16/index.html ,click "Community" at the top right and click "GitHub Org".

**Comment by koic** [comment]
I updated the doc site. Thank you!
