### ISSUE TITLE
Make enforcement of colon after comment annotation configurable

### ISSUE THREAD

**Issue by mojavelinux** [rubocop/rubocop#9890]
If the Style/CommentAnnotation rule is enabled, RuboCop requires that the annotation name be followed by a colon. In both the IntelliJ IDEs and the Eclipse IDE, the convention is to omit the colon. (See https://www.jetbrains.com/help/idea/using-todo.html and https://www.vogella.com/tutorials/Eclipse/article.html#task-management). It's fair to say that omitting the colon is also a well-established convention (especially in mixed programming language teams). However, if we write comment annotations (aka task tags) this way, this RuboCop rule is not usable since it gets stuck on the missing colon (rather than the annotation names).

I wish to see an enforced style (or something of the sort) that allows the colon to be omitted. The rule can then still fulfill its primary function while accommodating this style variation.

What we are talking about is being able to reverse the bad and good cases in the cited section of the Ruby style guide: https://rubystyle.guide/#annotate-keywords

**Comment by bbatsov** [comment]
I'm fine with making this configurable. I've also noticed that in other communities it's quite common to write those annotations sans the `:`.

**Comment by themilkman** [comment]
Generally great option.
Wouldn't an "ignore" parameter make sense? Instead of forcing color or forbidding it?
