### ISSUE TITLE
Make --disable-uncorrectable disable where unsafe autocorrection is possible

### ISSUE THREAD

**Issue by yitznewton** [rubocop/rubocop#9921]
## Is your feature request related to a problem? Please describe.

It appears impossible to use `--disable-uncorrectable` for offenses which could be unsafely autocorrected.

## Describe the solution you'd like

I would like the option/default for `rubocop -a --disable-uncorrectable` to disable for offenses are eligible for unsafe autocorrection.

## Additional context

```
$ rubocop --only=Rails/WhereEquals -a --disable-uncorrectable -- app/models/group.rb 
Inspecting 1 file
C

Offenses:

app/models/group.rb:33:21: C: [Correctable] Rails/WhereEquals: Use where(groups: { status: :done }) instead of manually constructing SQL.
  scope :done, -> { where('groups.status = ?', :done) }
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 more offense can be corrected with `rubocop -A`
```

**Comment by yitznewton** [comment]
I see this was already raised in #7958

**Comment by jonas054** [comment]
Closing as duplicate.
