### ISSUE TITLE
using & with empty? cops back and forth

### ISSUE THREAD

**Issue by badal** [rubocop/rubocop#9924]
Rubocop 0.77.0

Using  thing && thing.empty?  =>  Cop says : use  &.empty?
Using  thing&.empty? => Cop says  : don't use & with empty?

**Comment by jonas054** [comment]
This bug was fixed in #8654 and released in RuboCop 0.91.0.

**Comment by badal** [comment]
Ah, I understand. I am stuck with ruby 2.4, as I need qtbindings not available on ruby > 2.4.

 

Michel Demazure

 ***@***.***> ***@***.***

 

De : Jonas Arvidsson ***@***.***> 
Envoyé : samedi 10 juillet 2021 23:45
À : rubocop/rubocop ***@***.***>
Cc : Michel Demazure ***@***.***>; Author ***@***.***>
Objet : Re: [rubocop/rubocop] using & with empty? cops back and forth (#9924)

 

This bug was fixed in #8654 <https://github.com/rubocop/rubocop/pull/8654>  and released in RuboCop 0.91.0.

**Comment by jonas054** [comment]
Support for Ruby 2.4 was dropped in RuboCop 1.13.0, so you should still be able to upgrade to a RuboCop version where this bug is fixed.

**Comment by badal** [comment]
OK. Thanks !

 

Michel Demazure

 ***@***.***> ***@***.***

 

De : Jonas Arvidsson ***@***.***> 
Envoyé : dimanche 11 juillet 2021 08:31
À : rubocop/rubocop ***@***.***>
Cc : Michel Demazure ***@***.***>; Author ***@***.***>
Objet : Re: [rubocop/rubocop] using & with empty? cops back and forth (#9924)

 

Support for Ruby 2.4 was dropped in RuboCop 1.13.0, so you should still be able to upgrade to a RuboCop version where this bug is fixed.
