### ISSUE TITLE
WordArray should enforce bracket style for strings that don't match WordRegex

### ISSUE THREAD

**Issue by rickselby** [rubocop/rubocop#9962]
## Is your feature request related to a problem? Please describe.

Given that WordArray won't suggest changing `['string with space', 'string']` to `%w[string\ with\ space string]`, should it suggest changing `%w[string\ with\ space string]` to `['string with space', 'string']`?

## Describe the solution you'd like

WordArray should enforce bracket style for arrays that contain strings that don't match WordRegex

**Comment by bbatsov** [comment]
Sounds reasonable to me. I guess we never did this, as it's extremely uncommon to come across such code.
